### ISSUE TITLE
Refactor Ticket

### ISSUE THREAD

**Issue by jacqueswww** [vyperlang/vyper#1024]
Just a brain dump, to be taken lightly, but a list of items we should consider refactoring:

* [x] Move type and structure exceptions into it's own layer. Once you get to ast->lll step you don't want to worry about types.
* [x] Move external call logic from stmt.py and expr.py into it's own module.
* [x] Move constant folding into it's own compilation step.
* [ ] Refactor arg packing functions, one implementation that works for all use cases.
* [x] Check if we should consider spinning off basetype into subtypes (with their own classes).
* [ ] Consider breaking up parse_func some more, and moving function parsing steps into parser/functions.py
* [x] Opportunity to leverage class inheritance in Vyper codebase - https://github.com/ethereum/vyper/issues/1032

**Comment by charles-cooper** [comment]
hide member variables like `context.vars` and control access via API. that would prevent bugs like a5728a1bb4c75fc097498c6be778d1c85e004e98.

**Comment by fubuloubu** [comment]
We should update this issue for current progress

**Comment by fubuloubu** [comment]
> Refactor arg packing functions, one implementation that works for all use cases.

@charles-cooper, you took care of this right?

**Comment by charles-cooper** [comment]
> > Refactor arg packing functions, one implementation that works for all use cases.
> 
> @charles-cooper, you took care of this right?

Yeah there is theoretically a single arg packing function (abi encode) but it hasn't gotten spliced in uniformly across the codebase.

**Comment by fubuloubu** [comment]
> > > Refactor arg packing functions, one implementation that works for all use cases.
> > 
> > 
> > @charles-cooper, you took care of this right?
> 
> Yeah there is theoretically a single arg packing function (abi encode) but it hasn't gotten spliced in uniformly across the codebase.

Nice, but IIRC it can be used as such? Aka we can start to integrate the ABI encoder? (perhaps combining the type systems together)

**Comment by iamdefinitelyahuman** [comment]
Mostly finished this - added a `refactor` issue tag that we can use going forward.
