### ISSUE TITLE
Opportunity to leverage class inheritance in Vyper codebase?

### ISSUE THREAD

**Issue by davesque** [vyperlang/vyper#1032]
### What's your issue about?

I noticed a place where it seems like we might be able to re-structure some Vyper code to be a bit more object oriented and to use some more natural Python idioms.  Specifically, here's what seems like a problem section of code:

https://github.com/ethereum/vyper/blob/master/vyper/parser/stmt.py#L51-L77

In the `Stmt.__init__` method, we're doing a dynamic dispatch to a method on the `Stmt` class based on the type of the Python AST node that is used to construct the `Stmt` instance.  This seems a bit weird since the `Stmt` class then ends up representing *all* of the different kinds of statements.  Furthermore, the method names (`parse_...`) don't really represent the action that is taking place which is that the Python AST node is being converted to its intermediate representation in LLL.

### How can it be fixed?

One possible alternative to the dynamic dispatch in the `__init__` method is to define a base `Stmt.from_ast` class method.  This method could choose which one of a number of subclasses of `Stmt` to instantiate and use for the conversion to LLL.  Each `Stmt` subclass could be named something like `If`, `For`, `Return`, etc. and they could all implement a `to_lll` method.

Here are some advantages of this approach:

* It's common in Python and other OO langs for there to be a class hierarchy with a subclass for each kind of object or task that you're working with.  New programmers coming to the project could have an easier time applying general OO principles to Vyper.
* The implementations of `to_lll` for each subclass could call out to other methods present on the subclasses.  Subclasses could override or inherit these other methods in various ways.  That could make it easier to re-use and/or slightly modify different common pieces of code that are used in converting similar kinds of statements.

#### Cute Animal Picture

![Cute Animal Picture](http://2.bp.blogspot.com/-bBCuRrUXpK4/UFb2_pkm6uI/AAAAAAAAArI/rYYCM2BmENs/s1600/Red+Panda+Walking.jpg)

**Comment by fubuloubu** [comment]
I like it! Can you make a toy example of how this might look in practice? I believe I understand the concept (create a Vyper-specific set of objects for it's own internal AST) and see the utility in modularizing the codebase, making it easier to work on.

---

In my mind, this looks like:
```python
py_ast = ast.parse(code)  # Returns root of tree from python's ast module

vy_ast = Stmt.from_ast(py_ast)  # Returns root of tree from Vyper's AST classes
# NOTE: Perhaps rename `Stmt` to `vyAST` or `vyNode` as a base class,
#       and using the `vy*` prefix so as not to conflict with some of Python's AST classes

lll = vy_ast.to_lll()  # Convert to LLL list form (opcodes and integers)

bin = compile_lll(lll)  # Convert LLL nodes to binary opcodes
```

I think there is also the added burden of calculating storage slots, but this can be done by having `vyContract.to_lll()` method compute the base storage slot for each `vyVariable` it contains using an incrementing slot counter (something I never had the chance to add to blocktract). Any other `vyAST` objects that references a specific `vyVariable` would have to use it's rules to calculate the storage slot in-process. For mappings, this might look like a `vyMappingAccessor` that references a mapping `vyVariable` sub-type, performing the hash-based key lookup to find the location of the corresponding storage slot relative to it's parent slot. Something similar for arrays.

Still thinking this out in my head, hopefully this is useful... haha.

**Comment by davesque** [comment]
Nice, glad you like it.  What you have in mind might be a bit more far-reaching.  What I imagined was more specifically meant to address the oddness of the dynamic dispatch via the dictionary in the `__init__` method and the lack of congruence between specific actions being performed by the code and the existence (or non-existence as it were) of subclasses which correspond with those actions.  I'll try and cook up an example in the next day.  I bet what I'm thinking about could eventually be adapted to be more powerful and suitable for what you had imagined.

Another thing I might add is that, if we do have a hierarchy of classes for internal AST tasks, my opinion is that they should probably begin with `Vy` or maybe with no prefix at all.  Either way, they should start with an uppercase letter.  Otherwise, a lot of Python IDEs or code linters will probably complain that classes shouldn't begin with a lowercase letter :).

**Comment by fubuloubu** [comment]
Fair enough lol

**Comment by jacqueswww** [comment]
I do think there is scope for this, I think we should go this route after we take care of the type checking and constant folding cycles (it would make the most sense to do it after this has been done).

I have added this item our refactor ticket #1024 :)
