### ISSUE TITLE
VIP: Give iterator variables a type

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1039]
## Simple Summary
Allow specifying a type for iterator variables in `range(N)` iterator

## Abstract
Currently, iterator variables are assumed to be `int128`. We should allow other types to be used

## Motivation
Without the ability to specify types, someone would have to do a convert to do this same functionality.

## Specification
It would look like this
```python
for x in range(N, type=bytes32):
    # Do stuff...
```
`type` can be any valid vyper base type which has an increasing order to it.

## Backwards Compatibility
Backwards compatible if `type` is defaulted to `int128`

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Yes, I think it should be implemented in some fashion. It's useful

**Comment by charles-cooper** [comment]
i'm closing this as superseded by #3596. please reopen if it's still a desired feature!
