### ISSUE TITLE
VIP: Allow usage of min with a literal to set iterators

### ISSUE THREAD

**Issue by ElianaTroper** [vyperlang/vyper#1047]
## Simple Summary
Allow usage of min with a literal to set iterators e.g. min(22, len(someBytes))

## Abstract
Currently, iterators must be set with a literal. A minimum which contains a literal reasonably should be no larger than said literal, but could theoretically be smaller based upon the other value.

## Motivation
This could reduce the number of loops used (and any calls contained within) in situations where the minimum number of loops may fall below a set value e.g. looping over a byte array of max length 64, but it may be shorter.

## Specification
I would expect a contract similar to the following to compile

```
@private
def __main__(input: bytes[64]) -> int128:
    _x: int128 = 0
    _len: int128 = len(input)
    for i in range(min(64, _len)):
        _x = i
    return _x
```

## Backwards Compatibility
Yes, doesn't change any previously compatible literal inputs for range

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Well, I think `for var in ls: ...` covers the majority of the use cases you might have here.

The one modification is that since `len(ls)` is actually always a constant (since we disallow dynamic arrays), we could allow this syntax  in place of having to write the numbers everywhere.

But again, since we have named constants now, you could just use that everywhere too e.g.
```python
N: constant(uint8) = 64

@private
def __main__(input: bytes[N]) -> int128:
    _x: int128 = 0
    _len: int128 = len(input)
    for i in range(N):
        _x = i
    return _x
```

**Comment by jacqueswww** [comment]
We discussed this issue at our meeting yesterday.  We came to the conclusion that we would need more details from the specific use case required, but we did come with two sensible use cases:

1.) iterating per byte until len of a bytearray.
```python
input: bytes[100] = "test data"
for idx, b in enumerate(input):
```

2.) whitelisting a statement of `for i in len(bytes[x])` which would iteration of the len value.
```python
input: bytes[100] = "test data"
for i in enumerate(input):
```

@SamuelTroper What are your thoughts?

**Comment by fubuloubu** [comment]
I'd like to note that `bytes[100]` is a "number of bytes less than or equal to 100". Therefore both iterator and `len()` should return 9, the length of the actual data (I think)

**Comment by SamuelTroper** [comment]
@jacqueswww assuming 2 is supposed to be

```input: bytes[100] = "test data"
for i in len(input):```

I think that would solve the use case I was thinking of. Additionally, if that were implemented you could effectively get the result of 1) just by slicing the input to one byte.

**Comment by fubuloubu** [comment]
I think 2 is actually `for i in range(len(input))` which should output `0..8` if `input` is of length 9.

Your use case sounds sort of like RLP decoding. We have a macro for that.

**Comment by SamuelTroper** [comment]
@fubuloubu I hadn't looked into RLP much before but man that's a nice standard. Thanks for pointing that out.

**Comment by fubuloubu** [comment]
The following works:
```python
@public 
def test(input: bytes32[64]): 
    for b in input: 
        ...
```
But you cannot iterate over a bytes object itself:
```python
@public 
def test(input: bytes[64]): 
    for b in input: 
        ...
```
```
StructureException: line 4:13 Cannot iterate over 'Name' object
     3 def test(input: bytes[64]):
---> 4     for b in input:
--------------------^
     5         pass
```

The solution for this would be implement the `bytes1` type, similar to #967 and #1616

**Comment by charles-cooper** [comment]
due to offline feedback, probably will deprecate this proposal in favor of https://github.com/vyperlang/vyper/issues/2527

**Comment by charles-cooper** [comment]
Not planned since #3537 implements #2527 .
