### ISSUE TITLE
VIP: Allow `bool` as an input type to built-in `convert` function

### ISSUE THREAD

**Issue by jakerockland** [vyperlang/vyper#1064]
## Simple Summary
Adding `bool` as an allowed input type to the built-in `convert` function so that one can do for example:

```python
flagSet: bool = True
flagSetInt: int128 = convert(flagSet, "int128")
```

## Abstract
Currently the built in `convert` function is specified as:

def convert(a, b) -> c:
  """
  :param a: value to convert
  :type a: either decimal, int128, uint256 or bytes32
  :param b: the destination type to convert to
  :type b: type of either decimal, int128, uint256 or bytes32

  :output c: either decimal, int128, uint256 or bytes32
  """
 
I'm proposing we re-specify it as:

def convert(a, b) -> c:
  """
  :param a: value to convert
  :type a: either bool, decimal, int128, uint256 or bytes32
  :param b: the destination type to convert to
  :type b: type of either decimal, int128, uint256 or bytes32

  :output c: either decimal, int128, uint256 or bytes32
  """

Where True <-> 1 and False <-> 0.

## Motivation
There are situations in which it would be convenient to be able to translate a boolean value into an integer or byte value to be able to pack it into an array of bytes with other data. Currently this seems to only be achievable using conditional logic, whereas the built in `convert` function supports similar behavior for other input types.

## Specification
The technical specification for this is a re-iteration of what is in "Abstract" above.  

## Backwards Compatibility
This VIP is backwards compatible.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
I think this one is probably okay to move forward with, another related one is #1074

It should basically just be possible to convert any basic (32 byte) type to any other basic type.

**Comment by jakerockland** [comment]
Awesome, I’ll start on tackling both. 😄👌

**Comment by jakerockland** [comment]
@fubuloubu quick question, when working on functionality like this, what is the best way to run a single test case that I've written, as opposed to running the entire test suite?

**Comment by fubuloubu** [comment]
`pytest -k path/to/test_case.py`
