### ISSUE TITLE
VIP: Specify basic type conversions

### ISSUE THREAD

**Issue by jakerockland** [vyperlang/vyper#1093]
## Simple Summary
A specification of expected behavior when converting between all basic Vyper types.

## Abstract
A table specifying the expected conversion behavior between basic types. Once adopted, this specification should be enforced at compile-time whenever possible and otherwise the compiler should add runtime checks to ensure that this conversion behavior is predictable.

Once we agree on a specificiation here, I can start a PR on the docs and start working on the implementation to meet the final spec. Given that is is a lot of text we may want a separate page in the docs specificying the conversion behavior that is linked to from the "Built in Functions" section in the docs.

## Motivation
In playing around with Vyper's type conversion, I've already noted various bugs and quirks in the conversion behavior. 

Per @fubuloubu and I's conversation on #1072, I think it is necessary to have a specified and agreed upon expected behavior for type conversion, which we can add to the docs and then implement accordingly.

## Specification
Add the following to the Vyper specification and documentation.

For the built-in convert function:

```python
def convert(a, b) -> c:
  """
  :param a: value to convert
  :type a: either bool, decimal, int128, uint256, bytes32, or bytes
  :param b: the destination type to convert to
  :type b: type of either bool, decimal, int128, uint256, bytes32, or bytes

  :output c: either bool, decimal, int128, uint256, bytes32, or bytes
  """
```

Referencing the following constant values:

```python
MAXNUM = 2**127 - 1
MINNUM = -2**127
MAXDECIMAL = (2**127 - 1) * 10000000000
MINDECIMAL = (-2**127) * 10000000000
MAX_UINT256 = 2**256 - 1
```

Specified conversion behavior should be:

| Output Type (b) | Input Type (a.type) | Allowed Inputs Values (a) | Additional Notes | Implemented? | Optimized? |
| :--- | :--- | :---: | :--- | :---: | :---: |
| bool | bool | N/A | Do not allow converting from/to the same type | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bool | decimal | MINDECIMAL...MAXDECIMAL | Has the effective conversion logic of: `return (a != 0.0)` | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bool | int128 | MINNUM...MAXNUM | Has the effective conversion logic of: `return (a != 0)` | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bool | uint256 | 0...MAX_UINT256 | Has the effective conversion logic of: `return (a != 0)` | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bool | bytes32 | (0x00 * 32)...(0xFF * 32) | Has the effective conversion logic of: `return (a != 0x00)` | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bool | bytes | bytes[1]...bytes[32] <br/> (0x00 * 1)...(0xFF * 32) | Has the effective conversion logic of: `return (a != 0x00)` | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bool | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of: return (a != ZERO_ADDRESS) | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| | | | | | |
| decimal | bool | True / False | Result will be 0.0 or 1.0 | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| decimal | decimal | N/A | Do not allow converting from/to the same type | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| decimal | int128 | MINNUM...MAXNUM | | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| decimal | uint256 | 0...MAXDECIMAL | | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |
| decimal | bytes32 | (0x00 * 32)...(0xFF * 32) | | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| decimal | bytes | bytes[1]...bytes[32] <br/> (0x00 * 1)...(0xFF * 32) | | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| decimal | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of first converting to `bytes[16]`, dropping the 4 most significant bytes, then converting to `decimal`<br/><br/>Output will be in range ((-2^127) * 10000000000)...((2^127 - 1) * 10000000000) | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| | | | | | |
| int128 | bool | True / False | Result will be 0 or 1 | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| int128 | decimal | MINNUM...MAXNUM | Only allow input within `int128` supported range, truncates the decimal value | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| int128 | int128 | N/A | Do not allow converting from/to the same type | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| int128 | uint256 | 0...MAXNUM | | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| int128 | bytes32 | (0x00 * 32)...(0xFF * 32) | | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |
| int128 | bytes | bytes[1]...bytes[32] <br/> (0x00 * 1)...(0xFF * 32) | | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |
| int128 | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of first converting to `bytes[16]`, dropping the 4 most significant bytes, then converting to `int128`<br/><br/>Output will be in range (-2^127)...(2^127 - 1) | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| | | | | | |
| uint256 | bool | True / False | Result will be 0 or 1 | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| uint256 | decimal | 0...MAXDECIMAL, truncates the decimal value | | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| uint256 | int128 | 0...MAXNUM | | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| uint256 | uint256 | N/A | Do not allow converting from/to the same type | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| uint256 | bytes32 | (0x00 * 32)...(0xFF * 32) | | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| uint256 | bytes | bytes[1]...bytes[32] <br/> (0x00 * 1)...(0xFF * 32) | | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |
| uint256 | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of first converting to `bytes[20]`, then converting to `uint256`<br/><br/>Output will be in range 0...(2^160 - 1) | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| | | | | | |
| bytes32 | bool | True / False | Result will be either (0x00 * 32) or (0x00 * 31 + 0x01) | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes32 | decimal | MINDECIMAL...MAXDECIMAL | Has the effective behavior of multiplying the decimal value by the decimal divisor `10000000000` and then converting that signed _integer_ value to a `bytes32` byte array. | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes32 | int128 | MINNUM...MAXNUM | | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes32 | uint256 | 0...MAX_UINT256 | | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes32 | bytes32 | N/A| Do not allow converting from/to the same type | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes32 | bytes | bytes[1]...bytes[32] <br/> (0x00 * 1)...(0xFF * 32) | Left-pad input `bytes` to size of 32 | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes32 | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of first converting to `bytes[20]`, then left-padding the remaining 12 bytes with `0x00` | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| | | | | | |
| bytes | bool | True / False | Should return `bytes` array of length 1, `0x00` or `0x01` | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes | decimal | MINDECIMAL...MAXDECIMAL | Should be minimum number of bytes required to represent equivalent `bytes32` representation (remove `0x00` left-padding) | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes | int128 | MINNUM...MAXNUM | Should be minimum number of bytes required to represent equivalent `bytes32` representation (remove `0x00` left-padding) | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes | uint256 | 0...MAX_UINT256 | Should be minimum number of bytes required to represent equivalent `bytes32` representation (remove `0x00` left-padding) | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes | bytes32 | (0x00 * 32)...(0xFF * 32) | Should be minimum number of bytes required to represent equivalent `bytes32` representation (remove `0x00` left-padding) | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes | bytes | N/A | Do not allow converting from/to the same type | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
| bytes | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Will always be a `bytes` array of length 20 | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |

## Backwards Compatibility
I believe this is fully backwards compatible. 

There are some type conversions that were previously not allowed by Vyper that this proposes, in which case tests will need to be updated.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jakerockland** [comment]
Another nice thing, once we agree on a spec here, that can be implemented with the implementation of this VIP is ensuring that the compiled op-codes for various conversions are as efficient as possible.

**Comment by fulldecent** [comment]
I love it. And yes, definitely want the tightest EVM implementations for this important function.

**Comment by jacqueswww** [comment]
@jakerockland So I was wondering about the `(remove 0x00 left-padding)` part, this is only useful if we convert from a literal right? Otherwise we do work that isn't required.

**Comment by jacqueswww** [comment]
Approved, just add WIP column so we can keep track of what's the state of each conversion :)

**Comment by jakerockland** [comment]
One thing I noticed is not currently part of this VIP is conversions to and from the address type. However, thinking about it more, I'm a bit conflicted about whether or not this should actually be part of the `convert` behavior. On one hand, I can understand treating `address` as a first-class citizen in the Vyper type world, and allowing it to be converted to-from any other basic type. I don't think this poses too much of a challenge in terms of producing weird edge case behavior, but it is hard to imagine wanting to convert an `address` to `decimal`.

Some routes to approach this would be:

1. Support converting to-from `address` to any other basic type, as all other types above.

2. `address` is a special case within the `convert()` function and it can only be converted to-from types `uint256` and `bytes32` (this is partially supported right now—the current behavior allows converting to `address` only from `bytes32` but allows converting from `address` to both `uint256` and `bytes32`.

3. We remove `address` from the `convert()` specification altogether and create a new built-in function(s) `bytes_from_address()`, `address_from_bytes()` that only allow one or two very specific conversions from `bytes` or `bytes32` to-from `address`.

My inclination is towards option (3), as one if they really wanted to do something silly could use the output of `bytes_from_address()` to then convert those bytes to `decimal` but the real important thing to support seems the bytes-to-address and address-to-bytes functionality.

Thoughts? @jacqueswww @fubuloubu @fulldecent @nrryuya @hskang9

**Comment by fubuloubu** [comment]
I like option 2 the best personally. There are some interesting non-intuitive use cases for being able to convert an address to bytes.

**Comment by jakerockland** [comment]
@fubuloubu Given that those use cases would be preserved with (3), curious if you could elaborate a bit on your preferring (2) over (3). My thought was that if `convert()` should be able to take in an input of any type in a given set of types and output any type within that set, so if `address` doesn't make sense for the set it deserves its own function.

**Comment by jakerockland** [comment]
@fubuloubu I hear you, this makes sense to me. I do think we probably know enough though at this point to include `address` fully in the spec then though if it is compelling to do conversions to-from `address` for all basic types.

What're your thoughts on the following as a starting point (if this seems good I will propose something analogous for the X-to-address direction as well)?

| Output Type (b) | Input Type (a.type) | Allowed Inputs Values (a) | Additional Notes |
| :--- | :--- | :---: | :--- |
| bool | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of: return (a != ZERO_ADDRESS) |
| uint256 | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of first converting to `bytes[20]`, then converting to `uint256`<br/><br/>Output will be in range 0...(2**160 - 1) |
| int128 | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of first converting to `bytes[20]`, then converting to `int128`<br/><br/>Output will be in range (-2**159)...(2**159 - 1) |
| decimal | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of first converting to `bytes[20]`, then converting to `decimal`<br/><br/>Output will be in range ((-2**159) * 10000000000)...((2**159 - 1) * 10000000000) |
| bytes32 | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Has the effective conversion logic of first converting to `bytes[20]`, then left-padding the remaining 12 bytes with `0x00` |
| bytes | address | ZERO_ADDRESS...0xffffffffffffffffffffffffffffffffffffffff | Will always be a `bytes` array of length 20 |

**Comment by fubuloubu** [comment]
Pretty much looks good, except the conversion to `int128`/`decimal` is lossy (make a note of that, bits 128-160 are lost) and those conversions should not go negative because there is no analogous concept of a "negative address" so it would be weird to create one (aka "bit 128 is the sign bit!" ... "but y tho?")

**Comment by jakerockland** [comment]
Hrmm, I feel like the address `0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` _should_ be equal to -1 when converted to `int128` though, no? It seems odd for the behavior to be the same when converting to `int128` as it is when converting to `uint256`. Even though there isn't a concept of "negative address" per-se, it makes sense to me to treat conversions from addresses to number types to be a twos-complement conversion of the bytes. I see the point though that there isn't a negative address space, something seems off about basically treating all conversions from `address` type to a numeric type as unsigned regardless of if the output type is signed or not. However, we do do something similar already in the spec when converting `uint256` to `int128`... So I can see that reasoning for also only treating `address` to `int128`/`decimal` as an unsigned conversion, just want to dive a bit deeper and flesh that thought out.

**Comment by fubuloubu** [comment]
So the address `0x00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` is -1 but the address `0x000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF is 2^127-1?

**Comment by jakerockland** [comment]
Hrm, I'm a big confused why `0x12345678FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` would be -1:

```
$ python
$ foo = b"\x12" + b"\x34" + b"\x56" + b"\x78" + b"\xff" * 16
$ int.from_bytes(foo, "big", signed=True)
   103929005455909232654322135874226081670765740031
```

And why `0x214728597FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` would be `2**127 - 1`:

```
$ python
$ bar = b"\x21" + b"\x47" + b"\x28" + b"\x59" + b"\x7f" + b"\xff" * 15
$ int.from_bytes(bar, "big", signed=True)
   189983563292991488376601128892698858119187398655
```

`0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` would be -1 though.

**Comment by fubuloubu** [comment]
It depends on which part of the address you are going to ignore on conversion, and what part you are going to arbitrarily use for the sign bit. It's a 160 bit quantity, so you have to ignore some part of it to convert to a 127 bit (signed) quantity (as the integer portion), and if you make it a signed integer it is also an arbitrary distinction which bit you claim is the signed bit.

It's all arbitrary 🤣, so as long as you are consistent in the arbitrariness it's fine.

**Comment by jakerockland** [comment]
@fubuloubu Ah yes sorry I see now what I was overlooking 😅. Will need to think a bit more on this in terms of what arbitrariness makes the most sense 😂

**Comment by fubuloubu** [comment]
Sounds good to me!

**Comment by jakerockland** [comment]
I've updated the above table to incorporate the discussed conversions _from_ the `address` type (haven't gone through and checked off which things are implemented and which still need to be done yet), next will be writing up specification for conversions _to_ `address` from all other types—then will verify what needs to be implemented and I'll start working on implementing both.

**Comment by jakerockland** [comment]
Before adding it to the table above (and then moving to implementing it), I wanted to see if there were any thoughts on the following:

| Output Type (b) | Input Type (a.type) | Allowed Inputs Values (a) | Additional Notes |
| :--- | :--- | :---: | :--- |
| address | bool | True / False | Result will be `ZERO_ADDRESS`, or `0x00000000000000000001` |
| address | decimal | MINDECIMAL...MAXDECIMAL | Has the effective behavior of converting the `decimal` value to `bytes32`, then trimming the 12 most significant bytes |
| address | int128 | MINNUM...MAXNUM | Has the effective behavior of converting the `int128` value to `bytes32`, then trimming the 12 most significant bytes |
| address | uint256 | 0...MAX_UINT256 | Has the effective behavior of converting the `uint256` value to `bytes32`, then trimming the 12 most significant bytes | 
| address | bytes32 | (0x00 * 32)...(0xFF * 32) | Has the effective behavior of trimming the 12 most significant bytes |
| address | bytes | bytes[1]...bytes[32] <br/> (0x00 * 1)...(0xFF * 32) | Left-pads the byte-array with `0x00` to 20 bytes if the length of the array is less than 20, trims all but the 20 least significant bits if the length is greater than 20 |
| address | address | N/A | Do not allow converting from/to the same type |

**Comment by fubuloubu** [comment]
@iamdefinitelyahuman I think this is solved with your docs updates?

**Comment by jakerockland** [comment]
Though the updates to the [Type Conversions](https://vyper.readthedocs.io/en/stable/types.html#type-conversions) section of the docs are more accurately covered now with #2081, I think there are still some feature gaps compared against the proposed spec here (notably fully supporting `address` and `bytes` conversions in both directions).

**Comment by charles-cooper** [comment]
superseded by #2507
