### ISSUE TITLE
Add type hints and expose via PEP561

### ISSUE THREAD

**Issue by pipermerriam** [vyperlang/vyper#1118]
### What's your issue about?

This codebase could probably benefit from having type hints and other codebases could benefit from having the python API types exposed via [PEP561](https://www.python.org/dev/peps/pep-0561/)

### How can it be fixed?

Mostly just semi-tedious work to get type hints added to the code but it's not too hard to do incrementally.

#### Cute Animal Picture

![cute monkeys 81](https://user-images.githubusercontent.com/824194/49468585-86146600-f7c2-11e8-9b08-9099ffbba7a1.jpg)

**Comment by fubuloubu** [comment]
@jacqueswww good first issue?

**Comment by pipermerriam** [comment]
@fubuloubu it can be but I'd recommend someone who's familiar with the codebase take a few minutes to identify the logical order that hints should be added (ideally starting at the most isolated code and working outwards).

**Comment by jacqueswww** [comment]
I would actually like to tackle this :) have only basic knowledge of mypy.
