### ISSUE TITLE
`Invalid type` and `Number out of range`

### ISSUE THREAD

**Issue by nrryuya** [vyperlang/vyper#1122]
### Version Information

* vyper Version: [the latest](https://github.com/ethereum/vyper/commit/97ed5fec89947d41fd91f5190c4478ffcadbb9fb) and 0.1.0b4

### What's your issue about?

I got `Number out of range` in compiling this.
```
a: int128 = - 2**127 - 1
```

Instead, I got `Invalid type, expected: int128` error in compiling this.
```
a: int128 = 2**127
```

I think they both should say `Number out of range`, which is more helpful?

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/22876645/49567102-1e9c1900-f970-11e8-8739-4612220f8e69.png)

**Comment by fubuloubu** [comment]
Just checked, still an issue

**Comment by iamdefinitelyahuman** [comment]
This is fixed from #2029
