### ISSUE TITLE
SyntaxError on struct definition

### ISSUE THREAD

**Issue by alexeiZamyatin** [vyperlang/vyper#1129]
### Version Information

* vyper Version: 0.1.0b5, 0.1.0b4, 0.1.0b3, 0.1.0b2

### What's your issue about?
`SyntaxError` thrown on  `struct` definition.

```
struct MyStruct:
    value1: int128
    value2: decimal
```
results in: 
``` 
    struct MyStruct:
                  ^
SyntaxError: invalid syntax

```

This example is taken directly from the documentation: https://vyper.readthedocs.io/en/latest/types.html#structs 

Tried downgrading versions up until b2, but no effect. 

Same issue with https://vyper.online/  ("Voting" example)

**Comment by jacqueswww** [comment]
Not a problem, will build th docs ;)

**Comment by jacqueswww** [comment]
@alexeiZamyatin please try the beta-5 docs, I will keep docs set to the latest version (instead of master / latest) at all times from now on.
