### ISSUE TITLE
VIP: Add keyword for immutable state variables

### ISSUE THREAD

**Issue by buckle2000** [vyperlang/vyper#1164]
## Simple Summary
Add a keyword for state variables of a contract that ensures immutability

## Abstract & Motivation

Data marked with this keyword **must** be set in `__init__`

This keyword will make code more readable, thus making it more secure.

The keyword might be
- final
- immutable
- frozen
- ... or whatever

## Specification

If the keyword is `final`, then it can be used like this:

```vyper
# Auction params
# Beneficiary receives money from the highest bidder
beneficiary: public(final(address))
auctionStart: final(public(timestamp))
auctionEnd: public(final(timestamp))
```

Immutability is checked **only in compile time**

## Backwards Compatibility
None

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
Just a note: Marking something as final means it can only be set in `__init__` which also means we need to warn that a variables is set to default/zero if not assigned in `__init__`.

**Comment by fubuloubu** [comment]
Should the compiler throw an Error if it's not set in `__init__` I would argue that's unintended behavior and they should either set it or make it a constant

**Comment by jacqueswww** [comment]
Yes, this would definitely have to be an error as it violates `final`.

**Comment by jacqueswww** [comment]
Approved :+1:

**Comment by charles-cooper** [comment]
for gas savings, we can skip SLOADing immutable variables. in the constructor, we can set the values of the immutable variables in a data section of the runtime code and then at runtime use CODECOPY to load the values.

**Comment by spinoch** [comment]
I would have expected this functionality to be implemented as part of `constant`, that feels more intuitive imo

**Comment by fubuloubu** [comment]
> I would have expected this functionality to be implemented as part of `constant`, that feels more intuitive imo

A constant gets injected directly into the bytecode during compilation. The suggestion here would be a state variable that can only be set once (during `__init__`, or potentially during an `initialize` method w.r.t. `create_forwarder_to`-style proxies).

It would still be a storage variable. Dynamically assembling the bytecode during deployments is a really difficult exercise, but could be done as an optimization to further reduce code size/gas cost.

**Comment by spinoch** [comment]
Right. Thanks for the low-level hints.

> It would still be a storage variable. Dynamically assembling the bytecode during deployments is a really difficult exercise, but could be done as an optimization to further reduce code size/gas cost.

I was thinking that one could have some sort of templating similar to say `docker-compose` or shell scripts where the contracts would get information from an environment variables kind of setup e.g. the code would look like
```
BENEFICIARY: public(constant(address)) = $BENEFICIARY
```
and at compile time the value of `$BENEFICIARY` is read from the environment and replaces the variable name.

This way, it is still a constant at compile time and we have the gas optimizations as well as relatively clean code.
Of course, this would imply having some kind of wrapper at compile time which replaces the placeholder constants for the desired values. One can easily do this using shell tools, but I'm unsure if the cost of maintenance and complexity are worth it

**Comment by fubuloubu** [comment]
> at compile time the value of `$BENEFICIARY` is read from the environment and replaces the variable name.

I had a similar idea too, I think it would be useful but IMO that's a new VIP.

In general, I want to support using Vyper as a templating tool too. For example, in `yearn-vaults` we have a field that's generated based on the git tag, but that requires a lot of management to use correctly. if it instead looked like:

```python
VERSION = public(constant(String[20])) = {{ $VERSION }}
BENEFICIARY: public(constant(address)) = {{ $BENEFICIARY }}
```
 that would be pretty cool

**Comment by charles-cooper** [comment]
> It would still be a storage variable. Dynamically assembling the bytecode during deployments is a really difficult exercise, but could be done as an optimization to further reduce code size/gas cost.

note for those searching for implementation details: in the current implementation (v0.3.3), immutables are appended to the runtime code during deployment, there is no storage overhead.
