### ISSUE TITLE
Improvements to the forwarder template of `create_with_code_of()`

### ISSUE THREAD

**Issue by GNSPS** [vyperlang/vyper#1176]
### Version Information

* vyper Version: latest

### What's your issue about?

The byte code template for the forwarder in `create_with_code_of()` is both longer than it needs to be and doesn't support returning data with the return data location from the proxied contracts.

### How can it be fixed?

An example of a template that I have built some time ago and has support for the return data location is:
https://gist.github.com/GNSPS/ba7b88565c947cfd781d44cf469c2ddb

It has been tested in production as you can see in the comments. Main improvements are the clear use of the `RETURNDATACOPY` opcode and usage of `DUP<X>` instead of pushing a lot of 0x00s.

#### Cute Animal Picture

![](https://secure.img2-ag.wfcdn.com/im/51042015/resize-h310-w310%5Ecompr-r85/4307/43074606/sitting-sleepy-bulldog-puppy-statue.jpg)

**Comment by jacqueswww** [comment]
Left as undecided for now, to be compared to: https://github.com/ethereum/vyper/blob/master/vyper/functions/functions.py#L636

**Comment by fubuloubu** [comment]
Unnecessary as of #2281
