### ISSUE TITLE
Write example of calling external contracts

### ISSUE THREAD

**Issue by jacqueswww** [vyperlang/vyper#1182]
We need a nice example of calling external contracts in the documentation, structure-of-a-contract.rst is probably a good place to put it.

The tests outline a few examples: https://github.com/ethereum/vyper/blob/master/tests/parser/features/external_contracts/test_external_contract_calls.py
https://github.com/ethereum/vyper/blob/master/tests/parser/features/external_contracts/test_modifiable_external_contract_calls.py

At the same time add a section on using the built-in ERC20 interface or just a link to:
https://github.com/ethereum/vyper/blob/master/examples/market_maker/on_chain_market_maker.vy#L10

**Comment by iamdefinitelyahuman** [comment]
Implemented..  somewhere.  #2081 if not sooner.
