### ISSUE TITLE
Reimplement `shift` using constantinople opcodes

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#1268]
With the inclusion of [EIP 145](https://eips.ethereum.org/EIPS/eip-145) in constantinople we can reimplement `shift` using `SHL`/`SHR`.

**Comment by jacqueswww** [comment]
This is a good idea! :)

**Comment by fubuloubu** [comment]
Would be a great way to test #1230

**Comment by charles-cooper** [comment]
Also I think we should add `shl` and `shr` functions (or `shiftl`/`shiftr`). I don't know what `shift` does without checking the documentation, but `shl` and `shr` are pretty obvious.

**Comment by fubuloubu** [comment]
@charles-cooper sometimes languages provide `shift(word, bits)` where `word` would be a `uint256` integer and `bits` would be a `int128` in our case. `bits` would have to be within the range [-255, 255] to be considered valid. The negative sign would be a right shift, and non-negative would mean a left shift.

LISP (of which LLL is loosely based on) does this: http://clhs.lisp.se/Body/f_ash.htm

**Comment by fubuloubu** [comment]
EIP 145 brings [three different opcodes](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md)  for shifting to the forefront, so we might want to build a higher-level API that provides the right opcodes on the situation (particularly `SHR` and `SAR` depending on the signed-ness of the first operand)

**Comment by charles-cooper** [comment]
I think choosing an opcode for the user based on the type is too magical and can lead to difficult to debug situations where they accidentally feed `uint128` to shift and get SAR when they meant to convert first and get SHR. The type system should help prevent subtle errors, not propagate them! (So vyper's SAR should only accept signed integers and SHR should only accept unsigned). At least, we should expose them to the user and then the user has a choice between the high level usage (shift) and lower level functions which have a one to one correspondence to opcodes.

**Comment by fubuloubu** [comment]
Sounds like a great compromise!

**Comment by fubuloubu** [comment]
Constantinople is in!

**Comment by jacqueswww** [comment]
Meeting notes: 
- We have to investigate the 3 opcodes 
- If we change the semantics we need a VIP

**Comment by iamdefinitelyahuman** [comment]
Note to self, should look at this after #1783
