### ISSUE TITLE
Consider weekly stand-up style meetings for Vyper

### ISSUE THREAD

**Issue by davesque** [vyperlang/vyper#1274]
This is just a thought but weekly stand-ups have worked well for the snake charmers team.  What I'm thinking is that Vyper could have weekly stand-ups at a set time *instead* of the bi-weekly meetings.  The problems I see with the current meeting format are:

* The meetings often get re-scheduled or the schedule is shifted back by a week.  This leads to attendees forgetting to adjust their calendars and getting out of sync with the schedule.
* Meetings often last an hour or longer.  There may be a lot of things to discuss but much of the discussion could take place between individuals or in github comment threads.
* If anyone misses a meeting, it's quite a while until there's another opportunity to meet.

Stand-up style meetings seem better because:

* They're more frequent so people are encouraged more to make a place in their schedules for them.
* They're shorter and don't impose as much on the participants.
* It's not as big a deal if someone misses one because there's less time until the next one and it's less likely they missed out on any important exchange of information.

**Comment by davesque** [comment]
I'll admit that one reason stand-ups might not be appropriate is that I believe the bi-weekly's are also used as a way to get input from community members.

**Comment by jacqueswww** [comment]
I would actually vote for no meetings, as it's clear because of time zones that there is never a perfect time. All of the items could be solved on issues directly if we aggregated the discussions into meta tickets on a fixed basis (which is what meetings have become). Just my 2 wei.

**Comment by charles-cooper** [comment]
I think meetings are useful in that input can be provided and consensus quickly achieved on things which might be long, convoluted or unclear in writing. Weekly seems like overkill though, especially because of the time zone issue; somewhere between every 2-4 weeks seems like enough to discuss everything. Re. missing out on important exchanges, it could easily be solved by keeping minutes.

It would be also be helpful if the meeting times were announced further in advance! A mailing list or similar tool could help keep everyone's schedule in sync. A low-tech way to do this would be to create a single meta-issue for meeting times which people can subscribe to.

**Comment by davesque** [comment]
@charles-cooper Re: minutes & meeting time announcements

I feel like having those two things already increases the burden of attending/organizing meetings significantly.  Keeping minutes seems to imply that meetings will last long than 10 or 15 minutes.  I already think that's too long.  Also, announcing the time for every meeting seems more complicated than just agreeing to a specific schedule and sticking to it.

There are rarely issues with the snake charmers meetings because they're always at the same time and they're always short.  There's never any confusion about when a meeting will be.  It's also easy to attend them since you know they won't last long.  You can even be in the middle of coding something and attending a stand-up is not that disruptive to your thought process.

**Comment by charles-cooper** [comment]
@davesque fair points! I guess I could be bought either way so long as the meeting times work across time zones, and are clear and in advance.

**Comment by fubuloubu** [comment]
@davesque keep in mind the Snake Charmers is mostly the EF team, and we have a lot of different contributors from different timezones, companies, affiliations, and availabilities. I like the current 2-week schedule, but we should be a little better to sticking to it to make sure our contributors know where to go and when the meeting is to discuss things deeper when necessary.

**Comment by davesque** [comment]
@fubuloubu Fair points although I did acknowledge that a little further back in the thread.

**Comment by jacqueswww** [comment]
@davesque @fubuloubu @charles-cooper I think part of the problems David is experiencing is that the meeting agenda isn't put up early enough, I will strive to have this in the issue list at least 3-4days before. Also I will ensure that even if I am on holiday the meeting will by held by @fubuloubu, unless we both are on holiday - then we will just skip it (this happened over the festive season). This will ensure agendas are up in time. The meeting time is actually pretty consistent, every two weeks 15:00UTC. 

Additionally the next meeting ticket will be created on each call, so everyone has ample notice of the time before.

**Comment by fubuloubu** [comment]
Perfect! I think this is the right solution to some of the problems @davesque is mentioning.
