### ISSUE TITLE
Pass *args and **kwargs in function declaration

### ISSUE THREAD

**Issue by NikitaMishin** [vyperlang/vyper#1359]
### Version Information

* vyper Version (output of `vyper --version`): v0.1.0-beta.9
* OS: linux
* Python Version (output of `python --version`): Python 3.6.7
* Environment (output of `pip freeze`): pycryptodome==3.7.3
                                                            vyper==0.1.0b9

### What's your issue about?

Is  this  a bug? 
I can compile contract with *args and **kwargs:
@public
def test1(a:uint256, *args,**kwargs) ->bool:
     return True

And if i try to get args, for example, i''ll get following error "Undeclared variable: args"
### How can it be fixed?
Check for * and ** in fun declaration

**Comment by davesque** [comment]
@jacqueswww Maybe this highlights the case for a custom grammar.  That kind of thing really should be a syntax error.

**Comment by jacqueswww** [comment]
@davesque yup.
