### ISSUE TITLE
Optimizer: JUMPI when the condition is statically known

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#1385]
One of the branches can be pruned. This happens a lot e.g. in `assert 0 <reason>`. Sub-issue of https://github.com/ethereum/vyper/issues/1380

**Comment by jacqueswww** [comment]
I think dead code lead to security errors, so we should perhaps error or throw a warning on these?

**Comment by fubuloubu** [comment]
Warning. Sometimes dead code is hard to remove, but we should encourage developers to remove them if possible.

**Comment by charles-cooper** [comment]
> I think dead code could lead to security errors (in terms of readability / assuming some code has run when it hasn't), so we should perhaps error or throw a warning on these?

Then we will basically have to stop using the LLL `assert` macro.

**Comment by charles-cooper** [comment]
resolved in https://github.com/vyperlang/vyper/pull/2647
