### ISSUE TITLE
selfdestruct should have the same type as return

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#1390]
Cf. conversation in https://github.com/ethereum/vyper/pull/1384#discussion_r272781923

From the yellow paper,
![Screenshot from 2019-04-08 09-42-17](https://user-images.githubusercontent.com/3867501/55741696-bb37fb80-59e2-11e9-8b40-37848ead2778.png)

`SELFDESTRUCT` cannot be distinguished by the caller from `RETURN(0, 0)` (or `STOP`). At the vyper level this is equivalent to the empty return statement `return`. So, this should be valid
```
@public
def foo() : 
  selfdestruct(msg.sender)
```
But not this
```
@public
def bar() -> int128 : 
  selfdestruct(msg.sender)
```
(unless I am misunderstanding the EVM semantics here, the latter will result in the caller having junk in the buffer they provide to `CALL`).

**Comment by fubuloubu** [comment]
I like it. Do the return statement check assuming `selfdestruct` is a endpoint. Slightly different from `assert` in that we allow this:
```python
@public
def bar(x: int128) -> int128 : 
  assert x == 1  # Execution stops if x != 1
  return x  # Thus, this is reachable
```
but this should fail:
```python
@public
def bar(x: int128) -> int128 : 
  selfdestruct(msg.sender)  # Execution ALWAYS stops here
  return x  # Thus, this is unreachable
```

**Comment by charles-cooper** [comment]
> but this should fail:
> 
> ```python
> @public
> def bar(x: int128) -> int128 : 
>   selfdestruct(msg.sender)  # Execution ALWAYS stops here
>   return x  # Thus, this is unreachable
> ```

I think that is already checked for in https://github.com/ethereum/vyper/pull/1384

**Comment by jacqueswww** [comment]
> > but this should fail:
> > ```python
> > @public
> > def bar(x: int128) -> int128 : 
> >   selfdestruct(msg.sender)  # Execution ALWAYS stops here
> >   return x  # Thus, this is unreachable
> > ```
> 
> I think that is already checked for in #1384

Yes this now handled.

**Comment by charles-cooper** [comment]
done in #1384
