### ISSUE TITLE
timespan variables cannot be assigned from another variable

### ISSUE THREAD

**Issue by akinama3** [vyperlang/vyper#1398]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b9
* OS: osx
* Python Version (output of `python --version`): Python 3.7.3
* Environment (output of `pip freeze`):
atomicwrites==1.3.0
attrs==19.1.0
autopep8==1.4.3
decorator==4.4.0
entrypoints==0.3
flake8==3.7.7
graphviz==0.10.1
mccabe==0.6.1
more-itertools==7.0.0
mypy==0.670
mypy-extensions==0.4.1
networkx==2.2
pluggy==0.9.0
py==1.8.0
pycodestyle==2.5.0
pycryptodome==3.8.1
pyflakes==2.1.1
pytest==4.3.1
PyYAML==5.1
result==0.3.0
six==1.12.0
typed-ast==1.3.1
typing==3.6.6
vyper==0.1.0b9

### What's your issue about?

I tried to compile the following code by truffle with Vyper.

```
@public
def process(_argument: timedelta):
    delta: timedelta = _argument
    ...
```

but it produced the following error message.

```
TypeError: '<=' not supported between instances of 'int' and 'str'
```

Is this behavior expected?

**Comment by fubuloubu** [comment]
No, that appears to be a miscaught python exception

**Comment by akinama** [comment]
thanks!
I will challenge to fix it.

**Comment by fubuloubu** [comment]
Thank you @akinama for volunteering as tribute

**Comment by akinama** [comment]
Sorry, I have realized that only a constant of "timedelta" definition causes the above error.

**Comment by akinama** [comment]
```
TIMESPAN: constant(timedelta) = 1234
```

**Comment by iamdefinitelyahuman** [comment]
No longer relevant, as we've removed units.
