### ISSUE TITLE
Explore Fuzzer-Based Test Cases

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1402]
Refactor certain parts of the test case suite into more general [fuzzer-based](https://www.owasp.org/index.php/Fuzzing) test cases (using [Hypothesis](https://hypothesis.works/) or other lib)

Examples of valuable uses:
- "Bad code"/"Good code" compile checks
  - no assertions about the code, only that it compiles
  - example [here](https://github.com/ethereum/vyper/blob/1cd54f7530544d661b76d12f76de5a643254b99e/tests/parser/syntax/test_custom_units.py#L14)
- Validate type clamps at ABI level
  - bypasses eth-abi/web3py
  - maybe symbolic analysis is better?

It's important to note that fuzzing must be applied intelligently to scenarios where a strategy can be constructed simply without re-implementing the functionality under test. For example, `hypothesis` has a [plugin](https://hypothesis.readthedocs.io/en/latest/extras.html#hypothesis-lark) for the `lark` parser that can generate different sequences of tokens, which may be useful.

**Comment by charles-cooper** [comment]
closing as we have a bunch of fuzz test cases now. we should also explore symbolic execution tests, but that's for another issue.
