### ISSUE TITLE
Update Vyper Semantics for K

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1403]
Update [Vyper Semantics for K](https://github.com/kframework/vyper-semantics) for the latest grammar and language features present in Vyper.

In progress work:
- https://github.com/LayerXcom/verified-vyper-contracts

Also, explore features that allow programmatic verification of source code against the K framework, compared to the EVM semantics of the compiled bytecode.

**Comment by charles-cooper** [comment]
@fubuloubu is this still planned?
