### ISSUE TITLE
VIP: Add abi.decode

### ISSUE THREAD

**Issue by karlfloersch** [vyperlang/vyper#1406]
## Simple Summary
Add `abi.decode` to Vyper similar to what is implemented in https://github.com/ethereum/solidity/pull/4390

## Abstract
Encoding is hard! It seems that abi encoding is a solid encoding format--likely better than RLP. SSZ encoding is being used in Eth2.0 and apparently it is quite similar to ABI encoding which is a good signal. Would be great to have Vyper support.

## Motivation
There are a number of teams (including Plasma Group) which need ABI encoding and this is actually a huge blocker with implementing our smart contracts in Vyper.

## Specification
See the Python implementation here: https://github.com/ethereum/eth-abi
See the Solidity PR here: https://github.com/ethereum/solidity/pull/4390
There are some docs here: https://solidity.readthedocs.io/en/v0.5.3/abi-spec.htm

## Backwards Compatibility
This is a new feature.

## Dependencies
Not that I am aware of.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by charles-cooper** [comment]
@karlfloersch I'm curious what the use case is for using `abi.decode` rather than just passing in data as arguments to functions? (Note that ABI encode/decode is already the standard for how function arguments are decoded from tx data).

**Comment by fubuloubu** [comment]
@charles-cooper many token extensions (as well as other methodologies) allow passing unstructured data through as an argument to a destination call address for further parsing. For example, ERC-777 `function send(address to, uint256 amount, bytes calldata data)`. This allows unstructured data to by parsed by smart contracts on the receive side of a transfer, and `abi.decode` allows them to interpret that data in a specific way on the receive side e.g. a transaction struct or something like that.

**Comment by charles-cooper** [comment]
@fubuloubu gotcha. I think the trickiest part about this spec is for the typechecker to dynamically deduce a type. But I suppose it could just have the same signature as `RLPList`, `bytes -> *`.

**Comment by fubuloubu** [comment]
@charles-cooper oh no, it's super easy! You can give it a type!

```python
from vyper import abi

struct Foo:
    a: address
    b: bytes32
    c: uint256

def foo(unstructured_data: bytes[84]) -> Foo:
    return abi.decode(unstructured_data, (Foo))
```

**Comment by fubuloubu** [comment]
In general, `abi.decode(bytes[N], (typ1, typ2, ...)) -> (typ1, type, ...)` where `N` has to be long enough to encode `typ1, type, ...`

**Comment by fubuloubu** [comment]
`abi.encode(typ1, typ2, ...) -> bytes[N]` is even easier, we can derive the types of the inputs

**Comment by fubuloubu** [comment]
Maybe an an alternative might be to leverage kwargs for `abi.decode` a la `abi.decode(bytes, encoding=(typ1, typ2, ...))`, but I'm on the fence about that

**Comment by charles-cooper** [comment]
I think you can even avoid using `abi.decode(TYPE, bytes_)` and go with `abi.decode(bytes_)` because in general the LHS is already known.

**Comment by fubuloubu** [comment]
Oh yeah! Duh!

I remember talking about this before... many issues ago...

**Comment by jacqueswww** [comment]
> @fubuloubu gotcha. I think the trickiest part about this spec is for the typechecker to dynamically deduce a type. But I suppose it could just have the same signature as `RLPList`, `bytes -> *`.

+1 for using RLPList style notation.

**Comment by skellet0r** [comment]
@fubuloubu I'm definitely in over my head here, but I'll take this issue :)

**Comment by fubuloubu** [comment]
@skellet0r this may not be as much work as you'd think, the idea we had was to leverage our internal ABI decoder and make it available as a feature. That might probe difficult in and of itself, but you dont have to implement everything ftom scratch!

**Comment by skellet0r** [comment]
lol SWEEET thxs @fubuloubu
Definitely not in over my head now

**Comment by fubuloubu** [comment]
> lol SWEEET thxs @fubuloubu
> Definitely not in over my head now

haha, yes!

To explain a little further, the thinking was that this would be how it would work:

```python
from ethereum.abi import decode as abi_decode  # Just to namespace this method
# data: Bytes[96]
a, _, b = abi_decode("uint256,uint256,uint256", data)
# Maybe also use it like `abi.decode(...)`
```

**Comment by skellet0r** [comment]
Yeah I definitely like that syntax more with the kwarg usage
```python
abi.decode(data, types=[uint256, uint256, address, ...])
```

Question though, if we derive from the LHS, would that mean the following syntax is supported:

```python
a: uint256, b: uint256 ... = abi.decode(data)
```

Or would we still require zero initializing variables with their specified type before the decode usage? (I would prefer this since it's explicit)

```python
a: uint256 = 0
...
a, b, c = abi.decode(data)
```

**Comment by fubuloubu** [comment]
> Question though, if we derive from the LHS, would that mean the following syntax is supported:

Python doesn't support this now, but I could see adding this in the future with a custom parser

> Or would we still require zero initializing variables with their specified type before the decode usage? (I would prefer this since it's explicit)

We'd have to do this for now though

**Comment by iamdefinitelyahuman** [comment]
I'm not a fan of deriving the output type(s) by looking at the LHS, as it creates a situation where the outcome of an expression is dependent upon how it is observed.  This feels backward to me.

**Comment by fubuloubu** [comment]
> Yeah I definitely like that syntax more with the kwarg usage
> 
> ```python
> abi.decode(data, types=[uint256, uint256, address, ...])
> ```

Yeah I'd say start with this approach

**Comment by fubuloubu** [comment]
Resolved in #2401

**Comment by adapt7** [comment]
@charles-cooper is it something you could help with? Do you know if that's in progress? or there are any workarounds to decode abi with current vyper version?

**Comment by charles-cooper** [comment]
@adapt7 I had put this on the back burner since mostly people were asking for `abi.encode` (which is now implemented).

I can add this, but note that you can also decode bytestrings "by hand" using `convert` and `slice`. For instance, if you wanted to decode `b: Bytes[32]` which encodes `(uint256)`, you could use `convert(slice(b, 0, 32), uint256)`. Decoding bytestrings would be more complicated. If you get in touch on our discord I can walk you through your specific case.

**Comment by cih997** [comment]
@charles-cooper many thanks. Will that also work for decoding addresses? Let's say I generate `abi.encode(address, address)`. To decode it will that be as simple as `convert(slice(b, 0, 32), address)` and `convert(slice(b, 32, 64), address)`?

**Comment by adapt7** [comment]
@charles-cooper many thanks. Will that also work for decoding addresses? Let's say I generate abi.encode(address, address). To decode it will that be as simple as convert(slice(b, 0, 32), address) and convert(slice(b, 32, 64), address)?

**Comment by charles-cooper** [comment]
@adapt7 Yes!

**Comment by charles-cooper** [comment]
closed in https://github.com/vyperlang/vyper/pull/2882
