### ISSUE TITLE
Documentation for compiler API

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1411]
It would be nice to have more documentation (and doctests) for the compiler API. This is endpoint that will support other tools, so it should really clear how to interact with it and what the options are. Also, if we allow deeper integration into the compilation stages, this will be really important to document what each stage takes as input and output.

**Comment by jacqueswww** [comment]
Good idea, I would just make this a "Integrating Vyper" section.

**Comment by iamdefinitelyahuman** [comment]
We have https://github.com/vyperlang/vyper/tree/master/vyper/compiler and the docstrings for `compile_code` and `compile_codes` are fairly extensive.  Should we still consider a section in the actual documentation, or can we consider this good enough?

**Comment by charles-cooper** [comment]
Seems done. Can always reopen or open new issues if there are specific things that need to be documented
