### ISSUE TITLE
Error: not recognized as an internal or external command,

### ISSUE THREAD

**Issue by catafest** [vyperlang/vyper#1413]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b9
* OS: windows 8.1
* Python Version (output of `python --version`): 3.7.3
* Environment (output of `pip freeze`): 
C:\Python373\Scripts>pip install vyper
Requirement already satisfied: vyper in c:\python373\lib\site-packages (0.1.0b9)

Requirement already satisfied: pycryptodome<4,>=3.5.1 in c:\python373\lib\site-p
ackages (from vyper) (3.8.1)

### What's your issue about?
vyper not run

Please include information like:
C:\Python373\Scripts>vyper yourFileName.vy
'vyper' is not recognized as an internal or external command,
operable program or batch file.

C:\Python373\Scripts>dir vy*
 Volume in drive C has no label.
 Volume Serial Number is E662-A6CD

 Directory of C:\Python373\Scripts

05/03/2019  11:16 PM             4,922 vyper
05/03/2019  11:16 PM             1,495 vyper-lll
05/03/2019  11:16 PM             3,666 vyper-serve
               3 File(s)         10,083 bytes
               0 Dir(s)  333,984,301,056 bytes free

C:\Python373\Scripts>vyper-lll
'vyper-lll' is not recognized as an internal or external command,
operable program or batch file.

C:\Python373\Scripts>vyper-serve
'vyper-serve' is not recognized as an internal or external command,
operable program or batch file.

* full output of the error you received
* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

### How can it be fixed?
Fill this in if you know how to fix it.

**Comment by jacqueswww** [comment]
@catefest https://github.com/ethereum/vyper/issues/1128 give a solution for this I believe by creating a `vyper.cmd` file. This should be fixed if we use python invocation: PR #1337

**Comment by iamdefinitelyahuman** [comment]
This was likely addressed when we moved to setuptools `entry-points` system.
