### ISSUE TITLE
Is vyper-run not supported?

### ISSUE THREAD

**Issue by NikitaMishin** [vyperlang/vyper#1417]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b9
* OS: linux
* Python Version (output of `python --version`): Python 3.6.8
* Environment (output of `pip freeze`): pycryptodome==3.7.3
vyper==0.1.0b9

### What's your issue about?

Is command vyper-run not supported? Trying from docker container and own environment gives  vyper-run: command not found. (Or am i miss something?)
### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by jacqueswww** [comment]
`vyper-run` is supported if you install vyper-debug using `pip install vyper-debug` . The documentation should be updated.

**Comment by NikitaMishin** [comment]
Thanks, already find out https://github.com/ethereum/vyper/commit/09e25eb9f2f68b74c5e847f5229c643fbe453d05#diff-c1111bd512b29e821b120b86446026b8 ) 
I think it should be mentioned in documentation

**Comment by NikitaMishin** [comment]
so, maybe docker container should be updated (because right know  it doesn't vyper-debug)? May be seen as little enhancement, i believe

**Comment by jacqueswww** [comment]
Yes, I agree - that's a good idea :)

**Comment by NikitaMishin** [comment]
python setup.py test --addopts "--version" && \
    pip install vyper-debug && \
    apt-get purge -y --auto-remove apt-utils gcc libc6-dev libc-dev libssl-dev

adding pip install "pip install vyper-debug && \"between those two line seems correctly install vyper-debug

**Comment by charles-cooper** [comment]
closing as vyper-run / vyper-debug are no longer maintained
