### ISSUE TITLE
Struct constants do not parse correctly

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1430]
### Version Information
* vyper Version (output of `vyper --version`): 0.1.0b9
* OS: linux
* Python Version (output of `python --version`): Python 3.6.6
* Environment (output of `pip freeze`):
```
flake8==3.5.0
mccabe==0.6.1
pycodestyle==2.3.1
pycryptodome==3.6.6
pyflakes==1.6.0
```

### What's your issue about?

It seems like the struct literal processing works differently for constants versus memory variables:
```python
struct Foo:
    a: uint256
    b: uint256

# raises vyper.exceptions.TypeMismatchException:
#   Invalid value for constant type, expected struct Foo: {a: uint256, b: uint256}
#                                    got struct Foo: {a: int128, b: int128} instead
CONST_BAR: constant(Foo) = Foo({a: 1, b: 2})

@public
def baz():
    bar: Foo = Foo({a: 1, b: 2})  # Works fine!
```

### How can it be fixed?
Not sure, this seems weird, but these should work in a similar way IMO.

**Comment by balajipachai** [comment]
I did the following changes to the existing code, and I was able to get rid of the TypeMismatchException error:
```
struct Foo:
    a: uint256
    b: uint256

c: constant(uint256) = 1
d: constant(uint256) = 2

CONST_BAR: constant(Foo) = Foo({a: c, b: d})

@public
def baz():
    bar: Foo = Foo({a: 1, b: 2})  # Works fine!

```

The reason why we need to cast 1 & 2 to uint256:
[By default integer literals are interpreted as int128](https://vyper.readthedocs.io/en/v0.1.0-beta.7/types.html?highlight=constant#id4)
However, the above statement holds true in case of constants, otherwise, it works fine for non-constant types, consider, `def baz()`.

Things that I tried out:
Whenever you declare a constant, the flow in the code is as follows:
`From constants.py -> Expr.parse_value_expr() gets invoked which in turn invokes parser_utils.py's unwrap_loaction().`

> Here, I observed that the **orig** function argument's location is none and **orig.typ** is int128, thus this function directly returns an int128 (my understanding may be wrong, anybody do correct me in such a case)

> Also, there, are 2 types `annotation_type & expr type`, the point worth noting is that `annotation_type` gets the exact values such as uint256 whereas expr gets int128 values

Thus, I feel, when we use `constant` and if there is integer involved (in structure type) whose type is other than **int128** then:
```

- Either we type cast it to constant(desired data type) 
   OR
- There has to be a mechanism in either constants.py OR expr.py OR parser_utils.py to do this

```

P.S. Being a newbie to Python and Vyper my understanding may be incorrect, above were the findings that I got mostly by logging the values onto the console.

I am keen to add this functionality (if at all it is needed), I just need pointers in the right direction.

**Comment by charles-cooper** [comment]
@balajipachai nice finds! I think you are on the right path. If you search for the error message in the code you should find https://github.com/ethereum/vyper/blob/da88d6d18aa92a0e838ae4f3544802382e8c16ae/vyper/parser/constants.py#L76. I think if you can add generic cases for tuples/structs to the `unroll_constant` function you should be able to resolve this issue.

At the same time, it would be ideal to reify this with other type-checking code which handles literals, but it might add significant scope.

**Comment by balajipachai** [comment]
@charles-cooper Thank you, for the inputs, I'll look into it.

**Comment by fubuloubu** [comment]
Sounds like the resolution here would include making sure all valid memory data types (such as structs, but not including maps) can have associated constants that parse correctly.

@balajipachai your additional example of other constants used within a constant struct is more interesting.

**Comment by balajipachai** [comment]
I noticed that:
```
 expr.typ is struct Foo: {a: int128, b: int128} 
 whereas 
 annotation_type is struct Foo: {a: uint256, b: uint256} 
```
I was thinking about:

- Check if annotation_type is of the type struct
- Check if annotation_type contains a data member, of type int
- If Yes
    `Check the type of int (can be uint256, int128 etc)`
    `Check if expr.typ's int data member is of the same type of that of the annotation_type`
    `if expr.typ's int data member is not of the same type, then type cast into annotation_type's int data member` 
- If No
    `There shouldn't be any problem`
**annotation_type**
`Annotation type:  struct Foo: {a: uint256, b: uint256}`
**expr.typ**
`expr.typ struct Foo: {a: int128, b: int128}`

**Unknowns**
How to access struct's data members in constants.py file? (unknown being a newbie)
What is:

- `unroll_constant: const  <_ast.AnnAssign object at 0x7fbfa5951f60>`
- `unroll_constant: expr  [multi, 1, 2]`
- `const.annotation.args[0] <_ast.Name object at 0x7fbfa5946320>`

Getting to know the unknows will help in coming up with a better solution.

**Comment by charles-cooper** [comment]
@balajipachai for some examples of accessing struct member types, check out vyper/parser/parser_utils.py. Basically what you can do is check if typ is `TupleLike`, and then iterate over `typ.members`, and for each element of `typ.members`, do the same check as https://github.com/ethereum/vyper/blob/da88d6d18aa92a0e838ae4f3544802382e8c16ae/vyper/parser/constants.py#L57-L72. I recommend factoring out that block into a separate function to avoid repeating code. Thanks for working on this!

**Comment by charles-cooper** [comment]
It also occurred to me that list constants might not typecheck as well. So you could check if the constant is of `ListType` and if so, perform the same check as above on `typ.subtype`.

**Comment by charles-cooper** [comment]
Note for future maintainers. Currently similar typechecks are spread across `parser.stmt:_check_valid_assign`, `parser.parser_utils:make_setter` and the function in this issue, `parser.constants:unroll_constant`. It would be nice to factor that into a common function in `types/types.py` or `types/typechecker.py`.

**Comment by balajipachai** [comment]
@charles-cooper @fubuloubu Could you please go through #1438 and let me know the changes that need to be done for the the SizeLimits.in_bound() function to accept arg2 in a generic manner?

**Comment by fubuloubu** [comment]
Still an issue, #1438 may fix, just need someone to pull in @balajipachai's work and fix the linter errors
