### ISSUE TITLE
Dynamic jump destinations

### ISSUE THREAD

**Issue by Pet3ris** [vyperlang/vyper#1446]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b9
* OS: OS X
* Python Version (output of `python --version`): 3.7
* Environment (output of `pip freeze`):

### What's your issue about?

The following contract:

```
holdings: public(uint256)

@private
def getHoldings() -> uint256:
    return self.holdings

@public
def getZero() -> uint256:
    token_reserve: uint256 = self.extBalanceOf()
    return 0
```

Compiles to blocks that include dynamic jump statements:

![image](https://user-images.githubusercontent.com/224585/58253128-9f54a300-7d5f-11e9-98ed-ad5afa10c7f1.png)

In this case the jump destination originates in memory.

As a result Vyper bytecode is much harder to analyze using static analysis/formal verification techniques, which could limit assurances for Vyper contracts

### How can it be fixed?

-

**Comment by fubuloubu** [comment]
We moved from `CALL` to `JUMP` because the gas costs were just too high for private calls. After EIP-615 is hopefully implemented, we will most likely adopt `STATICJUMP` instead.

**Comment by jacqueswww** [comment]
To elaborate on what @fubuloubu said - we use dynamic jumps because of how we use copying of parameters, and copying of existing function context to the stack when making a private call.

**Comment by Pet3ris** [comment]
@fubuloubu @jacqueswww - thanks both, that makes a lot of sense!

**Comment by fubuloubu** [comment]
Watching EIP-2315: https://ethereum-magicians.org/t/eip-2315-simple-subroutines-for-the-evm/3941

**Comment by charles-cooper** [comment]
Closing since dynamic jumps (i.e. JUMP which is not immediately preceded by a PUSH2 constant) are necessary for invoking private functions.
