### ISSUE TITLE
Documentation on testing a contract is wrong

### ISSUE THREAD

**Issue by choosy** [vyperlang/vyper#1481]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b10
* OS: linux
* Python Version 3.7.3
* Environment (output of `pip freeze`):

### What's your issue about?
I'm reading through docs here: https://vyper.readthedocs.io/en/v0.1.0-beta.10/testing-deploying-contracts.html
in regards to testing a contract. 

It talks about two options, one using pyethereum>2.0.0 one using vyper-run.

Problem is, pyethereum is marked as deprecated in ethereum account. And vyper-run command does not exist. How should this be?

**Comment by fubuloubu** [comment]
Thanks for the issue! That whole page needs to be revamped to use Web3py for testing and deployment. The Vyper API also changed.

**Comment by iamdefinitelyahuman** [comment]
I think this issue can be closed.

**Comment by fubuloubu** [comment]
Yes! Closed as of #1497
