### ISSUE TITLE
Cannot define a byte array constant with value that exact same size as the array 

### ISSUE THREAD

**Issue by SAYONG** [vyperlang/vyper#1538]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b10
* OS: Linux 4.19.49-1-MANJARO
* Python Version (output of `python --version`): 3.73
* Environment (output of `pip freeze`):
```
pycryptodome==3.8.2
vyper==0.1.0b10
```
### What's your issue about?

I've tried to create a constant type `bytes[4]` and then assign byte array size 4 to constant.

Contract `const.vy`:
```python
CONST_BYTES: constant(bytes[4]) = b'\xf2\x3a\x6e\x61'
```

Command
```
vyper const.vy
```

Returns:
```
Error compiling:  issue-2.vy
vyper.exceptions.TypeMismatchException: line 1: Invalid value for constant type, expected bytes[4] got bytes[4] instead
CONST_BYTES: constant(bytes[4]) = b'\xf2\x3a\x6e\x61'
----------------------------------^
```
But when I try to increase size of the constant to be 5 then everything fine.
```python
CONST_BYTES: constant(bytes[5]) = b'\xf2\x3a\x6e\x61'
```

**Comment by fubuloubu** [comment]
Looks like a `<` -> `=<` bug in the code somewhere

**Comment by SAYONG** [comment]
@fubuloubu I guess it's because a `<` from this line -> [link](https://github.com/ethereum/vyper/blob/4369ceacf0559a3de2f459f00ea845f18af9f818/vyper/parser/constants.py#L52).
But I'm not sure if it's intentional or not.
