### ISSUE TITLE
Coveralls is broken

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1577]
Just noticed that Coveralls hasn't been working for months. I know it broke when we upgraded, but it would be useful to get it working again. @davesque had a comment somewhere about it, but I forgot where it was.

Link:
https://coveralls.io/github/ethereum/vyper?branch=master

**Comment by davesque** [comment]
Unless we want to expose build environment variables to forked branches, it will only work on the master branch.

**Comment by fubuloubu** [comment]
Oh, even the Master branch is broken:
```
LAST BUILD ON BRANCH master

Committed 15 Mar 2019 - 20:17
```

**Comment by iamdefinitelyahuman** [comment]
This can probably be closed.

**Comment by fubuloubu** [comment]
We moved to codecov from coveralls
