### ISSUE TITLE
Replace self.pos with self.ast_node on LLLNode

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1609]
Per discussion during #1583:

Currently `LLLnode` accepts a `pos` kwarg which is used for source mappings. This is typically generated via `getpos(node)`. By allowing `LLLnode` to accept an AST node directly, `pos` can still be generated and now we also have the node available - allowing us to raise more expressive exceptions.

To implement this, add another kwarg `ast_node` to `LLLNode`'s init that takes precedence over `pos` when given. Going forward we will favor the use of `ast_node` over `pos`, but won't immediately remove `pos` as it could break the code in many places at once.

**Comment by iamdefinitelyahuman** [comment]
Note to self: use `mypy` to find all occurrences of `pos`, and this should be a fairly straightforward conversion.  Should try to get this in before the next release when the number of open PRs is at a minimum, as it will touch a lot of files.

**Comment by charles-cooper** [comment]
note: `pos` was renamed to `source_pos` in dfbca3eea5118ebb7873979c2e122634b7c70c53. also the number of places where `source_pos` is added is very small, so this should be a much easier change now
