### ISSUE TITLE
VIP: Compatibility with Solidity Interfaces using types not supported in Vyper

### ISSUE THREAD

**Issue by maurelian** [vyperlang/vyper#1616]
## Simple Summary

Some ERC interfaces defined in Solidity are impossible to implement in Vyper.

## Abstract

Take [ERC-1404 as the example](https://github.com/simple-restricted-token/simple-restricted-token#the-standard)

It contains this function:

`function messageForTransferRestriction (uint8 restrictionCode) public view returns (string);`

vyper gives it this ID (because I can't define a uint8 input arg
`'messageForTransferRestriction(uint256)': '0x22e51888'`

Solidity gives it this ID: 
7f4ab1dd: messageForTransferRestriction(uint8)

## Motivation
Interoperability and adoption.

## Specification

I'll leave that to you. 

## Backwards Compatibility

old code should still work.

## Dependencies

Similar to #884 and #903.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by charles-cooper** [comment]
My initial thought is that we don't really want to support every type solidity does, so we should provide a way for the programmer to manually override the function signature for the purpose of generating the function selector. We could use a `@method_id_signature('<override_sig>')` decorator. It is up to the programmer then to check constraints that the overridden function signature implies, such as checking that uint8 input is between 0 and 255.

**Comment by charles-cooper** [comment]
Or simpler, the programmer provides the function selector directly. That way there is no chance of confusion that they actually wanted a different signature.

`@function_selector('0x7f4ab1dd')`

**Comment by maurelian** [comment]
that's kind of what I was thinking too.

**Comment by fubuloubu** [comment]
I would prefer the former rather than the later, but both seem kind of magical to me, and could lead to obfuscated behavior.

**Comment by maurelian** [comment]
Seems safe if the compiler is also detecting and preventing collisions per discussion in #1603. 
Though there may eventual also be shenanigans related to upgrading.

**Comment by fubuloubu** [comment]
We'll have to discuss that in the next meeting

**Comment by fubuloubu** [comment]
Resolution: natively implement `uint8` type (and others) instead of being fancy

**Comment by fubuloubu** [comment]
Punting on this for v0.2 milestone

**Comment by SuperCipher** [comment]
> Punting on this for v0.2 milestone

@fubuloubu 
Hi.
I was curious about the status of this issue

**Comment by fubuloubu** [comment]
> > Punting on this for v0.2 milestone
> 
> @fubuloubu Hi. I was curious about the status of this issue. Is it already merged somewhere?

you can use `uint8` type today. We are working on other types. I think we can close this issue as superceded by: #2559
