### ISSUE TITLE
Add Architecture section to docs

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1618]
Per #1612, it would be good to have a high level architectural overview of the compiler stages and codebase to make it easier for contributors.

**Comment by fubuloubu** [comment]
From @smarx in gitter:
> Could someone go through the Python AST and/or vyper AST (`ast.py`) and write down where there's a difference between the Python grammar/semantics and Vyper's? A couple quick examples of what we're thinking about:
> - Vyper does preprocessing to turn structs and contracts into classes and keeps track of the original token outside of the AST (I think).
> - for loops have an else in Python, but Vyper seems to just ignore that. Should it be rejected? Or should it be used?
> - Vyper has units, like uint256(wei). That probably looks like a function call in the Python AST?

**Comment by fubuloubu** [comment]
@davesque's work might be relevant to this: https://github.com/davesque/rust-vyper/tree/master/parser/src/grammar

**Comment by smarx** [comment]
I'm not sure what to make of that. `Vyper.grammar` certainly doesn't look complete.

**Comment by fubuloubu** [comment]
I think Dave did it as a diff to Python's grammar. Also, still a WIP

**Comment by davesque** [comment]
I wouldn't use those grammar definitions in rust-vyper as any kind of reference at this point. They're really more like a collection of my own (incomplete and in flux) notes.

**Comment by fubuloubu** [comment]
A good suggestion is to add doc strings to `vyper/ast.py` and generate documentation from that

**Comment by charles-cooper** [comment]
Seems done, see https://github.com/vyperlang/vyper/issues/1411 which links to relevant docs
