### ISSUE TITLE
Cannot create a constant array of uint256 type: implying int128

### ISSUE THREAD

**Issue by michwill** [vyperlang/vyper#1628]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b12+commit.a01cdc8
* OS: linux
* Python Version (output of `python --version`): 3.6.8
* Environment (output of `pip freeze`):

### What's your issue about?

```python
compile_code(""" 
A: constant(uint256[2]) = [0, 0] 
  
@public 
def g(): 
    pass 
""") 
```
This raises:
```
TypeMismatchException: line 2:26 Invalid value for constant type, expected uint256[2] got int128[2] instead
```

**Comment by iamdefinitelyahuman** [comment]
This was fixed by type checking in 0.2.0
