### ISSUE TITLE
make dev-deps 

### ISSUE THREAD

**Issue by shuishangmusheng** [vyperlang/vyper#1639]
In file included from cytoolz/dicttoolz.c:17:
    /usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m/Python.h:25:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/zhangjie/vyperStudy/vyper-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/pj/wjwsvp997sb_mly_gpmmm0zw0000gn/T/pip-build-fct6wuhu/cytoolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/pj/wjwsvp997sb_mly_gpmmm0zw0000gn/T/pip-ds548at5-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/zhangjie/vyperStudy/vyper-env/include/site/python3.6/cytoolz" failed with error code 1 in /private/var/folders/pj/wjwsvp997sb_mly_gpmmm0zw0000gn/T/pip-build-fct6wuhu/cytoolz/

**Comment by shuishangmusheng** [comment]
Mac system

**Comment by fubuloubu** [comment]
@shuishangmusheng is this still an issue for you? Please make sure you have a clean virtualenv with all the correct dependencies installed. Try [pyenv](https://github.com/pyenv/pyenv), as it will help you set it up.

**Comment by iamdefinitelyahuman** [comment]
Closing for now, if you have any questions feel free to join us on [Gitter](https://gitter.im/vyperlang/community)
