### ISSUE TITLE
Feature refactor: default nonreentrant key

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1640]
I think the semantics of `@nonreentrant(<key-name>)` are a little difficult to describe to the average user, and that allowing a default value (perhaps `lock`) under the hood would reduce confusion to those trying to use this feature. You could then specify it without the parents syntax as just `@nonreentrant` which would make it easier to use, and safer for those untrained in how to use the more advanced functionality of this feature.

**Comment by fubuloubu** [comment]
The docs should be refactored to use this default mode, only describing the ability to select keys as an optional feature.

**Comment by charles-cooper** [comment]
closing as 199f2b65e43e3d3f055756039ef4a9bce7f6f3cf removes fine-grained nonreentrancy keys from the language (only the global `@nonreentrant` is supported now)
