### ISSUE TITLE
Example auction limitation is not necessary

### ISSUE THREAD

**Issue by fulldecent** [vyperlang/vyper#1642]
Regarding https://vyper.readthedocs.io/en/v0.1.0-beta.13/vyper-by-example.html

It is not necessary that a bidder be limited to 128 bids. This restriction can be removed to achieve feature parity with the referenced Solidity contract.

Other potential improvements include not locking up funds if a reveal is done too late and not requiring a "fake" parameter.

PR coming

**Comment by fulldecent** [comment]
PR at https://github.com/ethereum/vyper/pull/1643

**Comment by fubuloubu** [comment]
I think the original point of the examples was to offer contracts that were feature-parity with the Solidity counterparts to make it easier for newcomers to explore similarities and differences between the two language. I'm open to some of the suggested improvements, but we should agree that they are not any more complex to understand than the code that it is replacing as it will be read by beginners to Vyper.

**Comment by fulldecent** [comment]
Agreed.

I read "not as good as Solidity" in the example, got triggered, and went to work! Now it's better and simpler than the Solidity example.

Another goal for me was to add our NatSpec comments.

**Comment by fubuloubu** [comment]
Ha! Well, I definitely think the code is a little bit clearer, it's got a :+1: from me

**Comment by fubuloubu** [comment]
Not an issue, waiting on updates to #1643 to merge
