### ISSUE TITLE
Change Istanbul opcode costs

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1653]
### What's your issue about?
Gas costs are changing in Istanbul! (See [EIP-1884](https://eips.ethereum.org/EIPS/eip-1884), [EIP-2028](https://eips.ethereum.org/EIPS/eip-2028), and [EIP-2200](https://eips.ethereum.org/EIPS/eip-2200))

Here's a preliminary table:

Name | Type | Address | Previous Cost | New Cost 
-- | -- | -- | -- | --
SLOAD | Opcode | 0x54 | 200 | 800
BALANCE | Opcode | 0x31 | 400 | 700
EXTCODEHASH | Opcode | 0x3F | 400 | 700
SSTORE | Opcode | 0x55 | 20000/5000 | TBD
CALLDATALOAD | Opcode | 0x35 | 68 (per byte) | 16 (per byte)

### How can it be fixed?
Just change the numbers when they're finalized

Note: might be best to add this feature via #1230 ruleset switch so there it fails to compile under pre-Istanbul rules

---

EDIT: Removed [EIP-1108](https://eips.ethereum.org/EIPS/eip-1108) because it was updating precompiles, not opcodes.

**Comment by fubuloubu** [comment]
Note: We don't have `ECADD` or `ECMUL` to contend with, and since we do the worst case with `SSTORE` it's not necessary to modify. `EXTCODEHASH` to be added via #1765. #1764 updates `SLOAD` and `BALANCE`.

I couldn't figure out the best strategy to modify `CALLDATALOAD` costs, because they don't seem to be implemented in the standard way.

**Comment by charles-cooper** [comment]
CALLDATACOPY needs to be changed as well

**Comment by charles-cooper** [comment]
> CALLDATACOPY needs to be changed as well

Never mind - we don't need to do anything about this. The gas cost for tx data is deducted before execution starts. It doesn't affect the cost of CALLDATALOAD or CALLDATACOPY.

**Comment by fubuloubu** [comment]
Just noticed that `ECADD`/`ECMUL` are precompiles, not opcodes. We don't seem to implement gas cost estimation for precompiles? See #1766
