### ISSUE TITLE
CompilerPanic exception is over-used

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1656]
The `CompilerPanic` exception is used a lot throughout the codebase as a catch-all for exceptional conditions (for example: https://github.com/ethereum/vyper/blob/master/vyper/parser/lll_node.py). It should only be sparingly used for scenarios that users are unlikely to run in to. #1655 is an example where this is not true, providing a 0 for `range(0)` seems like something that is likely to happen due to user input, thus the use of `CompilerPanic` exception is inappropiate and should be a more explicit exception with the proper error reporting to the user.

**Comment by charles-cooper** [comment]
It's true that CompilerPanic should definitely only be used for compiler bugs, I'm not sure this needs to be a full-blown issue, we can just address issues like #1655 as they come up.
