### ISSUE TITLE
Perform reachability/liveness analysis on LLL variables

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#1669]
### Version Information
v0.1.0b13

### What's your issue about?
when exiting multiple with statements, the asm generator creates extra unnecessary swaps. for example,
```python
(with x 1 (with y 2 (add x y)))
```
generates this asm
```python
PUSH1 1
PUSH1 2
DUP1
DUP3
ADD
SWAP1
POP
SWAP1
POP
```
obviously the most efficient version would be
```python
PUSH1 1
PUSH1 2
ADD
```

Another example:
```python
(with x 1 (add x x))
```
generates:
```python
PUSH1 1
DUP1
DUP2 # unnecessary
ADD
SWAP1 # unnecessary
POP # unnecessary
```

### How can it be fixed?

Unclear. Perhaps we could use the optimization in https://github.com/ethereum/vyper/issues/1306. The condition in #1306 is too broad but a narrower condition for when to apply that optimization could work. But I think the best thing to do is to reduce the number of stack items generated by 1. So if `x` is referenced 1 time, no dups needed. If `x` is referenced `N` times, only `N - 1` dups needed.

**Comment by fubuloubu** [comment]
Seems like it's some sort of safety against overwrite mechanism, which I agree seems unnecessary. Probably in general LLL could be more stack-aware

**Comment by charles-cooper** [comment]
The branching problem becomes more tractable if each branch is responsible for copying any stack items it needs (instead of the outer block trying to analyze the branching).

We can annotate this with a kind of function call syntax. Instead of
```
(with x 1 (seq (add 1 x) (if <cond> (mstore 0 x) (pass))))
```
use
```
(with x 1 (seq (add 1 x) (if <cond> <x,args...> (mstore 0 x) (pass))))
```
The difference is that, in my previous suggestion, x is DUPed unconditionally, and in the branch without x, it gets POPped again. Now, x is DUPed conditionally as the branch is entered.

**Comment by charles-cooper** [comment]
closing this as it is superseded by recent work on venom IR (#3659 )
