### ISSUE TITLE
initializing empty arrays

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#1675]
since https://github.com/ethereum/vyper/issues/1493 arrays can't be left uninitialized. we should introduce a way to create a freshly zeroed array, along the lines of `zero_array(N)`, or maybe have a special case for arrays to be uninitialized (that does explicitly set them to zero).

**Comment by fubuloubu** [comment]
In Rust, you can initialize static arrays (in fact you must) by doing the following:

```rust
a: [u8; 32] = [0u8; 32];
```
Note that then the type signature becomes unnecessary (except for constants).

I think it looks quite clean, and could serve as inspiration

**Comment by charles-cooper** [comment]
I thought about that but maybe we don't want to allow mismatches like
```
x: uint256[10] = zero_array(uint256, 20)
```
Since the type/size hint on the RHS is redundant we can just infer it either with a syntactic sentinel value (like `None`, :joy: ) or skip the RHS entirely.

**Comment by jacqueswww** [comment]
```
x: uint256[10] = zero_array(uint256, 20)
```
Should just throw a type mismatch.

**Comment by iamdefinitelyahuman** [comment]
We also need to consider multidimensional arrays, structs, and combinations thereof. Initializing an array of structs that contain arrays isn't fun.

**Comment by charles-cooper** [comment]
current proposed syntax:
```python
xs: uint256[10] = clear(uint256[10])
```

**Comment by fubuloubu** [comment]
As I mentioned in the PR (but better brought up here), can we use `empty` instead of `clear`? I don't like mixing the semantics of the two. Let's keep `clear` as clearing/resetting storage space, and `empty` as creating empty memory.

**Comment by fubuloubu** [comment]
Actually, I wonder if `default(type)` might be even clearer than `empty`?
