### ISSUE TITLE
`int128` exponentiation can overflow without error

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1685]
```python
@public
@constant
def test(x: int128, y: int128) -> int128:
    return x**y # BUG: test(2, 256) returns 0
```

The relevant compiler code is here:

https://github.com/ethereum/vyper/blob/c296b2d7532d913103aad494b749f8179a3acddc/vyper/parser/expr.py#L659-L667

**Comment by fubuloubu** [comment]
Genericize safemath operations here over all types

**Comment by charles-cooper** [comment]
similar: https://github.com/ethereum/vyper/issues/1684
