### ISSUE TITLE
Inappropriate overflow check for `addmod` and `mulmod`

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1689]
`addmod` and `mulmod` should allow arbitrary `uint256` operands, but the following code performs a check for addition or multiplication overflow:

https://github.com/ethereum/vyper/blob/c296b2d7532d913103aad494b749f8179a3acddc/vyper/functions/functions.py#L1023-L1052

This results to the following runtime errors:

```python
@public
@constant
def test1(a: uint256, b: uint256) -> uint256:
    return uint256_addmod(a, b, 12) # test(2**255, 2**255) reverts
    
@public
@constant
def test2(a: uint256, b: uint256) -> uint256:
    return uint256_mulmod(a, b, 12) # test(2**255, 2) reverts
```

**Comment by fubuloubu** [comment]
Remove the checks. The opcode's already perform modulo, so overflow/underflow isn't possible
