### ISSUE TITLE
Modulo at compile time differs from modulo at runtime

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1693]
At compile time, constant expressions are computed using Python's built-in modulo operator. It handles negative numbers differently from the EVM:

```python
@public
@constant
def foo() -> int128:
    return -5%2 # returns 1

@public
@constant
def bar(n: int128) -> int128:
    return n%2 # bar(-5) returns -1
```

**Comment by fubuloubu** [comment]
I wonder... Could we create a mini-program in LLL for a constant expression/sub-expression, then execute it in `py-evm` to get an EXACT output match?

Or, I guess just match the even semantics I guess.

**Comment by charles-cooper** [comment]
I think the issue is using `smod`. I'm unclear on the use case for `smod` tbh.

**Comment by jacqueswww** [comment]
Meeting Notes: We need more tests for this to ensure 100% the same behaviour.
