### ISSUE TITLE
Negative constants can be used in some places where `uint256` is required

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1694]
The following code casts `int128` literals to `uint256` without any check on the value:

https://github.com/ethereum/vyper/blob/c296b2d7532d913103aad494b749f8179a3acddc/vyper/parser/parser_utils.py#L415-L417

This permits the following (invalid) code to compile without error:

```python
Test: event({ n: uint256 })
x: map(uint256, uint256)

@public
def test():
    a: uint256 = self.x[-7]
    log.Test(-7)
```

**Comment by fubuloubu** [comment]
Check for literal value matching destination type
