### ISSUE TITLE
Runtime error when making an external call to the same contract

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1696]
This code makes it an error to make an external call to the same contract:

https://github.com/ethereum/vyper/blob/c296b2d7532d913103aad494b749f8179a3acddc/vyper/parser/external_call.py#L75

This is a surprising limitation. It doesn't seem to have a clear benefit, and it could be problematic. As an example, multisig wallets often use self-calls to perform administrative functions. This way the wallet owners have to agree to make a change like lowering the required threshold of signatures. In Vyper, this would produce a runtime error.

**Comment by fubuloubu** [comment]
We originally wanted to avoid a recursion/stack-exhaustion kind of attack, but I think we relaxed that a bit by just making it unergonomic. If someone wants to write it that way, they can. Just be aware of how the mechanism could be abused.

**Comment by charles-cooper** [comment]
I think this should just be a compile-time error. I think our latest consensus was to refactor into a private function for these kinds of self calls (and never use public functions like solidity external functions)

**Comment by jacqueswww** [comment]
Meeting Notes: Remove runtime-check as we have compile time check for this already, then document the behaviour.

**Comment by charles-cooper** [comment]
cf. https://github.com/ethereum/vyper/pull/1582 thanks @iamdefinitelyahuman !

**Comment by fubuloubu** [comment]
Meeting Notes: Remove assertion of `dst != self.address` in `raw_call`. Everything else is unsolved
