### ISSUE TITLE
Array types are not hashed for event topics

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1699]
Solidity hashes all array types, including `bytes` and `string`s, when they're used as indexed parameters (event topics).

Vyper only accepts `bytes` and `string`s with a maximum length of 32. They're then converted to `bytes32`. This could be an interoperability problem. Vyper doesn't appear to accept other array types as indexed event parameters at all.

**Comment by fubuloubu** [comment]
This has been pointed out before, but I can't find the issue. I'm not sure if this is covered in the ABI specification, but I feel like it should be.

cc @davesque?

**Comment by smarx** [comment]
I think https://solidity.readthedocs.io/en/v0.5.12/abi-spec.html#events is the relevant ABI documentation:

> However, for all “complex” types or types of dynamic length, including all arrays, `string`, `bytes` and structs, `EVENT_INDEXED_ARGS` will contain the _Keccak hash_ of a special in-place encoded value (see Encoding of Indexed Event Parameters), rather than the encoded value directly.
