### ISSUE TITLE
Struct getter collisions

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1702]
Due to the way getter names are generated for struct fields, collisions can happen:

```python
struct Test:
    foo: uint256
    __foo: uint256
    
a: public(Test)
a__: public(Test)
```

The error message is `Duplicate function name: a____foo`. This is better than an ambiguity, but perhaps the collision should be avoided altogether by using a separator that cannot appear in identifiers.

The following code is responsible for this naming:

https://github.com/ethereum/vyper/blob/c296b2d7532d913103aad494b749f8179a3acddc/vyper/parser/global_context.py#L230-L240

**Comment by fubuloubu** [comment]
I was thinking about this a while ago, and there's no reason the getter can't be `method_id("a.foo")` instead of `method_id("a__foo")`. That would avoid this scenario because `.` is not a valid identifier character

**Comment by fubuloubu** [comment]
Removed "bug" because this actually would change semantics, although not enough to really be a problem for anyone I don't think since it's only used externally

**Comment by jacqueswww** [comment]
Meeting Notes: Refactor public getters for structs to return the full struct.

**Comment by fubuloubu** [comment]
Note: originally this was done this way because we didn't have ABI handling for structs yet.
