### ISSUE TITLE
Negation ("unary subtraction") can underflow

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1705]
There is no check for underflow when negating:

```python
@constant
@public
def bar(x: uint256) -> uint256:
    return -x # BUG: returns 2**256 - x
```

Using `0 - x` instead reverts as expected.

The issue is here, where no check is done for underflow:

https://github.com/ethereum/vyper/blob/c296b2d7532d913103aad494b749f8179a3acddc/vyper/parser/expr.py#L969-L985

**Comment by iamdefinitelyahuman** [comment]
I believe this was fixed in https://github.com/vyperlang/vyper/pull/1638
