### ISSUE TITLE
Type confusion with timestamp negation

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1706]
Subtracting two timestamps yields a `timedelta`, but `-x` where `x` is a timestamp is still a `timestamp`:

```python
@public
def test(x: timestamp) -> timestamp:
    return -x
```

Note that this negation probably shouldn't be allowed at all, given that `timestamp` is an unsigned value, so perhaps this issue will go away when that is fixed.

**Comment by fubuloubu** [comment]
Related to #1705

**Comment by iamdefinitelyahuman** [comment]
I'm not sure exactly when we fixed this (maybe #1791?), but the example code now fails to compile with `TypeMismatchException: Not a signed type: uint256`

**Comment by fubuloubu** [comment]
That would make sense since `timestamp := uint256(s)`
