### ISSUE TITLE
Can't loop over a nested array

### ISSUE THREAD

**Issue by smarx** [vyperlang/vyper#1709]
`for` loops in Vyper can loop over arrays, but not if they're nested. This code fails to compile with the surprising error `'Subscript' object has no attribute 'func'`:

```python
@public
def __init__():
    x: uint256[5][2] = [[0, 1, 2, 3, 4], [2, 4, 6, 8, 10]]
    for i in x[1]:
        pass
```

**Comment by fubuloubu** [comment]
Seems weird, buy maybe we should allow. Should also check to see if it affects arrays in structs

**Comment by jacqueswww** [comment]
Meeting Notes: This should be allowed.
