### ISSUE TITLE
Meeting 9th December 2019

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1734]
Start time: 15:00 UTC (https://time.is/UTC)

Vidchat link: https://meet.google.com/czc-kuep-jda
Jitsi backup: https://meet.jit.si/IndifferentSquidAdaptRegularly

Agenda:
- [x] #1733
- [x] #1723
- [x] #1730
- [x] #1676
- [x] #1756

**Comment by charles-cooper** [comment]
probably also should discuss https://github.com/vyperlang/vyper/issues/1730

**Comment by charles-cooper** [comment]
we should probably reschedule this

**Comment by charles-cooper** [comment]
also https://github.com/vyperlang/vyper/pull/1728. it's ready for merge

**Comment by fubuloubu** [comment]
Rescheduled for next Monday

**Comment by fubuloubu** [comment]
Next:  #1759
