### ISSUE TITLE
Disallow @nonreentrant on __init__

### ISSUE THREAD

**Issue by robinsierra** [vyperlang/vyper#1755]
### Version Information

* vyper version: 0.1.0b13

### What's your issue about?

The `@nonreentrant` decorator doesn't make sense on `__init__` and is currently just ignored. It would probably be better to just disallow writing it.
```
@public
@nonreentrant('lock')
def __init__():
    pass
```

**Comment by robinsierra** [comment]
I'm not sure whether this is intended but it also seems to be ignored in `__default__`.

**Comment by fubuloubu** [comment]
That might be an issue? I'll have to think about it.

**Comment by Rish001** [comment]
Can I work on ths?

**Comment by iamdefinitelyahuman** [comment]
Gladly! :pray:

I think the best place for this check is in the new [`context`](https://github.com/vyperlang/vyper/tree/master/vyper/context) subpackage.  Probably somewhere in the classmethods of `ContractFunction`.

**Comment by Rish001** [comment]
Hi!
I looked into the `context `subpackage and the `classmethod `contract function but I did not come across this piece of code.Could you please tell me what do I need to do to disallow the said decorator?
