### ISSUE TITLE
Clarification about tuples

### ISSUE THREAD

**Issue by robinsierra** [vyperlang/vyper#1762]
This is partly a question and partly a request for documentation: To what extent are tuples 'officially' supported in Vyper? Are there situations in which tuples can be used but which will be disallowed in the future? I know that they can be used for multiple return values:
```
@private
def foo() -> (int128, int128):
   return 1, 2

@public
def bar() -> (int128, int128):
   a: int128 = 0
   b: int128 = 0
   a, b = self.foo()
   return self.foo()
```
Are there more cases?

**Comment by fubuloubu** [comment]
I think that's basically it?

**Comment by robinsierra** [comment]
Ok, nice. Thanks!
