### ISSUE TITLE
VIP: Add support for EXTCODEHASH

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1765]
## Simple Summary
Add support for the `EXTCODEHASH` opcode, which was added in Constantinople via [EIP-1052](https://eips.ethereum.org/EIPS/eip-1052) which allows a user to obtain the `keccak256` hash of a contract's deployed bytecode.

## Motivation
This feature is helpful for users who want to check that a particular configuration of a contract's bytecode is a given value, such as the use of proxy/registry contracts, and other uses.

## Specification
Add the function `get_extcodehash(address)` which returns the hash of the given account's address per EIP-1052 by calling that opcode. Note the updated gas costs in #1653.

## Backwards Compatibility
No backwards incompatibilities.

## Dependencies
No dependencies

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by iamdefinitelyahuman** [comment]
This will be easy to implement after #1783 - and give us something to list in the documentation under changes when targeting `constantinople` :)

**Comment by fubuloubu** [comment]
Meeting: change function name to `get_extcodehash(address)`
