### ISSUE TITLE
Optimization - remove multiple CALLVALUE checks if a contract has no payable functions

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1776]
### Current Behavior
Vyper checks that `CALLVALUE` is zero at the beginning of each function not marked as payable.

### Possible Optimization
When a contract has no payable functions, we could instead perform this check just once - at the start of the function selector.

**Comment by jacqueswww** [comment]
Well we don't have a function selector / jump table so currently we cannot optimise this :yum:

**Comment by iamdefinitelyahuman** [comment]
Maybe poor semantics..  instead of having that chunk of bytecode at the start of the logic of each function, it could happen once at the very beginning of the bytecode.
