### ISSUE TITLE
Does vyper support deploy new contracts from a contract?

### ISSUE THREAD

**Issue by dangnh0611** [vyperlang/vyper#1782]
Is there anyway to deploy new contracts at any address (random) from a contract in vyper? As solidity, we can use, for example 
`ChildContract c = new ChildContract(*args);`

**Comment by dangnh0611** [comment]
a hack like[]( https://github.com/Uniswap/contracts-vyper/blob/master/contracts/uniswap_factory.vy) solve my problem.

**Comment by fubuloubu** [comment]
`create_with_code_of` is indeed the preferred way to handle this right now
