### ISSUE TITLE
`AttributeError: 'Attribute' object has no attribute 'id'` on constants

### ISSUE THREAD

**Issue by agroce** [vyperlang/vyper#1802]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b14+commit.4ac5ef5
 OS: osx
* Python Version (output of `python --version`): 3.7.5
* Environment (output of `pip freeze`): same as previous TSTL issues

### What's your issue about?

Compiling:

```
cv0: constant(address) = block.coinbase.balance
```

produces:

```
Error compiling: vfile.67808.vy
AttributeError: 'Attribute' object has no attribute 'id'
```

**Comment by agroce** [comment]
(this is new on latest git pull; confirm some other issues fixed, my regressions mostly down to that CompilerPanic on ranges)

**Comment by agroce** [comment]
I know this is just a bad error message, at heart, but I don't want to filter out `AttributeErrors` from the testing so a fix eventually would be good to aid fuzzing.

**Comment by agroce** [comment]
And "you can't make a constant from a call" would obviously be more user-friendly.

**Comment by fubuloubu** [comment]
Great find! Hopefully, the fact that we haven't had an issue from you in a while means we're doing better 🤣

**Comment by agroce** [comment]
You guys have definitely got less to find now.

However, I'm up to some new tricks maybe soon. :)

Have you used python-afl to fuzz vyper any, by the way?

**Comment by fubuloubu** [comment]
Well, half of us are American, we're mostly fuzzy, and I think at least one of us is a lop, so fairly familiar with it but haven't used it against the codebase yet.

**Comment by agroce** [comment]
Ok, you're clean on current tests, and I have to hack AFL and a mutation testing tool before I start a more serious attack :)

Will keep you posted if anything new comes up.
