### ISSUE TITLE
VIP: Remove wei_value as a type

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1816]
## Simple Summary
Remove `wei_value` as a type.

## Motivation
We have two ways to denote a value as wei: `uint256(wei)` and `wei_value`. Both are `uint256` and so they are effectively identical. However, `uint256(wei)` is much more explicit. And why do we need two ways to say the same thing? IMO it's more likely to cause confusion than bring any benefit.

## Specification
* Deprecate `wei_value` in the upcoming release, and then remove it altogether in the following one.
* Scrub all mention of wei_value` from the documentation and example contracts, in favor of `uint256(wei)`

## Backwards Compatibility
It will break existing contracts, but the fix is as easy as find-and-replace.  I think that if we deprecate it for a release, it will give users plenty of time to modify their contracts.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
I support this VIP. Seems unecessary to have both.

**Comment by fubuloubu** [comment]
Units are gone, so shall this be. Begone!
