### ISSUE TITLE
Weird issue with returning data

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1821]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b15
* OS: linux
* Python Version (output of `python --version`): 3.7.5

### What's your issue about?
contract:
```python
from vyper.interfaces import ERC721 
 
@public 
def foo(): 
    success: bool = ERC721(msg.sender).transferFrom(msg.sender, self, 1) 
```

error:
```bash
vyper/parser/stmt.py in _check_valid_assign(self, sub)
    140                 )
    141         # Check that the integer literal, can be assigned to uint256 if necessary.
--> 142         elif (self.stmt.annotation.id, sub.typ.typ) == ('uint256', 'int128') and sub.typ.is_literal:
    143             if not SizeLimits.in_bounds('uint256', sub.value):
    144                 raise InvalidLiteralException(

AttributeError: 'NoneType' object has no attribute 'typ'
```

### How can it be fixed?
Unsure where this comes from, but if I remove `success: bool =` from the equation it goes away

**Comment by charles-cooper** [comment]
I think, this is the same deal as https://github.com/vyperlang/vyper/issues/1823. `transferFrom` doesn't actually return anything.

**Comment by fubuloubu** [comment]
Yeah, it shouldn't compile but the error message is off
