### ISSUE TITLE
ERC721 Interface is wrong

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1822]
### What's your issue about?
The `ERC721` interface in our repository does not conform with the `ERC721` spec

### How can it be fixed?
Likely stemming from these lines:
https://github.com/vyperlang/vyper/blob/44f44dea7dfed836caa92e56ee28a5c7392a7bd4/vyper/interfaces/ERC721.py#L39-L45

which should be replaced with:
```python
 @public 
 def safeTransferFrom(_from: address, _to: address, _tokenId: uint256, _data: bytes[1024]=b""): 
     pass 
```
so as to generate the correct interface (where `safeTransferFrom` is overloaded)

**Comment by iamdefinitelyahuman** [comment]
Not sure when, but this has been fixed.

**Comment by SuperCipher** [comment]
Is this fixed by using the default parameter seen here https://github.com/vyperlang/vyper/issues/903

**Comment by fubuloubu** [comment]
> @fubuloubu 
> Is this issue fixed by using the default parameter seen here https://github.com/vyperlang/vyper/issues/903

Yes! Please see our ERC721 example contract

The one slight issue for ERC721 is that we don't have `bytes4` for ERC165 (which is required per ERC165), but we are working on adding that soon

You could probably fake it by making a `__default__` method that works with that method_id though

**Comment by fubuloubu** [comment]
@SuperCipher this gave me an idea! See
https://github.com/vyperlang/vyper/pull/2622
