### ISSUE TITLE
Allow interfaces to be used in mappings

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1824]
### What's your issue about?

Using interfaces as a destination in a mapping:
```python
interface MyInterface: 
    def kick(): modifying

kickers: HashMap[address, MyInterface]
```
raises this exception:
```bash
vyper/types/types.py in parse_type(item, location, sigs, custom_units, custom_structs, constants)
    352             )
    353         else:
--> 354             raise InvalidTypeException("Invalid base type: " + item.id, item)
    355     # Units, e.g. num (1/sec) or contracts
    356     elif isinstance(item, ast.Call) and isinstance(item.func, ast.Name):

InvalidTypeException: line 5:26 Invalid base type: MyInterface
     4
---> 5 kickers: HashMap[address, MyInterface]
---------------------------------^
     6
```

doesn't really seem to be any reason why, especially since it works for standard variables and arrays:
```python
interface MyInterface: 
    def kick(): modifying

kicker: MyInterface
kickers: MyInterface[5]
```

### How can it be fixed?
Allow it to use interfaces as the _destination_ of a mapped entry

**Comment by iamdefinitelyahuman** [comment]
This should also include memory and calldata i think.  Currently interfaces can only be assigned as a type within storage.

**Comment by fubuloubu** [comment]
Yeah, I was thinking about calldata, something like would be neat:
```python
@public
def exchange(token1: ERC20, token2: ERC20):
    ...
```

**Comment by iamdefinitelyahuman** [comment]
exactly.  in the signature it's still considered an address, we're just automagically recasting it.  this is how solidity handles it.

**Comment by fubuloubu** [comment]
Requires a refactor of parser to be implemented, not a breaking change so we can implement in a patch release after v0.2.0
