### ISSUE TITLE
VIP: Change contract keyword to interface

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1825]
## Simple Summary
Use `interface` as the keyword for defining an interface.

## Motivation
VIP #885 added Interfaces to Vyper, but it chose the `contract` keyword, which in retrospect seems inconsistent with it's intended purpose.

## Specification
Just change the keyword. Consider deprecating it first. It would look like:
```python
interface MyInterface:
    def do_stuff(): modifying
```

## Backwards Compatibility
This VIP would not be backwards compatible and would require a small change from users.

## Dependencies
Depends on #885, which is already implemented

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by iamdefinitelyahuman** [comment]
I'm in favor of this.  Coming from Solidity, having an interface marked as a `contract` at the top, and then the actual contract having no designation - this always felt confusing to me.

**Comment by fubuloubu** [comment]
Meeting note: Make a sensible error message if `contract` is used

**Comment by fubuloubu** [comment]
@iamdefinitelyahuman Shall we target for 0.2.0?
