### ISSUE TITLE
issue generating ABI

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1826]
### Version Information

* vyper Version : 0.1.0b15
* OS: linux
* Python Version : 3.8

### What's your issue about?
The following code raises an `InvalidTypeException` when attempting to generate an abi via `compile_code`:
```python
from vyper.interfaces import ERC721 
token: public(ERC721) 
@public 
def __init__(_token: address): 
    self.token = ERC721(_token)
```
It does not raise when compiling to bytecode.

**Comment by iamdefinitelyahuman** [comment]
This leads to much bigger questions re: expected behavior of contract types.

**Comment by fubuloubu** [comment]
Is this still a problem?

**Comment by iamdefinitelyahuman** [comment]
Seems not.
