### ISSUE TITLE
KeyError when using an absolute file name

### ISSUE THREAD

**Issue by robinsierra** [vyperlang/vyper#1828]
### Version Information

* vyper version: 0.1.0b15
* OS: Linux, MacOS
* Python version: 3.7

### What's your issue about?

Since 0.1.0.b15 using an absolute filename when calling Vyper from the command line 
```$ vyper /home/.../mycontract.vy```
 causes a KeyError.

**Comment by fubuloubu** [comment]
Why are there 3 dots?

**Comment by robinsierra** [comment]
Oh sorry,  I just used them as a replacement for my actual path. I meant something like this
```$ vyper /home/me/myproject/mycontract.vy```

**Comment by fubuloubu** [comment]
Gotcha, haha. Yes, this seems like a bug. I wonder why...

**Comment by robinsierra** [comment]
It only happens for me if the file is in some subdirectory of my current directory. If I change the root path to something else it works.

**Comment by fubuloubu** [comment]
And this was working before `b15`?

**Comment by robinsierra** [comment]
Yes.

**Comment by iamdefinitelyahuman** [comment]
The issue comes from #1784 - sorry about that!  Working on a fix now.

**Comment by iamdefinitelyahuman** [comment]
The issue comes from 7902d9ff0df71f30b2293de18050f9dc5dd26f84 - sorry about that!  Working on a fix now.
