### ISSUE TITLE
Cannot generate AST from ABI containing string or bytes

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1832]
### Version Information
* vyper Version: 0.1.0b16
* OS: linux
* Python Version: 3.7

### What's your issue about?
When importing a `json` file as an interface, if any inputs or outputs use type `string` or `bytes`, there is a `TypeError` raised:

```python
  File "vyper/signatures/interface.py", line 72, in abi_type_to_ast
    slice=ast.Index(256)
TypeError: __init__() takes 1 positional argument but 2 were given
```

It seems `ast.Index` is incorrect being initiated for these types:

https://github.com/vyperlang/vyper/blob/d4c53204ce4bb3a314443f6d6deadbb2b2111cdd/vyper/signatures/interface.py#L59-L73

**Comment by fubuloubu** [comment]
ABI encoder ftw
