### ISSUE TITLE
ABI issue with bytes and string arrays inside tuples

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1841]
### Version Information

* vyper Version (output of `vyper --version`): `0.1.0b16`
* OS: linux
* Python: `3.8`

### What's your issue about?

Returning a tuple that contains a bytes or string array that came from another contract call gives incorrect return data:

```python
def test_bytes_inside_tuple(get_contract):
    code = """
@public
@constant
def test_return() -> (bytes[6], uint256):
    return b"potato", 42
    """
    c1 = get_contract(code)

    code = """
contract jsonabi:
    def test_return() -> (bytes[6], uint256): constant

@public
def test_values(a: address) -> (bytes[6], uint256):
    return jsonabi(a).test_return()
    """

    c2 = get_contract(code)
    assert c2.test_values(c1.address) == [b"potato", 42]
```

The above test fails with:
```
AssertionError: assert [b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00*\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06', 50855962295469179162425751602892202823040865300719823209625149558373627199488] == [b'potato', 42]
```

Some observations:

1. The returned bytes array is always exactly 64 bytes long. I've tried a range of values between `bytes[6]` and `bytes[256]`.
2. The location of the bytes array within the tuple does not seem to have an effect.
3. The test passes if you assign the individual tuple values to memory variables and then return an array of those variables.
4. The same behavior exists with `string`.
5. The error is not present when using a `uint[]` array.
6. The error is not present when calling from a public function into a private function in the same contract.

**Comment by michwill** [comment]
Having the same issue with arrays of uint256 inside structs

**Comment by charles-cooper** [comment]
I think this has to do with decoding ABI-encoded return data which I haven't gotten around to yet.

**Comment by fubuloubu** [comment]
@charles-cooper any update on looking at this?

**Comment by saikat041** [comment]
@fubuloubu I have been able to solve this issue. But I am not very sure where to put the above test case. There are no test cases that are similar to this. I have already created a pull request for the same
