### ISSUE TITLE
Raise a warning when exceeding code size limit (EIP-170)

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1850]
### What's your issue about?
The compiler should raise a warning when size of the generated runtime bytecode is >24577 bytes ([EIP-170](https://github.com/ethereum/EIPs/issues/170)).

Because other chains may have different / no limits, we should not raise an exception. But I think for the majority of users, a warning will save some debugging headaches.

**Comment by fubuloubu** [comment]
Just to clarify, is it the deployment bytecode or the runtime bytecode that's affected by this size?

I believe it's the runtime, but should be sure of that. Error message should probably give some of this context too e.g. constructor doesn't count towards codesize

**Comment by iamdefinitelyahuman** [comment]
Yes, 100% it's based on runtime bytecode.

**Comment by fubuloubu** [comment]
close in favor of #2150
