### ISSUE TITLE
Fuzzing CI keeps failing

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1860]
Looks like some sort of memory issue, possible could be solved by having settings configured for timeouts in the Lark fuzzer

**Comment by fubuloubu** [comment]
reference: https://github.com/vyperlang/vyper/runs/446873464?check_suite_focus=true

**Comment by charles-cooper** [comment]
can't pull up the reference CI run anymore but i believe was fixed in https://github.com/vyperlang/vyper/pull/2719
