### ISSUE TITLE
Is there any plan to support  translating vyper to wasm?

### ISSUE THREAD

**Issue by vita-dounai** [vyperlang/vyper#1861]

**Comment by fubuloubu** [comment]
Not at this time, but we are participating in the [EVM-LLVM](https://github.com/etclabscore/evm_llvm) project which would allow us access to a very strong WASM compiler that could be leveraged alongside the work the eWASM team is doing, when it eventually comes time to make that move in the coming years.

**Comment by iamdefinitelyahuman** [comment]
Closing this for now, if you have further questions feel free to join us on [Gitter](https://gitter.im/vyperlang/community).
