### ISSUE TITLE
VIP: Modify event declaration syntax to resemble that of struct

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1864]
## Simple Summary
Change this:

```python
Transfer: event({_from: indexed(address), _to: indexed(address), _value: uint256})
```

to this:

```python
event Transfer:
    _from: indexed(address)
    _to: indexed(address)
    _value: uint256
```

## Motivation
The current approach to declaring an event reads as though there is a variable being created, with it's type defined from the result of a call to an `event` function.  This is misleading because:

1. The created event is not a variable. You cannot assign to it during declaration, or reference it except as a callable member of `log`.
2. `event`, though appearing to be a function, is not a function. And type annotations are not typically declared as the result of a function call.
3. The reliance on the ordering of dictionary keys inside `event` is not a standard python behavior until version 3.7. Declaring the fields in this way does not intuitively read as though they are sequenced.

By instead using the struct-style declaration, we make it more clear that this not a simple variable, and that the members inside are sequenced.

## Backwards Compatibility
This will be a rather large breaking change, we should definitely discuss it at length. If it is approved, it probably belongs in the `1.0rc` release.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Should changing the way logs are emitted also be a part of this proposal?

(From `log.<EventName>({...})` to `log(EventName({...}))`)

Example:
```python
event MyEvent:
    arg1: indexed(address)
    arg2: uint256
...
log(MyEvent({msg.sender, msg.value})
```

**Comment by jacqueswww** [comment]
Approved; makes to align the syntax with `struct`.

**Comment by fubuloubu** [comment]
@iamdefinitelyahuman Let's make this happen with 0.2.0?

**Comment by iamdefinitelyahuman** [comment]
For an event without any arguments:

```python
event Foo: pass
```

**Comment by iamdefinitelyahuman** [comment]
for emitting events, i think `log` is better as a statement.  Also, I don't like the use of curly brackets inside the call, I don't think they serve any purpose.

To me the ideal syntax would be:

```python
log MyEvent(msg.sender, msg.value)
```

**Comment by fubuloubu** [comment]
:ship: :ship: :ship:
