### ISSUE TITLE
VIP: Remove RLPList

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1866]
## Simple Summary
Remove the builtin `RLPList` function.

## Motivation
My understanding is that this function was put in place for, and served a very specific purpose related to the ETH 2.0 deposit contract. With a specific version of Vyper forked, verified and frozen for said contract, I see no need to keep this function as a part of the language.

## Specification
1. Remove `RLPList` from `vyper/functions`
2. Remove the test cases
3. Remove the section in the documentation

## Backwards Compatibility
It is a breaking change, but I highly doubt it will affect any existing projects.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
I see this change overall as good, because the RLP decoder is really not what most people want, rather they want #1406. So, this change should come after we finish that one.

**Comment by jacqueswww** [comment]
Approved; should be replace by ABI - encoder / decoder.

**Comment by iamdefinitelyahuman** [comment]
Closed by #1872 and #1975
