### ISSUE TITLE
VIP: Remove assert and raise as callables

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1867]
## Simple Summary
`assert` and `raise` should only be possible via statements, not callable functions.

## Motivation
Allowing these two commands to happen as statements _and_ functions creates ambiguity in the syntax without any added benefit that I can see. I believe being opinionated here will make for more readable smart contracts, and means we can reduce some complexity in the vyper codebase.

## Specification

Currently all of the following syntax is valid.  This VIP proposes that the second set of examples should be _invalid_.

```python
# keep this
assert foo, "oopsie"
raise "oopsie"

# remove this
assert(foo, "oopsie")
raise("oopsie")
```

## Backwards Compatibility
This will be a breaking change, if approved we might want to delay it until a major release.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Note: I believe `raise(...)` is rejected, but `assert(...)` is not (or vice versa, I forget)
