### ISSUE TITLE
VIP: Temporarily remove type units

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1881]
## Simple Summary
The current implementation of type units feels inconsistent and confusing. I would like to remove them from the language in their current form.

## Motivation
While working on type checking I keep running into issues with units. All of this is made much more difficult because there is very minimal documentation on the subject.

1. `uint256` is considered "unitless", so assignments such as `uint256(wei) = uint256` are permitted. It took me a while to realize this was the case, I assumed `uint256` was equivalent to `uint256(None)` and so should not be compatible with `uint256(wei)`.
2. Addition and subtraction between values with different units is disallowed, but multiplication and division is allowed and produces new compound unit types. This is completely undocumented and does not feel intuitive to me.
3. `wei_value` and `uint256(wei)`, despite both being `uint256` with unit `wei`, are incompatible. 
4. Same for `timestamp`, `timedelta`, and `uint256(sec)`.  Per the documentation, `timestamp` additionally cannot be added or subtracted with another `timestamp`. I was unable to check with this firsthand, as attempting to assign to `timestamp` or `timedelta` gives me a `TypeMistmatch`. These feel broken.

While I'm not inherently opposed to the idea of units, the current implementation feels more confusing than beneficial. I propose we remove units altogether while refactoring. We can revisit the concept once refactoring is complete and documentation is up-to-date, and hopefully come up with another approach that's cleaner and more consistent.

## Backwards Compatibility
It's a breaking change.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Meeting notes: discuss with the community, tentatively accepted for now

**Comment by iamdefinitelyahuman** [comment]
![image](https://user-images.githubusercontent.com/35276322/77826002-36c81680-7126-11ea-9aef-cb61c8e9e363.png)
