### ISSUE TITLE
Convert bytes[20] => address

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1901]
### What's your issue about?
In order to convert a `bytes[20]` to an `address`, one must do the awkward intermediate step of converting to `bytes32` first i.e `convert(convert(slice(_data,  0, 20), bytes32), address)`. It should be possible to more directly convert via `convert(slice(_data,  0, 20), address)`

### How can it be fixed?
Make it so

**Comment by charles-cooper** [comment]
fixed as of #2694
