### ISSUE TITLE
VIP: Allow raise without reason string

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1902]
## Simple Summary
Allow use of `raise` without a reason string.

## Motivation
1. I see no technical reason to enforce requiring a revert string. A bare `raise` statement is parseable.
2. Requiring a reason for `raise` but not `assert` is inconsistent.
3. The requirement is easily circumvented:
```python
assert False
```

## Specification
Fairly self-explanatory. The following syntax should compile:

```python
if cond:
    raise
```

## Backwards Compatibility
Will not cause any issues.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by charles-cooper** [comment]
I'm on board with this
