### ISSUE TITLE
asttokens issue

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1922]
### Version Information
0.1.0-beta.17

### What's your issue about?
I had to include a workaround here because there was an issue with the asttokens dependency throwing a dumb error on modules where a docstrings was the only element in the ast. See:
https://github.com/vyperlang/vyper/blob/e27fd81b8ec81eafdb2d24d25c2c7658e0aa651e/tests/grammar/test_grammar.py#L116

### How can it be fixed?
Remove the dependency, remove the need for the dependency, or have the dependency upstream a fix

**Comment by charles-cooper** [comment]
fixed in https://github.com/vyperlang/vyper/pull/2719
