### ISSUE TITLE
VIP: Add min and max type

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1923]
## Simple Summary
Add the ability to get the minimum and maximum values for a given type via `min_value(type)` and `max_value(type)`. Remove value constants like `ZERO_ADDRESS`, `MIN_UINT256`, and `EMPTY_BYTES32`

## Motivation
#1675 adds `empty(type)` to specify an empty section of memory filling the size of `type`. This can be used to simulate "default" values that the EVM provides all types. Some types deserve the ability to also specify their edge-case values, so functionality should be added to ensure this is possible. After this featureset is fully implemented, it makes sense to eliminate the standard constants that are provided with Vyper, as they can be replicated with this more advanced featureset

### `min_value(type)`
Returns the minimum representation value of the given type (the most negative value for a given type). Raises a compilation error if the type does not have a minimum representation type (like `bytes32` or `address`)

Throws for more complex types.

### `max_value(type)`
Returns the maximum representation value of the given type (the most positive value for a given type). Raises a compilation error if the type does not have a maximum representation type (like `bytes32` or `address`)

Throws for more complex types.

### Built-in Constants
All built-in constants can be replicated as follows:
```
ZERO_ADDRESS: address = empty(address)
EMPTY_BYTES32: bytes32 = empty(bytes32)
MAX_INT128: int128 = max_value(int128)
MIN_INT128: int128 = min_value(int128)
MAX_DECIMAL: decimal = max_value(decimal)
MIN_DECIMAL: decimal = min_value(decimal)
MAX_UINT256: uint256 = max_value(uint256)
MIN_UINT256: uint256 = min_value(uint256)  # Same as empty(uint256)
```

## Backwards Compatibility
Removes built-in constants

## Dependencies
No dependencies

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

---

EDIT: Modified `min` and `max` to `min_value` and `max_value`

**Comment by charles-cooper** [comment]
great VIP!

**Comment by iamdefinitelyahuman** [comment]
I like the functionality but I'm not a fan of the names. Vyper already uses `min` and `max` as arithmetic functions returning the lower or higher of two numeric values. As described, this VIP will give these functions two completely different functionalities depending on the input(s) given.

Is there another set of function names that are just as descriptive and not already in use?

**Comment by fubuloubu** [comment]
We can just do `min_value(type)` and `max_value(type)`, which are much more descriptive

**Comment by iamdefinitelyahuman** [comment]
:+1: for `min_value` and `max_value`
