### ISSUE TITLE
Vyper is not using staticcall for precompiles

### ISSUE THREAD

**Issue by axic** [vyperlang/vyper#1929]
I have noticed that the compiler is still emitting the `call` opcode in conjunction to precompiles:
- [sha256](https://github.com/vyperlang/vyper/blob/master/vyper/functions/functions.py#L319)
- [ecrecover](https://github.com/vyperlang/vyper/blob/master/vyper/functions/functions.py#L438)
- [ecadd](https://github.com/vyperlang/vyper/blob/master/vyper/functions/functions.py#L459)
- [ecmul](https://github.com/vyperlang/vyper/blob/master/vyper/functions/functions.py#L476)

Is there a reason for this?

It also means contracts can't make use of potential reductions of the cost of `staticcall`, if they were to happen.

**Comment by fubuloubu** [comment]
Good call. We missed these when we added support for `STATICCALL`
