### ISSUE TITLE
Remove 'swap' from the list of reserved keywords

### ISSUE THREAD

**Issue by gonchs** [vyperlang/vyper#1938]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b17+commit.0671b7b
* OS: osx
* Using docker

### What's your issue about?

I need to call a function called "swap" on an external contract from the Vyper code. When I try to define the interface, I get an error: "Function name invalid. swap is a reserved keyword (Vyper language)".

`SWAP` is an opcode. But does it need to be a reserved keyword? Is it [used for anything](https://github.com/vyperlang/vyper/search?q=swap&unscoped_q=swap)?

### How can it be fixed?

Remove "swap" from the list of reserved keywords.

**Comment by fubuloubu** [comment]
We're definitely being a little overzealous with the naming
