### ISSUE TITLE
Private function declarations in interfaces

### ISSUE THREAD

**Issue by cbraem** [vyperlang/vyper#1951]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b17+commit.0671b7b
* OS: osx
* Python Version (output of `python --version`): Python 3.6.10 :: Anaconda, Inc.
* Environment (output of `pip freeze`):
  * asttokens==2.0.3
  * certifi==2020.4.5.1
  * pycryptodome==3.9.7
  * six==1.14.0
  * vyper==0.1.0b17

### What's your issue about?

Private function declarations can be made in interfaces. For example the following interface is apparently valid.

```python
# interface.vy

@private
def foo():
    pass
```

I assume vyper ignores all private function decelerations of interfaces. It can apparently successfully compile the following _implements.vy_ contract with the _interface.vy_ as interface.

```python
# interface.vy

@private
def foo():
    pass

@public
def foo():
    pass
```

```python
# implements.vy

from . import interface

implements: interface

@public
def foo():
    pass
```

#### Expected Behavior
From my perspective, vyper should complain that _interface.vy_ is not a valid interface.

**Comment by fubuloubu** [comment]
I agree that this behavior makes sense. An interface file should _only_ contain a public interface

**Comment by iamdefinitelyahuman** [comment]
The issue here is that we allow vyper contracts to be used as interfaces.  So it's not straightforward to differentiate.

We could scan the maybe-interface and if all the functions only include `pass` in the body - then raise if there are illegal elements present?  Or introduce the ellipsis node to be used _only_ in interfaces:

```python
@external
def foo():
    ...
```

**Comment by iamdefinitelyahuman** [comment]
Thinking about this in relation to #1944.  If we're going to introduce `.vyi` as a suffix to differentiate interfaces, we can apply a different, much simpler type checking pattern to them.  I think the only valid items in an interface should be:

* external function definitions with an ellipsis body
* event definitions
* public storage variables
* struct definitions

**Comment by charles-cooper** [comment]
this is correctly rejected as of c6f457a73db40e4b113497883bd330e0dcec28d1 with
```
vyper.exceptions.StructureException: Internal functions in `.vyi` files are not allowed!

  contract "tmp/ifoo.vyi:6", line 6:0 
       5 @internal
  ---> 6 def bar():
  -------^
       7     ...
```
