### ISSUE TITLE
Type conversion with decimals

### ISSUE THREAD

**Issue by cbraem** [vyperlang/vyper#1957]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b17+commit.0671b7b
* OS: osx
* Python Version (output of `python --version`): Python 3.6.10 :: Anaconda, Inc.
* Environment (output of `pip freeze`):
  * asttokens==2.0.3
  * certifi==2020.4.5.1
  * pycryptodome==3.9.7
  * six==1.14.0
  * vyper==0.1.0b17

### What's your issue about?

According to the documentation, no type conversion is made implicitly. Therefore, it is very natural that `l1: decimal = 0` gets rejected since the integer literal is not compatible with the decimal type.

But if an Assign is used instead of an AnnAssign or an AugAssign vyper does not complain. Additionally, the error message using an invalid AugAssign is less informative than the one of the invalid AnnAssign.

```python
# accepted code
@public
def foo():
    l1: decimal = 0.0
    l1 = 42
```

```python
# rejected code with the following error message
# Error compiling: test.vy
# vyper.exceptions.TypeMismatch: line 11:4 Invalid type int128, expected: decimal
#      2 def foo():
# ---> 3     l1: decimal = 0
# ------------^
#      4

@public
def foo():
    l1: decimal = 0
```

```python
# rejected code with the following error message
# Error compiling: test.vy
# vyper.exceptions.TypeMismatch: <exception str() failed>

@public
def foo():
    l1: decimal = 0.0
    l1 += 42
```

#### Expected Behavior

All three contracts should get rejected and a correct error message should be generated (like in the example with the invalid AnnAssign).

**Comment by iamdefinitelyahuman** [comment]
Fixed in #2029

```python
vyper.exceptions.InvalidType: Expected decimal but literal can only be cast as int128 or uint256
           function 'foo', line 5:9 
                4     l1: decimal = 0.0
           ---> 5     l1 = 42
           ----------------^
```
