### ISSUE TITLE
Interfaces allow duplicate definitions

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1959]
### Version Information
* vyper Version (output of `vyper --version`): 0.1.0-beta.17

### What's your issue about?
This is apparently allowed...

`bar.vy`:
```python
@public
def bar():
    pass

@public
def bar():
    pass
```

`foo.vy`:
```python
import bar as Bar

bar: Bar
```

### How can it be fixed?
Make it so duplicates are caught when importing interfaces

**Comment by fubuloubu** [comment]
Note: This should be fixed by type checking

**Comment by iamdefinitelyahuman** [comment]
Related to #1951
