### ISSUE TITLE
VIP: Change Mapping Syntax (again)

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#1969]
## Simple Summary
Change mapping syntax from `var: map(key_type, val_type)` to `var: HashMap[key_type, val_type]`

## Motivation
Mapping syntax was changed in #564. While it made for easier understanding of how mappings work in practice, it precludes the use of the Python standard function `map(fn, iter) -> iter` for anything in Vyper to use. We propose adopting a MyPy-like type structure, which will make working with mappings (and nested mappings) more apparent, and open up the keyword `map` to future use as an iterator operation.

## Specification
The syntax for mappings would change from `var: map(key_type, val_type)` to `var: HashMap[key_type, val_type]`. This looks like the following in practice:
```python
struct MyStruct: ...

my_mapping: HashMap[uint256, MyStruct]

my_nested_map: HashMap[bytes32, HashMap[uint256, address]]

@public
def foo():
    self.my_mapping[1] = MyStruct({...})  # Same access as before
    self.my_nested_map[blk.hash][1] = msg.sender  # Same access as before
```

## Backwards Compatibility
This VIP will break the current syntax for defining mappings

## Dependencies
Depends on #564

## References
No references

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by howardpen9** [comment]
![image](https://user-images.githubusercontent.com/36764495/92538151-87fd3a00-f270-11ea-9ecb-6e98d3bb3302.png)

**Comment by howardpen9** [comment]
ok, then I know the reason why the code on this Sep 2019's paper couldn't work...

Thanks for the updated.
