### ISSUE TITLE
Fixed size lists with size > 2 ** 256

### ISSUE THREAD

**Issue by cbraem** [vyperlang/vyper#1970]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b17+commit.0671b7b
* OS: osx
* Python Version (output of `python --version`): Python 3.6.10 :: Anaconda, Inc.
* Environment (output of `pip freeze`):
  * asttokens==2.0.3
  * certifi==2020.4.5.1
  * pycryptodome==3.9.7
  * six==1.14.0
  * vyper==0.1.0b17

### What's your issue about?
Apparently one can define fixed size lists with a size greater than 2 ** 256. And as long the list is just accessed with integer literals, vyper accepts the contracts like the following contract.

```python
# test1.vy (accepted)

# List with more elements than (2 ** 256)
t: int128[200000000000000000000000000000000000000000000000000000000000000000000000000000]

@public
def foo() -> int128:
    return self.t[0]
```

If one accesses the list with a variable, vyper complains (correctly) that the size is too large. The following contract gets rejected.

```python
# test2.vy (rejected)

# List with more elements than (2 ** 256)
t: int128[200000000000000000000000000000000000000000000000000000000000000000000000000000]

@public
def foo(a: uint256) -> int128:
    return self.t[a]
```

#### Access the (2 ** 256)-th element
In addition, one can access the (2 ** 256)-th element of a list with a size > 2 ** 256 , but this number would be too large to store in any variable. The following contract gets accepted by vyper.

```python
# test3.vy (accepted)

# List with more elements than (2 ** 256)
t: int128[200000000000000000000000000000000000000000000000000000000000000000000000000000]

@public
def foo() -> int128:
    # Access (2 ** 256)-th element
    return self.t[115792089237316195423570985008687907853269984665640564039457584007913129639936]
```

But if one would access the (2 ** 256 + 1)-th element, vyper complains, that (2 ** 256 + 1) is too large. Therefore, the following contract gets rejected.
```python
# test4.vy (rejected)

# List with more elements than (2 ** 256)
t: int128[200000000000000000000000000000000000000000000000000000000000000000000000000000]

@public
def foo() -> int128:
    # Access (2 ** 256 + 1)-th element
    return self.t[115792089237316195423570985008687907853269984665640564039457584007913129639937]
```

#### Expected Behavior
vyper should reject all integer literals greater than 2 ** 256 as the size of fixed sized list. In addition, vyper should reject integer literals greater than or equal to 2 ** 256 as an index of a list look up.

**Comment by fubuloubu** [comment]
To paraphrase, this looks like an off-by-1 error?

**Comment by cbraem** [comment]
This issue is mainly about the fact that one can declare lists with a size > (2 ** 256). This is not an off-by-1 error.

The addition to this issue, about using integer literals to access elements of a list, is an off-by-1 error.

**Comment by iamdefinitelyahuman** [comment]
This is now blocked at compile time by #2029
