### ISSUE TITLE
VIP: Make the type argument in method_id optional

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1980]
## Simple Summary
`method_id`'s second argument (the output type) should be optional with a default of `bytes[4]`.

## Motivation
* Generating a 4 byte function selector is by far the most common use-case for this method
* The 32 byte flavor is just as easily achieved using `keccak256`

## Specification
```python
method_id(method, output_type=bytes[4]) → Union[bytes[4], bytes32]
```

`output_type` may still be given as a positional arg so that this is not a breaking change.

## Backwards Compatibility
No issues.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
I was thinking to remove `output_type` entirely, and figure out `bytes[4]` or `bytes32` based on context (calls or events)

**Comment by iamdefinitelyahuman** [comment]
That sounds pretty magical.

**Comment by fubuloubu** [comment]
Not really, it should be obvious because it is only useful as `bytes[4]` for calls, and only useful as `bytes32` for events. I don't think the user needs to know this detail.
