### ISSUE TITLE
Error strings are zero-padded to 32 bytes

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1981]
### What's your issue about?
Vyper zero-pads error strings to 32 bytes within the bytecode. This in turn causes the string to occupy an additional memory slot, and can lead to [decoding weirdness](https://etherscan.io/tx/0xa0f0aa5fc4f56771a0b49ff66c752bcad2a32844ec4b173337086d6610571d65).

Here is an example contract:

```python
@public
def foo():
    raise "foo"
```

Here is the bytecode that handles the error string:

```python
PUSH4 0x8C379A0   # error string signature
PUSH2 0x140
MSTORE
PUSH1 0x20
PUSH2 0x160
MSTORE
PUSH1 0x3
PUSH2 0x180
MSTORE
PUSH32 0x666F6F00000000000000000000000000000  # "foo" with many trailing zeros
PUSH2 0x1A0
MSTORE 
PUSH2 0x180
POP
PUSH1 0x0
PUSH2 0x15
JUMPI
PUSH1 0x84  # returns 4 memory slots
PUSH2 0x15C
REVERT
```

### How can it be fixed?
Remove the zero-padding and use `PUSH[n]` where `n` is the actual length of the encoded string. This way we can also reduce the size in memory that we are returning.

**Comment by ZumZoom** [comment]
I believe PUSH32 is required as MSTORE stores the whole word into memory.

Current code stores following data in memory starting from offset 0x15C:
```
8C379A0  # error signature
0000000000000000000000000000000000000000000000000000000000000020  # text offset
0000000000000000000000000000000000000000000000000000000000000003  # text length
666F6F0000000000000000000000000000000000000000000000000000000000  #  error text
||||||
3 bytes with meaningful data
```

Changing PUSH32 to PUSH3 will result in string consisting of 3 zeros:
```
8C379A0  # error signature
0000000000000000000000000000000000000000000000000000000000000020  # text offset
0000000000000000000000000000000000000000000000000000000000000003  # text length
0000000000000000000000000000000000000000000000000000000000666F6F  # error text
||||||
3 bytes with meaningful data
```

I believe that it is not PUSH32 that is responsible for the extra rubbish at the end of revert string but erroneous computation of revert length. See #1982.
