### ISSUE TITLE
VIP: Use uint256 for public array getters

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1983]
## Simple Summary
When an array is declared public, the generated getter should accept `uint256` instead of `int128` in order to handle the lookups.

## Motivation
We do not allow array lookups with negative numbers, so the use of `int128` is unintuitive.

## Specification
As an example, the following variable:

```python
foo: public(address[3])
```

Should produce a getter with the following signature:

```python
def foo(arg0: uint256) -> address: constant
```

## Backwards Compatibility
This is not a breaking change, but it does amount to a deviation in expected behavior.

## Dependencies
Not dependent, but related to #1979 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
It actually is a breaking change, because it changes the Method ID of the getter function. I think this is a good thing though, as it will match the Solidity implementation.

**Comment by iamdefinitelyahuman** [comment]
Ahh, I forgot about interfaces we generate from other contracts.  Was thinking it wasn't breaking since it would only affect newly compiled contracts. Good call.
