### ISSUE TITLE
'make' failed

### ISSUE THREAD

**Issue by johnda98** [vyperlang/vyper#1991]
all smooth on 160.04 packages and install until

johnda@ymirjda:~/vyper-venv/vyper$ make 
install .
install: missing destination file operand after '.'
Try 'install --help' for more information.
Makefile:12: recipe for target 'init' failed
make: *** [init] Error 1

was following to the letter the Docs

"git clone https://github.com/vyperlang/vyper.git
cd vyper
make
make dev-deps
make test"

**Comment by fubuloubu** [comment]
Really need to get rid of the Makefile, but it appears it's not recognizing `pip`. What happens when you do `pip install .`?

**Comment by johnda98** [comment]
gone back to .sol for now
