### ISSUE TITLE
Source map only available for runtime bytecode

### ISSUE THREAD

**Issue by Pet3ris** [vyperlang/vyper#1998]
### Version Information

* vyper Version (output of `vyper --version`): `latest`

### What's your issue about?

Vyper `source_map` argument currently only provides the runtime contract source map by default. In order to fully support debuggers, it would be helpful to have source maps also for deployable bytecode, just like Solidity.

### How can it be fixed?

-

**Comment by charles-cooper** [comment]
we should do this. i'm adding to the v0.4.0 mileston so i don't forget (it might get pushed to 0.4.1 though)
