### ISSUE TITLE
auction example does not compile

### ISSUE THREAD

**Issue by benjyz** [vyperlang/vyper#2000]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b17+commit.0671b7b

### Error
```
Error compiling: examples/auctions/simple_open_auction.vy
vyper.exceptions.TypeMismatch: line 25:4 Typecasting from base type uint256(sec, positional) to uint256 unavailable
```

**Comment by iamdefinitelyahuman** [comment]
Are you pulling the example from the latest commit on master?  We've pushed quite a few breaking changes since `0.1.0b17` so that could be the issue.

https://github.com/vyperlang/vyper/blob/0671b7bbb21f40435b73aafbe7f5bd0b8475f0eb/examples/auctions/simple_open_auction.vy

That example should work.
