### ISSUE TITLE
VIP: Rename @constant decorator to @view

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2040]
## Simple Summary
Change the `@constant` decorator to `@view` for methods

## Motivation
To be consistent with the ABI `stateMutability` field, we should use the term `view` instead of `constant` when decorating a method

## Specification
Contracts and Vyper interfaces should be specified using the following syntax to denote a method that does not modify state:
```python
@view
@public
def getSender() -> address:
    return msg.sender
```

## Backwards Compatibility
Breaks backwards compatibility because of a name change.

## Dependencies
No dependencies

## References
-  #1931
- https://solidity.readthedocs.io/en/latest/abi-spec.html#json

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by iamdefinitelyahuman** [comment]
Violent agreement!
