### ISSUE TITLE
Reorganize and refactor the test suite

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#2056]
## How it works now
Tests are disorganized and sometimes duplicated.  We have a lot of coverage but it can be hard to know where something is tested, or where to place a new test.

## How it could be refactored
Organize tests into three base directories.

* `functional`: Unit tests. Designed to execute quickly so they can be run locally in a matter of seconds.
* `fuzzing`: Hypothesis tests. Can be very slow as they're meant to run in the CI.
* `integration`: Large-scale tests that verify interactions across multiple components or the entire compiler process.  The majority of our test suite currently belongs in this category.

We should also add a readme in `tests/` to explain the structure to new contributors.

## Why this is an improvement

* With this structure we can split up how the CI runs and remove the need for the `fuzzing` marker. 
* It becomes very obvious which tests are new, and which are old. We can slowly migrate the old tests into these folders as we clean them up, and remove redundant test cases

**Comment by fubuloubu** [comment]
An idea: we have a bunch of compilation test cases that either fail with a compiler exception or pass, and _maybe_ we do some simple checks. *What if* we used a TOML format for this? Like:
```toml
type: failure
exception: StructureException
source: |
  @public
  def foo
```

**Comment by fubuloubu** [comment]
Could use something like this to construct a test suite out of source files:
https://docs.pytest.org/en/stable/example/nonpython.html#yaml-plugin

`tests/.../no_function_name_raises_SyntaxError.vy`:
```python
@external
def ():
    pass  # Should fail w/ `SyntaxError` because no function name
```

**Comment by charles-cooper** [comment]
closed as of https://github.com/vyperlang/vyper/pull/3664 -- two main directory structures now, although i used the names `unit/` (the proposed `functional/` directory) and `functional/` (the proposed `integration/` directory). there are also `fixtures/` (common test fixtures) and `util/` (pure utility functions for tests) as well, maybe introduced a few commits later.
