### ISSUE TITLE
Refactor out the signatures subpackage

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#2062]
> Note: will try refactoring out `vyper/signature` in favor of adding `ContractFunctionType.to_abi` ABI serializer, and replacing all uses of `vyper/signature` in `vyper/parser` in another PR (see https://github.com/fubuloubu/vyper/tree/refactor/abi-serializer)

_Originally posted by @fubuloubu in https://github.com/vyperlang/vyper/pull/2054#issuecomment-650682785_

## How it works now
`vyper/signatures` handles the creation of signatures for functions and events, and generates the ABI. This logic is all fairly dependent upon `GlobalContext`.

## How it could be refactored
This logic could be moved into methods within `ContractFunction` and `Event` in the new `vyper/context` subpackage.  The use of `GlobalContext` can be replaced with `Namespace`.

## Why this is an improvement
* This is a good first step toward removing `GlobalContext`
* It allows us to remove the requirement that functions only call upward (this is happening in `signatures/function_signature.py`)
* It's a good first step in feeling out how well `Namespace` fits where `GlobalContext` used to be

**Comment by fubuloubu** [comment]
To note: We shouldn't need `Namespace` in order to create the ABI. It's only really needed for refactoring what `parser/` needs

**Comment by iamdefinitelyahuman** [comment]
Some of the stuff in `signature/` touches `GlobalContext` so I think we will need `Namespace` somewhere in this refactor.

**Comment by iamdefinitelyahuman** [comment]
I think completing this refactor will also make #1944 trivial to implement.

**Comment by charles-cooper** [comment]
this was completed as of #3209  and #3390
