### ISSUE TITLE
Remove Bumpversion

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2086]
`bumpversion` is deprecated, and we don't really use it for much anyways. If [new way of releasing](https://github.com/vyperlang/vyper/pull/2082#discussion_r449640465) works, we should remove `bumpversion` from deps and `setup.cfg`, move the version to `vyper/__init__`, and have `setup.py` grab `__version__` directly from the package.

Then set up CI tests that this value only changes on a `release/*` branch, and that the version matches the branch name (and ideally that the old version < the new version).

Better yet, find a way to have GitHub automatically make this change based on the branch name and we'll be in business for automagic releases!

**Comment by charles-cooper** [comment]
i think this was done in #2353
