### ISSUE TITLE
empty(Bytes[1024]) causes vyper.exceptions.CompilerPanic: Unsupported location: None

### ISSUE THREAD

**Issue by or2008** [vyperlang/vyper#2112]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.3+commit.006968f
* OS: Osx

I am trying to mimic solidity's `new bytes(0)`

and looks like `empty(Bytes[1024])` causes this exception:

vyper.exceptions.CompilerPanic: Unsupported location: None Please create an issue.vyper.exceptions.CompilerPanic: Unsupported location: None Please create an issue.

using `b''` works great, I wonder, is there a significant gas diff between using `b''` and `empty(Bytes[1024])`?

**Comment by fubuloubu** [comment]
I tried this and it seemed to work just fine, can you give the full source code of a Minimal Working Example (MWE) that is giving you problems?

Example:
```python
@external 
def foo(): 
    b: Bytes[1024] = empty(Bytes[1024]) 
```

Also, yes `b''` and `empty(Bytes[1024])` should work interchangeably.

**Comment by or2008** [comment]
your code works fine, I see the problem, in my code, I passed `empty(Bytes[1024]` as a function argument

```py
from vyper.interfaces import ERC20

interface UniswapV2Pair:
    def swap(amount_0_out: uint256, amount_1_out: uint256, to: address, data: Bytes[1024]): nonpayable

@external
def foo():
    UniswapV2Pair(ZERO_ADDRESS).swap(1, 1, ZERO_ADDRESS, empty(Bytes[1024]))
```

**Comment by fubuloubu** [comment]
Yeah, in that situation you would use `b""`. If that works for you, that's great!

They should be interchangeable even then though, in fact `empty(Bytes[1024])` is somewhat more efficient as it leverages empty calldata instead of creating new memory. I was talking with @iamdefinitelyahuman and it seems like this may still be a bug.

Also, glad to see you're able to work with UniSwap V2!

**Comment by iamdefinitelyahuman** [comment]
Yes, this looks like a bug.  It should be possible to use `empty` without an assignment.
