### ISSUE TITLE
Vyper can't handle folding to a decimal type

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2122]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.3
* OS: linux
* Python Version (output of `python --version`): 3.8.4

### What's your issue about?
```
InvalidType: Expected decimal but literal can only be cast as int128 or uint256
contract "contracts/RateOracle.vy", function "__init__", line 83:22 
     82     self.base = ERC20(_base)
---> 83     self.riskFactor = 2 / 100  # 2%
------------------------------^
     84     self.reward = 10 ** 17
```

### How can it be fixed?
Whole numbers are still valid decimal types.

**Comment by iamdefinitelyahuman** [comment]
This is actually a [documented behavior](https://vyper.readthedocs.io/en/stable/types.html#id8). Whole numbers are integers, if you want to use those values as decimals they should be written as `2.0 / 100.0`.

If whole numbers can be interpreted as both decimals and integers, your specific example is just as likely to fold to `0` as `0.02`.  The only way to know which is the correct folding is to first type check and determine what `riskFactor` is. It also adds further ambiguity to literal arrays (`[1, 2, 3]` can now be three types), and weirdness such as:

```
foo: decimal = 100
bar: int128 = 2

foo / 2
100 / bar
foo / bar
```

The above example would raise a type mismatch at `foo / bar`, but given the previous two lines are ok, this feels like a strange outcome.
