### ISSUE TITLE
Auction example should leverage `self.auctionStart` for "future" auctions

### ISSUE THREAD

**Issue by rayrrr** [vyperlang/vyper#2124]
### What's your issue about?

Let's say I want to make sure my auction starts at exactly 11PM UTC tomorrow. Following the example at https://github.com/vyperlang/vyper/blob/v0.2.3/examples/auctions/simple_open_auction.vy it seems I would have to be poised to deploy my smart contract to the EVM at roughly 10:59PM UTC tomorrow (plus/minus my best estimate of how long it will take for my smart contract to be "accepted"). I would rather deploy it in advance and know that it is sitting there waiting to be activated at an exact moment.

### How can it be fixed?

The example code does instantiate a `self.auctionStart` variable, but it appears to be unused. Shouldn't the `bid()` function in the example be checking that the bid is _between_ the start and end times? It currently just checks that it is before the end time. Otherwise it seems if I deploy my auction contract in advance following the example, bids can be submitted before the intended start time. Am I missing something?

**Comment by fubuloubu** [comment]
Yup, that would indeed be a design choice that would make sense. We usually aim for our examples to be a minimal enough implementation of a specific idea, but adding this little bit of functionality would be a little bit more user friendly, as you demonstrate.

I would happily merge a PR with this fix and updated tests if you wanted to do that.

**Comment by rayrrr** [comment]
@fubuloubu thank you and yes please! Happy to review that upcoming simple PR.

**Comment by tacitvenom** [comment]
Is this still something that needs to be done? I would like to have a look.

**Comment by rayrrr** [comment]
@tacitvenom I gave it a try recently but then realized that this work should also involve updating not only the tests but also the example in the docs as well as the code itself and I didn't have the bandwidth. You are welcome to give it a go.
