### ISSUE TITLE
Production ready now?

### ISSUE THREAD

**Issue by davidsmiles** [vyperlang/vyper#2129]
Quite invested in vyper now and want to know if I shouldn't waste my time any more and just use Solidity.

**Comment by fubuloubu** [comment]
Vyper is a younger language, with much less diligence from external auditors and less money in contracts on Mainnet. That being said, it has been used to secure both UniSwap V1 and Curve. You should be able to draw your own conclusions and figure out if that risk tolerance is acceptable for your project.

You can watch our progress towards a fully audited V1 here: https://github.com/vyperlang/vyper/projects/6

Closing this issue for now.
