### ISSUE TITLE
error with python librairies

### ISSUE THREAD

**Issue by jordan69420** [vyperlang/vyper#2148]
when I tried to import the library web3 I got the error "Cannot locate interface 'web3/Web3{.vy,.json}'"
I do not know how to fix this, however it is of critical importance that this is fixed.
do I need to write a .json file?
is this a problem with the compiler?
how can this be fixed?

**Comment by jacqueswww** [comment]
I am not sure what the problem is; but vyper only supports JSON and Vyper interfaces https://vyper.readthedocs.io/en/stable/interfaces.html#importing-interfaces

Web3 is a python library not a vyper library.

**Comment by fubuloubu** [comment]
You can access the web3 repo here: github.com/ethereum/web3.py
