### ISSUE TITLE
Add a warning when exceeding the EIP-170 Contract Size Limit

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2150]
Right now, there is no indication that the contract size limit (`2**14 + 2**13 = 24576 bytes`) is exceeded when compiling a contract.

I would suggest raising a warning when this happens, because an error may be just as confusing for newcomers, and it's important to know if the contract is compile-able at all. The warning should also give suggestions about how to fix the problem (reducing interactions in the constructor, reducing state variables, breaking apart contracts, etc.)

As an additional aid, we could also raise this warning if you are within 5% of the limit, so that the user is aware for further iterations on a contract that limited space is left.

**Comment by howardpen9** [comment]
Yes, overflow problem is important!
