### ISSUE TITLE
Remove Gas Estimates from ABI

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2151]
https://twitter.com/_prestwich/status/1304986329604710401?s=20

Basically, since gas costs change all the time, we can't rely on the estimates that a particular version of Vyper uses. So, we should just get rid of this "feature"

NOTE: we'll still keep an upper bound on gas usage, for use with optimizations and to prevent gas attacks

**Comment by bitcoinbrisbane** [comment]
I'd like to take a swing at this...

**Comment by bitcoinbrisbane** [comment]
Should be as simple as removing this guy?  https://github.com/vyperlang/vyper/blob/master/vyper/compiler/output.py#L56

**Comment by fubuloubu** [comment]
@bitcoinbrisbane it should be that easy, yes! But if you could also try to remove that functionality from the rest of the codebase and the test suite, that'd seal the deal!

**Comment by bitcoinbrisbane** [comment]
> @bitcoinbrisbane it should be that easy, yes! But if you could also try to remove that functionality from the rest of the codebase and the test suite, that'd seal the deal!

On it

**Comment by bitcoinbrisbane** [comment]
43 tests break after removing it, taking a bit of time to refactor those tests.

**Comment by Alec1017** [comment]
Hey @bitcoinbrisbane, just curious of there were any updates on the progress of this issue so far?

**Comment by bitcoinbrisbane** [comment]
Not good, I got stuck on refactoring the unit tests. I was just thinking about this ticket on the weekend. Can I try again this weekend?

**Comment by charles-cooper** [comment]
@bitcoinbrisbane I can help or take over this issue, if you want

**Comment by bitcoinbrisbane** [comment]
Sounds good. I need to get back into compilers
