### ISSUE TITLE
The returned struct value from the external call does get stored properly

### ISSUE THREAD

**Issue by saikat041** [vyperlang/vyper#2155]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.4+commit.3eb9e7a
* OS: linux
* Python Version (output of `python --version`): Python 3.6.9

### What's your issue about?
The returned struct value from the external call does get stored properly. It seems that the problem is due to abi decoding.
```
def test_bytes_inside_tuple(get_contract):
    code = """
struct Person:
    name: String[6]
    age: uint256

@external
def test_return() -> Person:
    return Person({name: "abc", age: 42 })
    """
    c1 = get_contract(code)

    code = """
struct Person:
    name: String[6]
    age: uint256

interface jsonabi:
    def test_return() -> Person: view

@external
def test_values(a: address) -> String[6]:
    p: Person = jsonabi(a).test_return()
    return p.name
    """

    c2 = get_contract(code)
    assert c2.test_values(c1.address) == "abc"
```

The above test case fails

### How can it be fixed?

I have found the cause and I am working on it

**Comment by fubuloubu** [comment]
Good find! Thank you for taking a stab at it

**Comment by saikat041** [comment]
Hey @fubuloubu
https://github.com/vyperlang/vyper/blob/c173ba72e78ba348c204053839c2ddfc866490a1/vyper/codegen/return_.py#L67


 Here we are returning abi-encoded value even for internal function return. I think we should not encode return value when we returning from internal functions.  If we don't encode return value then we don't have to decode using this complex algorithm here,
https://github.com/vyperlang/vyper/blob/c173ba72e78ba348c204053839c2ddfc866490a1/vyper/parser/self_call.py#L193

We should only encode return value for external functions.
