### ISSUE TITLE
Constant arrays cannot be indexed with variables

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#2156]
### Version Information

* vyper Version: `0.2.4`
* OS: linux
* Python Version: `3.8.5`

### What's your issue about?
Attempting to use a variable to access a value within a constant array fails to compile. For example, the following code:

```python
BAR: constant(bool[3]) = [False, False, True]

@external
def foo(i: uint256):
    a: bool = BAR[i]

```

produces the following exception:

```python
  File "/home/computer/code/python/vyper/vyper/parser/expr.py", line 967, in parse_variable_location
    raise StructureException("Looking for a variable location, instead got a value", expr)
vyper.exceptions.StructureException: Looking for a variable location, instead got a value
```

### How can it be fixed?
¯\\\_(ツ)\_/¯ The issue is somewhere in `vyper.parser`, I think it will be fairly straightforward but I haven't had a chance to look yet.

**Comment by charles-cooper** [comment]
For now the appropriate workaround is
```python
BAR: constant(bool[3]) = [False, False, True]

@external
def foo(i: uint256):
    a0: bool[3] = BAR
    a: bool = a0[i]
```
