### ISSUE TITLE
unhelpful error message with mismatched parens

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2161]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.4
* OS: linux
* Python Version (output of `python --version`): 3.8.5

### What's your issue about?
I had a program where I left and extra left paren in `)`, and it caused this bug:
```
vyper.exceptions.SyntaxException: EOF in multi-line statement                                                                            
  line 180:0                                                                                                                             
       179     self.transfer(_strategy, _startingCapital)                                                                                
  ---> 180                                                                                                                               
  ---------^             
```

### How can it be fixed?
Can only really be solved with a custom parser, or completely refactoring the tokenizer

**Comment by charles-cooper** [comment]
closing in favor of report with newer vyper version: https://github.com/vyperlang/vyper/issues/2763
