### ISSUE TITLE
Incorrect output while passing multi-dimensional array as argument

### ISSUE THREAD

**Issue by saikat041** [vyperlang/vyper#2183]
### Version Information

* vyper Version: 0.2.4+commit.14327e9
* OS: linux
* Python Version: 3.6.9

### What's your issue about?
When we pass a multi-dimensional array like [[1, 2]] as an argument to internal/external functions we get incorrect output.
The following test case fails:
```
def test_multiple_dim_array_as_argument(get_contract):
    code = """
@internal
def test_input(arr: int128[2][1], i: int128) -> (int128[2][1], int128):
    return arr, i

@external
def test_values(arr: int128[2][1], i: int128) -> (int128[2][1], int128):
    return self.test_input(arr, i)
    """

    c = get_contract(code)
    assert c.test_values([[1, 2]], 3) == [[[1, 2]], 3]
```

### How can it be fixed?
Working on it

**Comment by fubuloubu** [comment]
Good find!
