### ISSUE TITLE
Limitations on dynamically-sized structs

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#2190]
Structs containing dynamically sized types (string, bytes) are not fully supported in vyper.

The following actions fail to compile and produce exceptions that are not immediately obvious:

* An argument in an external function call
* An argument in an internal function call
* An input argument for function - but only if you attempt to access the dynamically sized data

The following actions _are_ supported:

* returning from an internal function
* returning from an external function

As a temporary measure I've added a better exception during type checking (https://github.com/vyperlang/vyper/pull/2189). It covers all of the not-possible cases given above.  Going forward though, I think we should add support for these structs in the places where they aren't working.

**Comment by vasa-develop** [comment]
How difficult is it to add support for these cases? (In case I would take a stab at this)

**Comment by fubuloubu** [comment]
@vasa-develop we have some of the building blocks in place (abi encoder), but it would be difficult to do this quickly without spending a lot of time in the codebase. Worth a shot if you have the time though, I know this is blocking you

**Comment by charles-cooper** [comment]
fixed in #2447
