### ISSUE TITLE
VIP: Add `SafeERC20` Internal Interface

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2202]
## Simple Summary
Add `SafeERC20` interface, that allows working with non-standard ERC20 tokens

## Motivation
When working with ERC20s, there are sometimes non-compliant implementations that are hard to work with. Adding an internal implementation that is a drop-in replacement for the normal `ERC20` interface, but uses the "Safe" versions of these calls for common variants would help users who want access to this functionality without having to code it themselves. This is common enough functionality that it should be supported.

## Specification
The new interface type `SafeERC20` is basically a `ERC20` interface, except it performs non-standard calls for `ERC20.transfer()` and `ERC20.transferFrom()` in order to handle different common scenarios. [OpenZeppelin](https://github.com/openzeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/SafeERC20.sol) has an implementation of this very library in common use in the ecosystem, with a Vyper-esque variant here:
https://ethereum.stackexchange.com/questions/84775/is-there-a-vyper-equivalent-to-openzeppelins-safeerc20-safetransfer/84776

Note that this "interface" can NOT be used with `implements`, and is only an option for those who need it (there will be some increased gas usage)

## Backwards Compatibility
Fully backwards compatible.

## Dependencies
No dependencies

## References
https://github.com/openzeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/SafeERC20.sol
https://ethereum.stackexchange.com/questions/84775/is-there-a-vyper-equivalent-to-openzeppelins-safeerc20-safetransfer/84776

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by Thrasymachus01** [comment]
So for approving, it would look like this?

```
def safeApprove(token: address, spender: address, value: uint256): bool {
    assert value == 0 or ERC20(token).allowance(self, spender) == 0,  "SafeERC20: approve from non-zero to non-zero allowance"
    _response: Bytes[32] = raw_call(
        token,
        concat(
            method_id("approve(address,uint256)"),
            convert(spender, bytes32),
            convert(value, bytes32)
        ),
        max_outsize=32
    )

    return True
}
```

**Comment by Thrasymachus01** [comment]
I've gone through the liberty of implementing a few of these:

```
@internal
def safeApprove(_token: address, _spender: address, _value: uint256) -> bool:
    assert _value == 0 or ERC20(_token).allowance(self, _spender) == 0, "SafeERC20: approve from non-zero to non-zero allowance"
    _response: Bytes[32] = raw_call(
        _token,
        concat(
            method_id("approve(address,uint256)"),
            convert(_spender, bytes32),
            convert(_value, bytes32)
        ),
        max_outsize=32
    )

    if len(_response) > 0:
        assert convert(_response, bool), "Token approval failed!"

    return True

@internal
def safeTransferFrom(_token: address, _from: address, _to: address, _value: uint256) -> bool:
    _response: Bytes[32] = raw_call(
        _token,
        concat(
            method_id("transferFrom(address,address,uint256)"),
            convert(_from, bytes32),
            convert(_to, bytes32),
            convert(_value, bytes32)
        ),
        max_outsize=32
    )

    if len(_response) > 0:
        assert convert(_response, bool), "Token transferFrom failed!"

    return True

@internal
def safeTransfer(_token: address, _to: address, _value: uint256) -> bool:
    _response: Bytes[32] = raw_call(
        _token,
        concat(
            method_id("transfer(address,uint256)"),
            convert(_to, bytes32),
            convert(_value, bytes32),
        ),
        max_outsize=32
    )

    if len(_response) > 0:
        assert convert(_response, bool), "Token transferFrom failed!"

    return True
```

**Comment by fubuloubu** [comment]
@Thrasymachus01 approvals aren't usually incorrectly implemented in most tokens (which is the point of the `SafeERC20` interface, to handle tokens that actually do not conform to the ERC20 spec), but if there is an example of one we can of course add it!

**Comment by Thrasymachus01** [comment]
The Tether (USDT) contract is an example.

**Comment by fubuloubu** [comment]
Ah, seems you are right! I would modify that slightly as follows:

```
@internal
def safeApprove(_token: address, _spender: address, _value: uint256) -> bool:
    _response: Bytes[32] = raw_call(
        _token,
        concat(
            method_id("approve(address,uint256)"),
            convert(_spender, bytes32),
            convert(_value, bytes32)
        ),
        max_outsize=32
    )

    if len(_response) > 0:
        assert convert(_response, bool), "Approval failed!"

    return True
```

**Comment by sabotagebeats** [comment]
@fubuloubu would this be a good opportunity to add erc20 metadata interface? 
https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#IERC20Metadata

**Comment by fubuloubu** [comment]
Can do that pretty easily IMO

**Comment by charles-cooper** [comment]
superseded by https://github.com/vyperlang/vyper/pull/2839, i think. @fubuloubu please reopen if there is still something to be implemented here.
