### ISSUE TITLE
Got "HashMap must be defined with a key type and a value type" error for HashMap type on Vyper with Python 3.9

### ISSUE THREAD

**Issue by arjunaskykok** [vyperlang/vyper#2206]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.7
* OS: osx
* Python Version (output of `python --version`): Python 3.9.0
* Environment (output of `pip freeze`):

asttokens==2.0.3
attrs==20.2.0
base58==2.0.1
bitarray==1.2.2
black-mamba==0.5.5
blake2b-py==0.1.3
cached-property==1.5.2
certifi==2020.6.20
chardet==3.0.4
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.4
eth-bloom==1.0.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.9.5
hexbytes==0.2.1
idna==2.10
iniconfig==1.1.1
ipfshttpclient==0.6.1
jsonschema==3.2.0
lru-dict==1.1.6
more-itertools==8.5.0
multiaddr==0.0.9
mypy-extensions==0.4.3
netaddr==0.8.0
packaging==20.4
parsimonious==0.8.1
pluggy==0.13.1
protobuf==3.13.0
py==1.9.0
py-ecc==4.1.0
py-evm==0.3.0a20
pycryptodome==3.9.8
pyethash==0.1.27
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.0.2
pytest-mock==3.3.1
requests==2.24.0
rlp==2.0.0
semantic-version==2.8.5
six==1.15.0
sortedcontainers==2.2.2
toml==0.10.1
toolz==0.11.1
trie==2.0.0a5
typing-extensions==3.7.4.3
urllib3==1.25.11
varint==1.0.2
vyper==0.2.7
web3==5.12.2
websockets==8.1

### What's your issue about?

Please include information like:

* full output of the error you received

This is the Vyper source code:

```python
x: HashMap[address, uint256]
```

This is the compilation output.

```bash
vyper.exceptions.StructureException: HashMap must be defined with a key type and a value type 
  contract "build/contracts", line 1:3
  ---> 1 x: HashMap[address, uint256]
  ----------^
       2
```

No problem with Python 3.8.5.

**Comment by alanwilhelm** [comment]
```
devo vyper token.vy
Error compiling: token.vy
vyper.exceptions.StructureException: HashMap must be defined with a key type and a value type
  contract "token.vy", line 17:23
       16 # Keep track of refunded bids so we can follow the withdraw pattern
  ---> 17 pendingReturns: public(HashMap[address, uint256])
  -------------------------------^
       18
```

**Comment by iamdefinitelyahuman** [comment]
Per #2182, Vyper doesn't yet support Python 3.9
