### ISSUE TITLE
Cannot use `in` comparator with literal uint256

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#2217]
### Version Information

* vyper Version (output of `vyper --version`): `0.2.7`
* Python Version (output of `python --version`): `3.8.5`

### What's your issue about?
Attempting to use the `in` comparator with a `uint256` array, where the test value is a literal that could also be interpreted as `int128`, raises a `CompilerPanic`:

```python
@external
def foo():
    a: uint256[2] = [1,2]
    if 0 in a:
        pass
```

The contract compiles if you change `0` to `2**127`.

### How can it be fixed?
There must be an assumption within `parser` that the literal is `int128` if it fits within the bounds.

**Comment by charles-cooper** [comment]
This appears fixed as of v0.3.0
