### ISSUE TITLE
Calldata variables cannot shadow storage variables

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#2219]
### What's your issue about?
In #2166 we removed the restriction re: name shadowing of memory variables and storage variables. This restriction should also be lifted for calldata variables.

### How can it be fixed?
Lift the restriction.

**Comment by fubuloubu** [comment]
So this allows overwriting function argument values? This could make sense in practice, but would require a memcpy first before the overwrite is allowed

**Comment by iamdefinitelyahuman** [comment]
Not overwriting, just shadowing.

Currently this is allowed:

```python
foo: uint256

@external
def bar():
    foo: bool = True
```

but this raises with a `NamespaceCollision`:

```python
foo: uint256

@external
def bar(foo: bool):
    pass
```
