### ISSUE TITLE
CompilerPanic caused by using String[64] directly as HashMap key

### ISSUE THREAD

**Issue by picked-a-username** [vyperlang/vyper#2237]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.7
* OS: OSX 10.15.6 (19G2021)
* Python Version (output of `python --version`): 3.6.8

### What's your issue about?

Full Error:

  >Error compiling: test.vy
  >vyper.exceptions.CompilerPanic: Number of arguments mismatched: add []
  >
  >This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
  >https://github.com/vyperlang/vyper/issues/new?template=bug.md

* what command you ran? `vyper test.vy`
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

```
struct Thing:
    name: String[64]

indexToThing: public(HashMap[uint256, Thing])
NameToStatus: public(HashMap[String[64], bool])

@external
def foo(_index: uint256):
    
    self.NameToStatus[self.indexToThing[_index].name] = True
    self.indexToThing[_index] = empty(Thing)
    
```

### Detailed steps to reproduce the issue
Save the code above as test.vy and run `vyper test.vy` to reproduce the issue.
### What was the result of the issue
The program failed to compile.
### What the expected behaviour is
It is expected to compile successfully.

### Temporary Fix

I stored `self.indexToThing[_index].name` in a variable and then used the variable as the key for self.NameToStatus instead of directly using `self.indexToThing[_index].name`
Working code:

```
struct Thing:
    name: String[64]

indexToThing: public(HashMap[uint256, Thing])
NameToStatus: public(HashMap[String[64], bool])


@external
def foo(_index: uint256):
    
    name: String[64] = self.indexToItem[_index].name
    self.NameToStatus[name] = True
    self.indexToThing[_index] = empty(Thing)

```

**Comment by iamdefinitelyahuman** [comment]
I took a closer look at this, seems you managed to find two bugs at once :)
