### ISSUE TITLE
Can't call an internal function from constructor

### ISSUE THREAD

**Issue by banteg** [vyperlang/vyper#2251]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.8
* OS: osx
* Python Version (output of `python --version`): 3.8.2
* Environment (output of `pip freeze`):

### What's your issue about?

```python
@internal
def initialize():
    ...

@external
def __init__():
    self.initialize()
```

```
Compiling contracts...
  Vyper version: 0.2.8
Unhandled exception in 'contracts/Vault.vy':
FunctionDeclarationException: Function not declared yet (reminder: functions cannot call functions later in code than themselves): initialize
```

### How can it be fixed?

Allow calling internal functions from constructor.

**Comment by fubuloubu** [comment]
Solution is to inline the internal method into the deployment constructor. This is useful for being able to deploy proxies

**Comment by charles-cooper** [comment]
I believe this is a dup of https://github.com/vyperlang/vyper/issues/1631
