### ISSUE TITLE
Multi-Line String on Top Level Gives Error

### ISSUE THREAD

**Issue by arjunaskykok** [vyperlang/vyper#2275]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.8+commit.01c8299
* OS: linux
* Python Version (output of `python --version`): Python 3.8.5
* Environment (output of `pip freeze`): 

apipkg==1.5
asttokens==2.0.4
attrs==20.3.0
base58==2.0.1
bitarray==1.2.2
blake2b-py==0.1.3
cached-property==1.5.2
certifi==2020.12.5
chardet==4.0.0
coverage==5.3.1
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.4
eth-bloom==1.0.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-tester==0.5.0b3
eth-typing==2.2.2
eth-utils==1.9.5
execnet==1.7.1
hexbytes==0.2.1
hypothesis==5.46.0
idna==2.10
iniconfig==1.1.1
ipfshttpclient==0.7.0a1
jsonschema==3.2.0
lark==0.11.1
lru-dict==1.1.6
multiaddr==0.0.9
mypy-extensions==0.4.3
netaddr==0.8.0
packaging==20.8
parsimonious==0.8.1
pluggy==0.13.1
protobuf==3.14.0
py==1.10.0
py-ecc==4.1.0
py-evm==0.3.0a20
pycryptodome==3.9.9
pyethash==0.1.27
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.2.1
pytest-cov==2.10.1
pytest-forked==1.3.0
pytest-xdist==2.2.0
requests==2.25.1
rlp==2.0.1
semantic-version==2.8.5
six==1.15.0
sortedcontainers==2.3.0
toml==0.10.2
toolz==0.11.1
trie==2.0.0a5
typing-extensions==3.7.4.3
urllib3==1.26.2
varint==1.0.2
vyper==0.2.8
web3==5.13.1
websockets==8.1

### What's your issue about?

This is a valid Python source code:

```python
"""
haha
haha
"""
class A:
    """
    haha
    haha
    """

    def a(self):
        pass
```

But this is not a valid Vyper source code:

```python
a: public(address)

"""
haha
haha
"""

@external
def __init__():
    pass
```

Compiling that file would give you this error:

```bash
Error compiling: /tmp/a.vy
vyper.exceptions.StructureException: Unsupported syntax for module namespace: Expr
  contract "/tmp/a.vy", line 3:0 
       2
  ---> 3 """
  -------^
       4 haha
```

You may think why it is so important to have multi-line string on top level. When working on Vyper source code, I sometimes comment out many methods with multi-line string to debug some issues. It's very convenient. I know, I know, I can use Vim Macro. But Vyper should mimic Python as much as possible, right?

**Comment by fubuloubu** [comment]
So, the top level NatSpec is using a multiline string, the assumption was that any multiline string at the top of the file is the top level NatSpec. This error message seems wrong though.

**Comment by arjunaskykok** [comment]
This is fine.

```
"""
haha
haha
"""

a: public(address)

@external
def __init__():
    pass
```

Nah, the question is what if I want to use a multi-line string as a way to comment out methods not as a NatSpec? Should Vyper have this feature?

**Comment by iamdefinitelyahuman** [comment]
The issue I see here is that a multi-line string technically isn't a comment - it's a string that isn't being assigned.  Vyper doesn't allow literals as top-level statements without assignment, so making an exception for this feels weird to me.

**Comment by arjunaskykok** [comment]
Hi Ben @iamdefinitelyahuman,

You are right that a multi-line string technically isn't a comment. But that's the best thing we have in Python. Even Guido said himself: "Python tip: You can use multi-line strings as multi-line comments. Unless used as docstrings, they generate no code! :-)" (https://twitter.com/gvanrossum/status/112670605505077248)

In Visual Studio Code, there is a shortcut to comment out many lines. It uses a multi-line string to do the job, not the comment syntax ("#").

You brought an important subject. Why doesn't Vyper allow literals as top-level statements without assignment? Python allows that.

**Comment by fubuloubu** [comment]
Vyper is a lot more restrictive than Python, we don't want random literals lying around mucking up things

pro-tip:
```python
ignore: constant(string) = """
... # Code to ignore
"""
```
probably works

**Comment by arjunaskykok** [comment]
Yeah, I have thought about using dummy variable as a hack for commenting out many lines. In the ideal world, Python should have a proper multi-line comment, something like /* */. But it is what is is.

Feel free to close this issue. This is not the hill that I'm willing to die on. 😂
