### ISSUE TITLE
Can't implement interface defined in same file

### ISSUE THREAD

**Issue by RevCBH** [vyperlang/vyper#2310]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.8+commit.069936f
* OS: linux
* Python Version (output of `python --version`): Python 3.8.5
* Environment (output of `pip freeze`):
```
apturl==0.5.2
argcomplete==1.12.2
attrs==19.3.0
Automat==0.8.0
blinker==1.4
breezy==3.0.2
catfish==1.4.13
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==20.4
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
Deprecated==1.2.7
distro==1.4.0
distro-info===0.23ubuntu1
dulwich==0.19.15
entrypoints==0.3
fastimport==0.9.8
gpg===1.13.1-unknown
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
iniconfig==1.1.1
Jinja2==2.10.1
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lightdm-gtk-greeter-settings==1.2.2
macaroonbakery==1.3.1
MarkupSafe==1.1.0
menulibre==2.2.1
more-itertools==4.2.0
mugshot==0.4.2
netifaces==0.10.4
oauthlib==3.1.0
olefile==0.46
onboard==1.4.1
packaging==20.9
pexpect==4.6.0
Pillow==7.0.0
pipx==0.16.0.0
pluggy==0.13.1
protobuf==3.6.1
psutil==5.5.1
py==1.10.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycups==1.9.73
PyGithub==1.43.7
Pygments==2.3.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.7
pyRFC3339==1.1
pyrsistent==0.15.5
pyserial==3.4
pytest==6.2.2
python-apt==2.0.0+ubuntu0.20.4.4
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
python-gitlab==2.0.1
pytz==2019.3
PyYAML==5.3.1
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
SecretStorage==2.3.1
service-identity==18.1.0
sgt-launcher==0.2.5
simplejson==3.16.0
six==1.14.0
sos==4.0
ssh-import-id==5.10
systemd-python==234
toml==0.10.2
Twisted==18.9.0
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
userpath==1.4.2
wadllib==1.3.3
wrapt==1.11.2
xcffib==0.8.1
xkit==0.0.0
zipp==1.0.0
zope.interface==4.7.1
```

### What's your issue about?

In asking about some related interface import issues on Discord, someone noted that code like the following should be expected to work:

```python
# @version >=0.2.8 <0.3.0

interface SomeInterface:
    def f(): nonpayable

implements: SomeInterface

@external
def f():
    pass
```

As it is it produces an error like: `vyper.exceptions.StructureException: Unknown interface specified: SomeInterface`

Please include information like:

* full output of the error you received
    ```
    Error compiling: example.vy
    vyper.exceptions.StructureException: Unknown interface specified: SomeInterface
      contract "example.vy", line 6:0
           5
      ---> 6 implements: SomeInterface
      -------^
           7
    ```
* what command you ran
    `vyper example.vy` on a file containing the sample above
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

**Comment by RevCBH** [comment]
As a possibly related issue:

If `SomeInterface.vy` contains:
```python
# @version >=0.2.8 <0.3.0

interface SomeInterface:
    def f(): nonpayable
```

And I run `vyper -f abi SomeInterface.vy`, the only output is `[]`

**Comment by fubuloubu** [comment]
> As a possibly related issue:
> 
> If `SomeInterface.vy` contains:
> 
> ```python
> # @version >=0.2.8 <0.3.0
> 
> interface SomeInterface:
>     def f(): nonpayable
> ```
> 
> And I run `vyper -f abi SomeInterface.vy`, the only output is `[]`

So the problem here is that you've defined an interface, but haven't implemented anything that uses it. For the "interface files" you basically do something like this instead:

```python
@external
def f():
    ...
```

**Comment by RevCBH** [comment]
@fubuloubu - Thanks. That's where I ended up with it (and then generating json abi into the `interfaces/` directory for use by other components as I had some issue importing a full contract w/ structs defined).

Wasn't sure what was unexpected vs me just being new and not understanding the right way to do things :+1:

**Comment by charles-cooper** [comment]
i just checked, and the code in this issue compiles as of v0.2.13
