### ISSUE TITLE
Pre-compiled vyper binaries are missing from releases 0.2.9 and 0.2.10

### ISSUE THREAD

**Issue by skellet0r** [vyperlang/vyper#2313]
## Description

There actually isn't any bug in the code, both vvm and brownie are functioning correctly, they just can't properly get vyper versions 0.2.9 and 0.2.10 since there are no precompiled binary versions available.

Related eth-brownie/brownie#964

**Comment by fubuloubu** [comment]
we hadn't gotten a chance to release those yet, however if you install via `pip install "vyper==0.2.10"` directly you can use it!
