### ISSUE TITLE
FunctionDeclarationException: Unknown decorator: public

### ISSUE THREAD

**Issue by codinghedgehog-python** [vyperlang/vyper#2315]
Hi, I was hoping to get some feedback on the error below.

### Version Information

* vyper Version (output of `vyper --version`):  0.2.10+commit.418c85b
* OS: Ubuntu Linux
* Python Version (output of `python --version`):  3.8.5
* Environment (output of `pip freeze`): 
```
appdirs==1.4.3
asttokens==2.0.4
CacheControl==0.12.6
certifi==2019.11.28
chardet==3.0.4
colorama==0.4.3
contextlib2==0.6.0
distlib==0.3.0
distro==1.4.0
html5lib==1.0.1
idna==2.8
ipaddr==2.2.0
lockfile==0.12.2
msgpack==0.6.2
packaging==20.3
pep517==0.8.2
progress==1.5
pycryptodome==3.10.1
pyparsing==2.4.6
pytoml==0.1.21
requests==2.22.0
retrying==1.3.3
semantic-version==2.8.5
six==1.14.0
urllib3==1.25.8
vyper==0.2.10
webencodings==0.5.1
```
I'm just starting out with Vyper to learn the ropes of writing smart contracts. I'm working with this simple hello world example:

```
name: public(bytes[24])

@public
def __init__():
    self.name = 'Satoshi Nakamoto'

@public
def change_name(new_name: bytes[24]):
    self.name = new_name

@public
def say_hello() -> bytes[32]:
    return concat('hello, ', self.name)
```
which gives me this error output:
```
UnknownType: No builtin or user-defined type named 'bytes'
  contract "hello.vy", line 1:13 
  ---> 1 name: public(bytes[24])
  --------------------^
       2


FunctionDeclarationException: Unknown decorator: public
  contract "hello.vy", function "__init__", line 3:1 
       2
  ---> 3 @public
  --------^
       4 def __init__():


FunctionDeclarationException: Unknown decorator: public
  contract "hello.vy", function "change_name", line 7:1 
       6
  ---> 7 @public
  --------^
       8 def change_name(new_name: bytes[24]):


FunctionDeclarationException: Unknown decorator: public
  contract "hello.vy", function "say_hello", line 11:1 
       10
  ---> 11 @public
  ---------^
       12 def say_hello() -> bytes[32]:
```

**Comment by skellet0r** [comment]
Hey @codinghedgehog-python, according to the changelog the `@public` function decorator was renamed to `@external` and the `bytes` type must be written as `Bytes`, according to the [changelog for vyper version 0.2.1](https://vyper.readthedocs.io/en/stable/release-notes.html#v0-2-1)

Also I'm not sure if it's posted anywhere, but another good spot for support questions like this is the new [Ethereum Python Community Discord Server](https://discord.gg/UyeGGmxtQB).

Good luck on your learning journey by the way!

**Comment by codinghedgehog-python** [comment]
@skellet0r Thanks so much for the link. I'm defo joining. I'm closing this now as this isn't really a bug.
