### ISSUE TITLE
VIP: Absolute Value Function

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2340]
## Simple Summary
Add an absolute value function under `vyper.math` scope

## Motivation
Just be able to calculate `abs(a)`

## Specification
```python
from vyper.math import abs
# OR `from vyper import math; math.abs(...)`

...

b: int128 = abs(-126)
assert b == 126
```

## Backwards Compatibility
N/A

## Dependencies
N/A

## References
N/A

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by iamdefinitelyahuman** [comment]
Implemented in #2356
