### ISSUE TITLE
Can't import interface using structs

### ISSUE THREAD

**Issue by ElianaTroper** [vyperlang/vyper#2359]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.12+commit.2c6842c
* OS: linux
* Python Version (output of `python --version`): 3.8.5
* Environment (output of `pip freeze`):
```
asttokens==2.0.4
pycryptodome==3.10.1
semantic-version==2.8.5
six==1.15.0
vyper==0.2.12
```

### What's your issue about?

Can't import an interface if it uses structs. Simple example:

foo.vy:
```
struct Widget:
        name: String[8]
        count: uint256

widget: Widget

@external
def show() -> (String[8], uint256):
        return (self.widget.name, self.widget.count)

@external
def __init__():
        self.widget = Widget({
                name: "thing",
                count: 1
        })
```
bar.vy
```
import foo as Foo

@external
def __init__():
        pass
```

Throw both in the same dir.

`vyper foo.vy` results in a successful compilation

`vyper bar.vy` results in:
```
Error compiling: bar.vy
vyper.exceptions.InvalidType: Invalid base type: Widget
  contract "Foo", line 5:8 
       4
  ---> 5 widget: Widget
  ---------------^
       6
```

### How can it be fixed?

Haven't spent time fixing yet

**Comment by fubuloubu** [comment]
At first I thought it was because `widget` was public, but this is indeed a bug with how our current processing works
