### ISSUE TITLE
Multidimensional lists declaration is inverted

### ISSUE THREAD

**Issue by eduardoxfurtado** [vyperlang/vyper#2367]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.8
* Python Version (output of `python --version`): 3.9.2

### What's your issue about?

I expect that when declaring multidimensional lists of two dimensions it would be like:
`<variable_name : <Type>[<row>][<column>]`
so then they can be accessed by:
`variable_name[row][column]`

However, it seems that the declaration is inverted so it's actually:
`<variable_name : <Type>[<column>][<row>]`
and then oddly, we access it the correct way:
`variable_name[row][column]`

The only thing that the documentation says about Multidimensional lists is:
"Multidimensional lists are also possible."

No usage examples are provided, so I don't know if this is intended of not. A severe bug or it's like that by design and documentation is lacking.

I would expect that it would work like in C:
```
#include <stdio.h>

int main()
{
    // declare and initialize an array of two dimentions:
    int arr2d[2][4] = {  
       {0, 0, 0, 0},
       {0, 0, 0, 0},
    };
    
    // prints the multidimentional array:
    for (int i = 0; i < 2; i++)
    {
        for (int j = 0; j < 4; j++)
        {
            printf("%d ", arr2d[i][j]);
        }
        printf("\n");
    }
    // output: 
    // 0 0 0 0 
    // 0 0 0 0 
    
    printf("\n-------------\n\n");
    
    // modify an element
    arr2d[1][3] = 9;
    
    // prints the multidimentional array again:
    for (int i = 0; i < 2; i++)
    {
        for (int j = 0; j < 4; j++)
        {
            printf("%d ", arr2d[i][j]);
        }
        printf("\n");
    }
    // output: 
    // 0 0 0 0 
    // 0 0 0 9
    
    return 0;
}
```

And the same implementation but on vyper would currently look like the following:
```
arr2d: int128[4][2] = empty(int128[4][2])
# the array above is not:
# 0 0
# 0 0
# 0 0
# 0 0

# it's actually:
# 0 0 0 0
# 0 0 0 0

# the line below would make it crash:
arr2d[3][1] = 9

# the line below would work as if the array was declared as arr2d: int128[2][4]
arr2d[1][3] = 9
# now it would print:
# 0 0 0 0
# 0 0 0 9

```

### How can it be fixed?

The semantics of array declaration should be inverted

**Comment by iamdefinitelyahuman** [comment]
Vyper's array notation is modeled after Solidity: https://docs.soliditylang.org/en/v0.6.0/types.html#arrays

I agree that this can be unintuitive when coming from other languages, and the documentation does not adequately address it.

**Comment by eduardoxfurtado** [comment]
OK. Interesting.

Maybe I am emotional about this because I lost 3 days of work debugging a code that didn't have a bug, but I believe that the notation should be changed to resemble python, after all vyper is supposed to be a pythonic language, not a soliditic language, right?

Either way, the documentation should be updated to clearly indicate this fact.

From my understanding, in vyper, the notation for the declaration is inverted but not the usage notation. Is this the same case for solidity?

**Comment by fubuloubu** [comment]
> I believe that the notation should be changed to resemble python, after all vyper is supposed to be a pythonic language, not a solidity-like language, right?

Unfortunately, not that simple. We would lose all compatibility with Solidity code because they set the convention first. Same reasom why all ERCs are written in `camelCase` because they set the convetion first.

If we were to set the convention over again, maybe we would do it this way, but the onlt realt solution out od this is to update the documentation around multi-level arrays

**Comment by eduardoxfurtado** [comment]
I am updating the docs right now and will make a push request. I am just testing what I wrote there.

Can you confirm that it's only the declaration that is inverted but the usage is not?


This is what I wrote:
Multidimensional lists are also possible. The notation for the declaration is reversed compared to some other languages.

A two dimensional list can be declared with ``_name: _ValueType[_Column_Integer][_Row_Integer]``.

.. code-block:: python

    # Defining a list with 2 rows and 5 columns
    exampleList2D: int128[5][2]

    # Setting values
    exampleList2D = [[10, 11, 12, 13, 14], [16, 17, 18, 19, 20]]

    # Setting a value for row the first row (0) and last column (4)
    exampleList2D[0][4] = 42

    # Returning the value in row 0 column 4
    return exampleList2D[0][4]

**Comment by fubuloubu** [comment]
I think maybe some of the confusion is in using "row" and "column". Whats really going on here is that the array definition is "inner" relative to other, e.g.

```python
v: uint256[2][5]  # size 5 array of `uint256[2]` arrays
```

Basically, 2 is inside 5.

This ends up looking "backwards" because when you access you access "outside in".

```python
a: uint256[2] = v[3] # access `uint256[2]` array at index 3 of outer array
```

The processing in these two different contexts is inverted, so when I define the variable I am defining a type `uint256[2][5]` which is a size 5 array of `uint256[2]` internal types, and when I access it i am going in the opposite direction
