### ISSUE TITLE
Meeting July 19 2021

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2375]
Start time: 19:00 UTC (https://time.is/UTC)

Vidchat link: https://meet.jit.si/VyperPlanningMeeting

Agenda:
- [x] #2381
- [x] #2385
- [x] #2386

**Comment by fubuloubu** [comment]
next: #2406

**Comment by tackoman** [comment]
> Start time: 19:00 UTC (https://time.is/UTC)
> 
> Vidchat link: https://meet.jit.si/VyperPlanningMeeting
> 
> Agenda:
> 
> * [x]  [VIP: Convert Struct construction to use kwargs #2381](https://github.com/vyperlang/vyper/issues/2381)
> * [x]  [VIP: Change slot layout #2385](https://github.com/vyperlang/vyper/issues/2385)
> * [x]  [VIP: Jump table optimization #2386](https://github.com/vyperlang/vyper/issues/2386)
