### ISSUE TITLE
Re-entrancy Locks breaks with upgrade to 0.2.14

### ISSUE THREAD

**Issue by pandadefi** [vyperlang/vyper#2393]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.14
* Python Version (output of `python --version`): 3.8.10

### What's your issue about?

I am upgrading the yearn vault code to 0.2.14, after the update some functions called in tests were failling.
I noticed that the gas usage was really small alsmost like if the code wasn't executed.
I later realized that the function that were hacing some issues were the one with the `@nonreentrant` decorator.
I have removed the decorator to run the tests and they are working.

Please include information like:

<img width="672" alt="Screen Shot 2021-07-22 at 4 47 36 PM" src="https://user-images.githubusercontent.com/87183122/126765835-a2b22bc7-66d0-437c-b405-3f778f352368.png">
<img width="785" alt="Screen Shot 2021-07-22 at 4 47 16 PM" src="https://user-images.githubusercontent.com/87183122/126765838-67258183-d53e-4d79-a255-233d0413e235.png">

**Comment by charles-cooper** [comment]
Thanks for the report, this is fixed in https://github.com/vyperlang/vyper/pull/2391, waiting review

**Comment by pandadefi** [comment]
> Thanks for the report, this is fixed in #2391, waiting review

amazing, thanks.

**Comment by charles-cooper** [comment]
Fixed in https://github.com/vyperlang/vyper/pull/2391
