### ISSUE TITLE
VIP: kwarg to allow manually handling call success

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2400]
## Simple Summary
Add a kwarg, provisionally `revert_on_failure=True` to all calls which, when set to `False`, allows the programmer to catch the result of a call. The default behavior would be `revert_on_failure=True`, which is identical to the current behavior.

```python
output = raw_call(...) # current behavior, reverts if the output of underlying call is 0
output = raw_call(..., revert_on_failure=True) # identical
success, output = raw_call(..., revert_on_failure=False) # new behavior
```
The tuple `(success, output)` is used to match solidity.

## Motivation
Right now you can't handle failed calls except the automatic behavior which is to revert.

## Backwards Compatibility
No known issues

## References
This is an alternative to (and easier to implement than) https://github.com/vyperlang/vyper/issues/1517

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by adapt7** [comment]
@fubuloubu @charles-cooper is this included in 3.0? if not, can I find it in any dev branch or is it WIP or not started?

If not available yet, do you know if there is **any other way** to have multiple raw_call and to not revert the whole transaction if any of those calls fail? so you would see message like:

"Although one or more Error Occurred [execution reverted] Contract Execution Completed"

in the Etherscan and the success calls before the failed one will show up as completed.

**Comment by fubuloubu** [comment]
Not started yet, taking contributions to make it happen, should be straightforwards

**Comment by charles-cooper** [comment]
@fubuloubu do you think we should allow the `revert_on_failure` kwarg with non-raw_call calls?

**Comment by charles-cooper** [comment]
Not exactly a dependency for the implementation but #2480 will be helpful for the usability of this feature.

**Comment by charles-cooper** [comment]
Should be ready for trying it out

**Comment by adapt7** [comment]
@charles-cooper getting:

```UnboundLocalError: local variable 'call_success_node' referenced before assignment```

**Comment by charles-cooper** [comment]
> @charles-cooper getting:
> 
> `UnboundLocalError: local variable 'call_success_node' referenced before assignment`

@adapt7 that case should be fixed in c928085f48803b51b4ab3da16c99c3bb151d3fc4, can you check again?

**Comment by charles-cooper** [comment]
@adapt7 see b826f4967dc32a59b1d159c20bf4ba9113b1bc18

**Comment by charles-cooper** [comment]
done in https://github.com/vyperlang/vyper/pull/2482

**Comment by adapt7** [comment]
@charles-cooper many thanks, all seem to work as expected.

**Comment by fubuloubu** [comment]
NOTE: No docs were added for this
