### ISSUE TITLE
Meeting August 30 2021

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2406]
Start time: 19:00 UTC (https://time.is/UTC)

Vidchat link: https://meet.jit.si/VyperPlanningMeeting

Agenda:
- [x] #2400
- [x] #2415
- [x] #2427
- [x] #2431

**Comment by charles-cooper** [comment]
I think we should talk a bit about how `extract32` does the same thing as `convert` combined with `slice`

**Comment by fubuloubu** [comment]
Meeting notes: deprecate `extract32` with a VIP for v0.3.0

**Comment by charles-cooper** [comment]
for reference, https://github.com/vyperlang/vyper/issues/2221#issuecomment-726219256

**Comment by fubuloubu** [comment]
also chatted about #1954

**Comment by fubuloubu** [comment]
next: #2445
