### ISSUE TITLE
test fail with web3.py 5.21.0

### ISSUE THREAD

**Issue by benjyz** [vyperlang/vyper#2407]
### Version Information

* vyper Version (output of `vyper --version`): latest master (cff69d63)
* OS: macos
* Python Version (output of `python --version`): 3.9.6

### What's your issue about?

tests fail

tests/cli/vyper_json/test_parse_args_vyperjson.py::test_pretty_json - json.decoder.J...
FAILED tests/cli/vyper_json/test_parse_args_vyperjson.py::test_to_stdout - json.decoder.JSO...
FAILED tests/parser/features/test_assert.py::test_assert_reason[False] - AssertionError: as...
FAILED tests/parser/features/test_assert.py::test_assest_reason_revert

misses the string "execution reverted"

**Comment by charles-cooper** [comment]
which version of web3?

**Comment by benjyz** [comment]
I bumped these 3 packages to get it work with more recent package to make ape work.

web3==5.21.0
pytest-xdist>=2.3.0
pytest==6.2.4

**Comment by charles-cooper** [comment]
So to clarify, the tests are failing with web3==5.21.0?

Have you tried upgrading to vyper 0.2.15?

**Comment by benjyz** [comment]
yes, those 4 tests fail. I am using latest master (cff69d63)

**Comment by charles-cooper** [comment]
Can you post your whole command and output please?

**Comment by charles-cooper** [comment]
@benjyz I've confirmed the issue is with the new version of web3. Would you be willing to submit a PR updating these tests to be compatible with the new web3? I think the best thing to do is to strip out the `"execution reverted:"` prefix from each of the relevant strings.

**Comment by benjyz** [comment]
ok sure, will see if I can make it all work. now I get 91 failed, I assume thats the fuzzing tests.
