### ISSUE TITLE
Add method_id kwarg to abi_encode builtin

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2408]
Usage:
```
raw_call(addr, abi_encode(data, method_id=0x12345678))
```

**Comment by fubuloubu** [comment]
allow us to get it from the `method_id` builtin function as well

**Comment by charles-cooper** [comment]
Of course. Those are always converted at compile time to a constant so either way would work

https://github.com/vyperlang/vyper/blob/cff69d63531b43eda4dd8a5c83aa09c379c78141/vyper/builtin_functions/functions.py#L678
