### ISSUE TITLE
VIP: Accessing deployed byte code

### ISSUE THREAD

**Issue by skellet0r** [vyperlang/vyper#2427]
## Simple Summary

Add an additional member to the `address` type, `code`.
The `code` attribute allows developers in conjunction with the `slice` built-in to extract explicit portions of a deployed contract's byte-code to memory.

Ex.

```python
@external
def foo():
    implementation: address = convert(slice(msg.sender.code, 15, 20), address)
    assert implementation == 0xbFcF63294aD7105dEa65aA58F8AE5BE2D9d0952A
    ...
```

## Motivation

Currently the `address` type has the members `codehash` (EXTCODEHASH) and `codesize` (EXTCODESIZE) for viewing the hash of a contract's bytecode, and length of a contract's bytecode, respectively. In many cases these two together along with the knowledge of how vyper creates minimal proxies is all that is needed for what I have envisioned.

Essentially in the factory pattern, there isn't a way to verify the calling contract is an approved proxy unless it was previously built into the factory logic itself.
One way to go about this is to check the deployed byte code at the proxy address itself. For contract's deployed with vyper's `create_forwarder_to`, we can simply extract the implementation being used with `slice(_bytecode, 15, 20)` and then convert that to an address, and then validate it's the implementation we expect.

Although the intended use case can be simulated by simply using `concat` along with the pre + post bytecode, the implementation address, and keccak, and then checking against the codehash of an address matches the expectation.  This would provide a much more clearer, readable way. 

## Specification

This VIP would simply allow the usage of `address.code` with the `slice` built-in. This would operate exactly the same as the recently added `msg.data` syntax.

## Backwards Compatibility

This is completely backwards compatible.

## References

#2419

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by charles-cooper** [comment]
I was wondering when somebody would bring this up. Note that we don't use EXTCODECOPY anywhere but if we did this and wanted it to work on OVM we would have to implement that -- https://github.com/vyperlang/vyper/pull/2416/files#diff-8401049c99db99323e79f128a7ed875d909207a0484bddbe737ffb593194c3c0R527
