### ISSUE TITLE
VIP: Allow computation of `a · b % 2^256`

### ISSUE THREAD

**Issue by reednaaxeelaa** [vyperlang/vyper#2429]
## Simple Summary
`pow_mod256` currently exist for computing `a ** b % (2 ** 256)` but the equivalent function for computing `a · b % (2 ** 256)` does not exist as `uint256_mulmod` does not allow `c` as `(2 ** 256)`.

## Motivation
 I want to calculate the product of 2 numbers where overflow is almost guaranteed. The easiest/cheapest algorithm is the one described in https://github.com/vyperlang/vyper/issues/1086 which _could_ be implemented in Vyper as:
```python
def _bigmul(a : uint256, b : uint256) -> uint256[2]:
    r0: uint256 = uint256_mulmod(a, b, 2**256)
    r1: uint256 = uint256_mulmod(a, b, MAX_UINT256)
    r1 = (r1-r0) - convert(r1 < r0, uint256)

    return [r0, r1]
```
However `uint256_mulmod(a, b, 2**256)` is not supported.

Since `uint256_mulmod(a, b, 2**256)` would be `a · b` without overflow protection, it can used as an explicit way to disable overflow protection potentially fulfilling the needs of https://github.com/vyperlang/vyper/issues/2335.

If this is a desired feature, `uint256_addmod(a,b, 2**256)` could be added as a way to disable overflow protection on addition.

## Specification
Upgrade `uint256_mulmod` and  `uint256_addmod` allowing `c = 2**256` as a special cases without overflow protection.

Alternatively, maintain the naming scheme of `pow_mod256` for the edge case:
- `mul_mod256(a: uint256, b: uint256) → uint256`
- `add_mod256(a: uint256, b: uint256) → uint256` 

Both of the function can be implemented directly via the MUL and ADD opcodes since these naturally overflow like modules `2^256` for uint256.

## Backwards Compatibility
I do not believe this introduces any breaking changes.

## References
https://github.com/vyperlang/vyper/issues/2335
https://github.com/vyperlang/vyper/issues/1086
https://medium.com/wicketh/mathemagic-full-multiply-27650fec525d

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by charles-cooper** [comment]
We may just want to introduce `unsafe_` versions of all math ops

**Comment by reednaaxeelaa** [comment]
Personally, I prefer syntax that wraps overflows into an explicit behaviour. I believe this resonates better with [the Zen of Python](https://www.python.org/dev/peps/pep-0020/): _Explicit is better than implicit_, and the **Auditability** goal of Vyper.

**Comment by fubuloubu** [comment]
> We may just want to introduce `unsafe_` versions of all math ops

Meeting notes: implement `unsafe_*` functions

**Comment by charles-cooper** [comment]
should be resolved as of https://github.com/vyperlang/vyper/pull/2629. we decided to go with `unsafe` builtins because the intent is clear, and because the analogy carries over to `div` and `sub` (for which there are no matching "`div_mod`" and `sub_mod` ops).
