### ISSUE TITLE
LSP support

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2434]
https://github.com/neovim/nvim-lspconfig

**Comment by fp-crypto** [comment]
Looks like solidity is on the verge of adding LSP support https://github.com/ethereum/solidity/pull/11350

**Comment by spinoch** [comment]
I looked very briefly into how one may implement this. Seems like it would require substantial effort

**Comment by mlntr** [comment]
Solidity just [launched](https://blog.soliditylang.org/2021/12/20/solidity-0.8.11-release-announcement/) their LSP

Perhaps it could be possible to leverage an existing Python LSP to help build a Vyper LSP?

**Comment by fubuloubu** [comment]
Well, it might be possible to leverage jedi a bit for this: https://github.com/pappasam/jedi-language-server

**Comment by meatballs** [comment]
I wonder if it might be possible to create a vyper plugin for https://github.com/python-lsp/python-lsp-server

**Comment by sify21** [comment]
found this plugin for vscode, at very early stage: https://github.com/z80dev/vscode-vyper-lsp-extension
