### ISSUE TITLE
make black formatting work

### ISSUE THREAD

**Issue by benjyz** [vyperlang/vyper#2443]
the parser of black fails for structs, events and log. would be nice to have it

**Comment by charles-cooper** [comment]
Interesting. We do some preparsing to handle those cases, I wonder if we can do a round-trip -- preparse, black, un-preparse.

**Comment by spinoch** [comment]
>  I wonder if we can do a round-trip -- preparse, black, un-preparse.

See https://github.com/vyperlang/blackadder/ . No longer maintained.  It does exactly that

**Comment by charles-cooper** [comment]
Thanks @spinoch closing in light of that
