### ISSUE TITLE
write to file with out

### ISSUE THREAD

**Issue by benjyz** [vyperlang/vyper#2444]
## Simple Summary

I want to do:

`vyper -o . foo.vy`

to generate foo.bin and foo.abi.

## Motivation
unix pipe adds a "\n" to file end

## implementation

wip https://github.com/benjyz/vyper/commit/3cf805188ff9847c81623b7a0b8f071ad38782b0

**Comment by charles-cooper** [comment]
fixed in https://github.com/vyperlang/vyper/pull/2452
