### ISSUE TITLE
Meeting September 20 2021

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2445]
Start time: 19:00 UTC (https://time.is/UTC)

Vidchat link: https://meet.jit.si/VyperPlanningMeeting

Agenda:

- [x] #1954
- [x] #2318
- [x] #2429

**Comment by charles-cooper** [comment]
couple discussion topics: 

https://github.com/vyperlang/vyper/issues/2318
https://github.com/vyperlang/vyper/issues/2310

**Comment by charles-cooper** [comment]
https://github.com/vyperlang/vyper/issues/2429

**Comment by fubuloubu** [comment]
next: #2461
