### ISSUE TITLE
Question: type declaration for tuples

### ISSUE THREAD

**Issue by spinoch** [vyperlang/vyper#2446]
### What's your issue about?

I'm reading from an interface which returns a tuple like this:

```
interface X:
    def x() -> (bytes32, uint256): view
```
When I try to call `X.x()`, it's difficult to declare the tuple types properly.
I've tried, what seems to be most intuitive:
`(a: bytes32, b: uint256) = ...`
Error:
```
vyper.exceptions.SyntaxException: invalid syntax (<unknown>, line 8)
  line 8:7 
       7 def try_x():
  ---> 8     (a: bytes32, b: uint256) = X(0x0000000000000000000000000000000000000000).x()
  --------------^
       9
```

```
    (a, b) : (bytes32, uint256) = X.x()
```
Error: `vyper.exceptions.SyntaxException: only single target (not tuple) can be annotated (<unknown>, line 8)`

The following seems to work:
```
    a: bytes32 = empty(bytes32)
    b: uint256 = empty(uint256)
    (a, b) = X(0x0000000000000000000000000000000000000000).x()
```
But it becomes quite verbose when working with longer tuples.

Is there any other way of declaring the types here?

**Comment by charles-cooper** [comment]
Best way would probably be to use a named struct (which are semantically identical to tuples, tuples can be thought of as anonymous structs). Would that work for your use case?

**Comment by spinoch** [comment]
yeah, that works great, thanks. Ironic, because I tried that before and messed something up which made me think it didn't work 😅
