### ISSUE TITLE
VIP: Automatically set function decorators

### ISSUE THREAD

**Issue by spinoch** [vyperlang/vyper#2465]
## Simple Summary
It seems like Vyper's compiler can automatically infer the kind of state interaction of a function, and external/internal functions must follow certain syntax requirements, so let's have the compiler set these attributes for us. 

## Motivation
This would make iteration for the developer faster as they can just write their functions and vyper will tell them the expected state transitions and whether it's external/internal.

## Specification
TBD. This could live in a separate package from vyper or could be part of the compiler.
e.g.
let `example.vy` be
```
def externalView() -> uint256:
	return self.x * 2
```
Then after calling `vyper --infer-decorators example.vy` we have
```
@view
@external
def externalView() -> uint256:
	return self.x * 2
```

What can be inferred:
- Mutability
- Visibility, `"@internal" if f.startswith("_") and f not in ["__init__", "__default__"] else "@external"`
-  payable/nonpayable may also be inferred by looking at whether msg.value is used in a function

## Backwards Compatibility
N/A

## Dependencies
N/A

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Meeting notes: this seems like a good use case for an external tool that might be used to infer and repair code in place, helping writers write proper vyper.

see https://github.com/vyperlang/blackadder
