### ISSUE TITLE
Events that take structs have malformed ABI JSON

### ISSUE THREAD

**Issue by haltman-at** [vyperlang/vyper#2483]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.0+commit.8a23feb
* OS: Release Linux Mint 20.2 Uma 64-bit
* Python Version (output of `python --version`): Python 3.8.10

### What's your issue about?

If you declare an event that takes a struct, the ABI JSON for it will be malformed.  Note that unlike the previous encoding bug, this bug is not specific to the case where the input is just a single struct alone; all structs used as event arguments appear to exhibit this bug.  Because of this, decoding libraries will fail to decode such events.

As an example, suppose I write a contract with the following declarations:

```vyper
struct Pair:
    x: uint256
    y: uint256

event Stuff:
    pair: Pair
    z: uint256
```

The ABI JSON I get for this event is:

```json
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "pair",
          "type": "(uint256,uint256)"
        },
        {
          "indexed": false,
          "name": "z",
          "type": "uint256"
        }
      ],
      "name": "Stuff",
      "type": "event"
    },
```

As you can see, this ABI item is malformed.  The first input, rather than having type `"tuple"` and an appropriate `components` field, instead has the malformed type `"(uint256,uint256)"`.  Decoding libraries are unable to handle this.

This bug does not apply to function inputs, function outputs, or constructor inputs; those have proper ABI JSON.

### How can it be fixed?

Given that structs are handled properly in the ABI JSON for functions and constructors, both on input and on output, whatever code you use for handling those can presumably be applied to event inputs as well.

**Comment by charles-cooper** [comment]
Thanks for the bug report!

**Comment by charles-cooper** [comment]
update: PR to fix this is open but blocked on https://github.com/ethereum/web3.py/issues/1629 for testing the functionality
