### ISSUE TITLE
fixed length arrays imported from JSON interfaces are not recognized

### ISSUE THREAD

**Issue by pyrex41** [vyperlang/vyper#2487]
### Version Information

* vyper Version (output of `vyper --version`):0.2.16
* OS: osx/
* Python Version (output of `python --version`): 3.9

### What's your issue about?
When I compile a project using brownie where contract A imports an interface of Contract B, and the interface for B is generating using `vyper --json`, then i get vyper compilation errors.

Repo created to show issue here: https://github.com/pyrex41/VypereIssue

To replicate: run `brownie compile`

Note: using pipx to install both brownie and vyper. Both should be using same version (0.2.16), but I think they are using separate executables. For what it's worth.

Please include information like:

* full output of the error you received
* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* please try running your example with the --debug flag turned on

See text file in repo above for `--debug` output.

### How can it be fixed?

If you generate the interface using `vyper --interface`, then the issue goes away.

**Comment by charles-cooper** [comment]
this is fixed in master, (probably as of a16af3d7e54)
