### ISSUE TITLE
VIP: Simplify+generalize conversion rules

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2507]
## Simple Summary
Simplify and generalize type conversion rules.

## Motivation
https://github.com/vyperlang/vyper/issues/1093 introduced type conversion rules between all the types in vyper that existed at the time. Now that the number of numeric types is growing, we can't just add more rules for every type that gets added. This will result in N^2 rules which is hard to code, and hard to reason about.

This VIP is basically a distillation of #1093 into rules that will generalize to more types. It modifies the rules for address, making it harder to convert address into other types (however - it can be converted via intermediate conversion to `bytes32`, which means "I really want to do this").

## Specification
Terminology:
- `bitcast`: leave the input byte-for-byte unchanged
- `padconvert`: convert left- or right-padding to the other one. (integers are left-padded with zeroes; bytestrings are right-padded).
- `top`: leftmost
- `bottom`: rightmost
- `signextend`: fill the top bits with 1's if the sign bit is set (e.g. signextend for int8 will look at the 8th bit from the right)

The general principles are:
- `padconvert` is applied for conversions between left-padded (bytes) and right-padded (other types)
- converting integers to decimals involves truncation
- conversion from a smaller-width to larger-width type is otherwise a no-op
- conversion from a larger-width to smaller-width type requires a clamp
- conversions involving bytes-like types are legal for `Bytes[N<=32]` and `String[N<=32]`
- conversion from a numeric type to a bytes-like type is legal so long as the output type is at-least-as-wide as the input type.
  - For instance, `int128` could be converted to `Bytes[N>=16]`.
- conversion from a bytes-like type to a numeric type requires a clamp.
- conversion between unsigned and signed requires a clamp.
  - For instance, `uint256` to `int128` requires a check that the input is less than `INT128_MAX`.
  - For instance, `int128` to `uint256` requires a check that the input is greater than `0`.

The following (WIP) table summarizes each case:

| from | to | behavior | clamps |
|---|---|---|---|
| `numeric` | `bytesM` | padconvert to `M` bytes | input must have fewer than `M` bytes set |
| `bool` | `bytesM` | padconvert to `M` bytes | input must have fewer than `M` bytes set |
| `address` | `bytesM` | padconvert to `M` bytes | input must have fewer than `M` bytes set |
| `integer` | `bytesM` | padconvert to `M` bytes | input must have fewer than `M` bytes set |
| `bytesN` | `bytesM` | bitcast the input | input must have fewer than `M` bytes set |
| `*` | `bool` | returns `iszero(iszero(input))` | (none) |
| `bool` | `decimal` | `1.0 if True else 0.0` | (none) |
| `bool` | `*` (except decimal) | bitcast the input | (none) |
| `bytesM` | `intN` | padconvert the input with sign extension | input must have fewer than N bits set |
| `decimal` | `uintN` | truncate the input, e.g. `1.0` -> `1` | output must be in bounds for the type, and be >=0 |
| `decimal` | `intN` | truncate the input, e.g. `1.0` -> `1` | output must be in bounds for the type |
| `address` | `uintN` | bitcast the input | input must have fewer than N bits set. signed integers not allowed |
| `bytesM` | `address` | padconvert the input | input must have fewer than 20 bytes set |
| `uintN` | `address` | bitcast the input | input must have fewer than 160 bits set. signed integers not allowed |
| `bytesM` | `decimal` | padconvert the input | input must have fewer than 168 bits set |
| `intN` | `decimal` | promote the input, e.g. `1` -> `1.0` | output must be in bounds |
| `uintN` | `decimal` | promote the input, e.g. `1` -> `1.0` | output must be in bounds, and be <decimal::max_value |
| `udecimal` (hypothetical) | `uintN` | truncate the input | output must be in bounds for the type, and be >=0 |
| `udecimal` (hypothetical) | `intN` | truncate the input | output must be in bounds for the type, and be <intN::max_value |

## Backwards Compatibility
Should stay backwards compatible EXCEPT for address and possibly decimal conversions. `address` is no longer convertible with as many types, and `decimal` now has bitcasting semantics instead of truncation when converting with bytes types.

## References
https://github.com/vyperlang/vyper/issues/967
https://github.com/vyperlang/vyper/issues/1093
https://github.com/vyperlang/vyper/issues/1901
https://github.com/vyperlang/vyper/issues/2317

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by charles-cooper** [comment]
meeting notes: get rid of address=>int128 conversion.

important: conversion from bytes to numeric is allowed ONLY if the output type is at-least-as-wide-as the input type. Bytes[17]=>int128 is illegal.

**Comment by charles-cooper** [comment]
notes: need to think more about bytes32, but basically, conversions should result in the least data change possible (that still makes sense intuitively+maintains safety)

**Comment by charles-cooper** [comment]
conversion from wider input bytes to narrower output int (e.g. `Bytes[17] => int128`) should be allowed (with a runtime clamp), because `int128` and other ints commonly come in via byte encoded data (e.g., calldata, returndata, etc).

**Comment by jakerockland** [comment]
This makes me so happy 🔥 🥳

**Comment by jakerockland** [comment]
Thank you @charles-cooper
