### ISSUE TITLE
vyper.exceptions.TypeCheckFailure: pack_arguments did not return a value

### ISSUE THREAD

**Issue by Eniola4031** [vyperlang/vyper#2520]
### Version Information

* vyper Version (output of `vyper --version`): 0.2.16
* OS: osx
* Python Version (output of `python --version`): python3

### I tried to compile my codes using "vyper file_name.vy" and this is the error I get

Please include information like:

*Error compiling: bounty.v
![Screenshot 2021-11-03 at 9 42 39 PM](https://user-images.githubusercontent.com/54287741/140189733-b037b084-b805-4f25-aa85-eee83b0b1727.png)
y
vyper.exceptions.TypeCheckFailure: pack_arguments did not return a value

This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
* vyper
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* please try running your example with the --debug flag turned on

### How can it be fixed?

Fill this in if you know how to fix it.
![Screenshot 2021-11-03 at 9 42 39 PM](https://user-images.githubusercontent.com/54287741/140189784-eb38f9fd-2994-4537-8a4a-8a6cf5f96d30.png)

**Comment by fubuloubu** [comment]
you might be missing the return value from the interface, or the fact that you're re-using the same interface that we have defined internally might be causing problems.

**Comment by charles-cooper** [comment]
Also maybe try v0.3.0?

**Comment by Eniola4031** [comment]
@fubuloubu I am new to vyper and only trying to implement the withdraw and deposit functions by interfacing  the safeTransferFrom function from ERC721. Do you mind simplifying please?

**Comment by Eniola4031** [comment]
@charles-cooper o.2.16 is the latest release

**Comment by charles-cooper** [comment]
closing as this is a dup of #2374 

By the way @Eniola4031 v0.3.0 is the latest release but as of yesterday we did not have the binaries uploaded to github. This has been corrected and you can view the released binaries here https://github.com/vyperlang/vyper/releases/tag/v0.3.0
