### ISSUE TITLE
using kwarg notation at call site results in typecheck error

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2525]
### Version Information

* vyper Version (output of `vyper --version`): v0.3.0
* OS: osx/linux/win
* Python Version (output of `python --version`): 3.8.10

### What's your issue about?
```python
@internal
def _foo(x: uint256, y: uint256 = 1):
    pass

@external
def foo(x: uint256, y: uint256):
    self._foo(x, y=y)
```
raises:
```
File "/home/charles/.venvs/vyper/lib/python3.8/site-packages/vyper/semantics/validation/utils.py", line 126, in _find_fn
    raise StructureException("Cannot determine type of this object", node)
vyper.exceptions.StructureException: Cannot determine type of this object
```

On the other hand, not using kwargs at the call site compiles fine:
```python
@internal
def _foo(x: uint256, y: uint256 = 1):
    pass

@external
def foo(x: uint256, y: uint256):
    self._foo(x, y)
```
### How can it be fixed?
Change the error message to something like, `"kwarg usage in Vyper is restricted to gas= and value="`.

**Comment by charles-cooper** [comment]
Note the same behavior happens for external calls

**Comment by fubuloubu** [comment]
I think this is because kwarg syntax is reserved for message modifiers like specifying gas limit and value

**Comment by charles-cooper** [comment]
OK I think the best resolution for now is to provide a better error message. I'm not convinced we should be so strict about kwarg syntax since it's intuitive for somebody coming from a python background but I don't feel very strongly about it either way.
