### ISSUE TITLE
Revert messages in `raise` or `assert` are not properly propagated when the exception is rethrown by the caller

### ISSUE THREAD

**Issue by haltman-at** [vyperlang/vyper#2529]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.0+commit.8a23feb
* OS: Release Linux Mint 20.2 Uma 64-bit
* Python Version (output of `python --version`): Python 3.8.10

### What's your issue about?

When a contract `A` calls a contract `B`, and the second call reverts with a message, then the original call will revert as described in the documentation, but it will not propagate the revert message it got from `B`.

Example:

TraceTest.vy:
```vyper
@external
def run():
    raise "Mayday, mayday!"
```

Caller.vy:
```vyper
import TraceTest as Test

test: address

@external
def run():
    Test(self.test).run()

@external
def __init__(test: address):
    self.test = test
```

Deploy `TraceTest`, then deploy `Caller`, passing the address of `TraceTest` as an argument.  Then run `TraceTest.run()`.

The call will revert, but there will be no revert message.  The revert message ought to be, `"Mayday, mayday!"`.

**Comment by fubuloubu** [comment]
good catch! cc @charles-cooper

**Comment by charles-cooper** [comment]
Thanks for the test case btw! Makes the implementer's life easier
