### ISSUE TITLE
`uint8` cannot be used as array index

### ISSUE THREAD

**Issue by hedgar2017** [vyperlang/vyper#2585]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.1
* OS: linux
* Python Version (output of `python --version`): 3.10.1

### What's your issue about?

Command:
```
vyper-0.3.1 tests/vyper/simple/array/store_load_constant_array_witness_index.vy
```

Output:
```
Error compiling: tests/vyper/simple/array/store_load_constant_array_witness_index.vy
vyper.exceptions.TypeCheckFailure: get_element_ptr (256 <array>, [mload, 224 <index>]) did not return a value

This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
```

Example:
```python
SIZE: constant(uint8) = 4

@external
@pure
def main(index: uint8) -> uint8:
    array: uint8[SIZE] = [1, 2, 3, 4]
    return array[index]
```

**Comment by fubuloubu** [comment]
Oh wild! Yes, that should throw if out of bounds

**Comment by charles-cooper** [comment]
I was planning to fix this as part of implementing https://github.com/vyperlang/vyper/issues/2559 - which will genericize the code handling int types
