### ISSUE TITLE
typechecker does not check constants

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2592]
### Version Information

* vyper Version (output of `vyper --version`): v0.3.1

### What's your issue about?

During constant folding, the annotated types for constants do not get propagated. Instead they are translated into literals and the literal types are inferred at the use site. For example the following example compiles even though it shouldn't really:
```python
MY_CONSTANT: constant(uint256[3]) = [1,2,3]

@external
def foo() -> uint8[3]:
    return MY_CONSTANT
```

Compare the error generated for the following

```python
@external
def foo() -> uint8[3]:
    xs: uint256[3] = [1,2,3]
    return xs
```
```
Error compiling: tmp/foo.vy
vyper.exceptions.TypeMismatch: Given reference has type uint256[3], expected uint8[3]
  contract "tmp/foo.vy", function "foo", line 7:11 
       6     xs: uint256[3] = [1,2,3]
  ---> 7     return xs
  ------------------^
       8
```

### How can it be fixed?

Propagate type annotations during constant folding

**Comment by tserg** [comment]
I am interested in taking this up next. I will start end of this week just in case anyone else has already started work.
