### ISSUE TITLE
Multidimensional String arrays are not supported

### ISSUE THREAD

**Issue by thegamebegins25** [vyperlang/vyper#2630]
Whenever I try to make a list of strings (2D array), I get this error `Multidimensional String arrays are not supported`. This is the code I tried: `names: String[30][100]`. Does anyone know how to help? (version 0.3.1)

**Comment by fubuloubu** [comment]
> Whenever I try to make a list of strings (2D array), I get this error `Multidimensional String arrays are not supported`. This is the code I tried: `names: String[30][100]`. Does anyone know how to help? (version 0.3.1)

It's harder to to do efficient memory allocation for this case, but why not try `names: HashMap[uint256, String[30]]` instead?

**Comment by thegamebegins25** [comment]
Figured it out for anyone who wants to know: 
```
# @version ^0.3.1

names: public(HashMap[uint256, String[30]])
lenN: public(uint256)

@external
def __init__():
    self.names[0] = "test"
    self.lenN = 0

@external
def set(namesadd: String[30]):
    self.lenN = self.lenN + 1
    self.names[self.lenN] = namesadd

@view
@external
def read(num: uint256) -> String[30]:
    name: String[30] = self.names[num]
    return name
```
