### ISSUE TITLE
vyper.exceptions.TypeCheckFailure: get_element_ptr (1 <self.bids>, [sload, 0 <self.bid_count>]) did not return a value

### ISSUE THREAD

**Issue by isavelli** [vyperlang/vyper#2669]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.1
* OS: win 
* Python Version (output of `python --version`): Python 3.9.10

### What's your issue about?
```
vyper.exceptions.TypeCheckFailure: get_element_ptr (1 <self.bids>, [sload, 0 <self.bid_count>]) did not return a value

This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
https://github.com/vyperlang/vyper/issues/new?template=bug.md
Error compiling: main_contract copy.vy
```

minimal code to reproduce the error:
```
# @version ^0.3.1

struct bid:
    id: uint256

bid_count: uint8
bids: bid[10]

@external
def submit_bid():
    order: bid = self.bids[self.bid_count]
```

### How can it be fixed?
it compiles with no problem if I use `bid_count: uint256`

**Comment by charles-cooper** [comment]
Seems to be a dup of https://github.com/vyperlang/vyper/issues/2585, @isavelli can you check if this is fixed with latest master?

**Comment by isavelli** [comment]
yes thanks!
