### ISSUE TITLE
VIP: Add `.code` element to address

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2681]
## Simple Summary
add `.code` entry to address types, that returns `Bytes[24_576]`

## Motivation
It might be handy to be able to check into an account's code more directly (say, to check if it's a proxy contract or something). Conventionally, Vyper tries to avoid unbounded dynamic structures, however thanks to [EIP-170](https://eips.ethereum.org/EIPS/eip-170), there is actually a defined bound on contract codesize.

## Specification
Here's an example use case of code for a use case that detects whether a contract is destructible (Copied from [here](https://etherscan.io/address/0x00000000daa80e2b0694604fc3644b0016dd56fc#code)):

```vy
reachable: bool = True
skip_num_bytes: uint256 = 0

for op in target.code:
    if skip_num_bytes > 0:
       skip_num_bytes -= 1
       continue

    if (op > 95 and op < 128):  # pushN
       skip_num_bytes = op - 95 - 1  # We are performing one skip here
       continue
   
    # Check the opcode if it is reachable (i.e. not a constant or metadata).
    if reachable:
        # If execution is halted, mark opcodes that follow as unreachable.
        if op in [
            254,  # invalid
            243,  # return
            253,  # revert
            86,   # jump
            0,    # stop
        ]:
            reachable = False
            continue
        
        # If opcode is impermissible, return true - potential destructibility!
        elif op in [
            242,  # callcode
            244,  # delegatecall
            255,  # selfdestruct
        ]:
            return True  # potentially destructible!

    elif op == 91:
        # Whenever a JUMPDEST is found, mark opcodes that follow as reachable. 
        reachable = True
```

## Backwards Compatibility
No Backwards Compatibility issues

## Dependencies
No Dependencies

## References
No references

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by charles-cooper** [comment]
I believe this was done in https://github.com/vyperlang/vyper/pull/2583 - is there something additional you are looking for?

**Comment by fubuloubu** [comment]
> I believe this was done in #2583 - is there something additional you are looking for?

Oh wow, duh!

This proposal is slightly different in that I realized that there is indeed an explicit maximum codesize, but yeah doing `slice(contract.code, 0, MAX_EIP170_SIZE)` is the same as doing it this way.
