### ISSUE TITLE
vyper.exceptions.UnknownType: No builtin or user-defined type named 'DynArray'

### ISSUE THREAD

**Issue by isavelli** [vyperlang/vyper#2685]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.1
* OS: win
* Python Version (output of `python --version`): 3.9

### What's your issue about?
```
vyper.exceptions.UnknownType: No builtin or user-defined type named 'DynArray'
  contract "test.vy", line 3:13 
       2
  ---> 3 exampleList: DynArray[int128, 3]
```

Please include information like:

I get this error compiling this test file following the Vyper documentation ([https://vyper.readthedocs.io/en/latest/types.html?highlight=#dynamic-arrays](https://vyper.readthedocs.io/en/latest/types.html?highlight=#dynamic-arrays)):

```
# @version ^0.3.1

exampleList: DynArray[int128, 3]

@external
def foo():
    self.exampleList.append(1)
```

**Comment by fubuloubu** [comment]
This feature is unreleased, please reference `stable` docs: https://vyper.readthedocs.io/en/stable/types.html
