### ISSUE TITLE
vyper.exceptions.TypeCheckFailure: Statement node did not produce LLL

### ISSUE THREAD

**Issue by isavelli** [vyperlang/vyper#2688]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.1
* OS: win
* Python Version (output of `python --version`): 3.9

this code
```
@external
def test():

    for c in ['a', 'b']:
        pass
```

gives: 
```
vyper.exceptions.TypeCheckFailure: Statement node did not produce LLL

This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
https://github.com/vyperlang/vyper/issues/new?template=bug.md
Error compiling: aggregator_template copy.vy
```

**Comment by charles-cooper** [comment]
Should be resolved as of https://github.com/vyperlang/vyper/pull/2584

**Comment by charles-cooper** [comment]
#2584 only fixes the error handling; we should consider allowing arrays of strings in the language (cc @fubuloubu )?

**Comment by isavelli** [comment]
yes please, it would be great having arrays of Strings, like `String[4][10]`
