### ISSUE TITLE
Convert Integer to String

### ISSUE THREAD

**Issue by arjunaskykok** [vyperlang/vyper#2703]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.1
* OS: doesn't matter
* Python Version (output of `python --version`): 3.9

### What's your issue about?

I want to have a way to convert an integer to a String: 311 -> "311".

Can I have it?

It's useful in the `tokenURI` method in the NFT smart contract:

```python
@external
def tokenURI(tokenId: uint256) -> String[100]:
    return self.baseURI + convert(tokenId, String[4])
```

`tokenURI` points to the asset of a particular NFT. It's usually a json file.

For example, tokenURI(5) in Pudgy Penguins returns https://ipfs.io/ipfs/QmWXJXRdExse2YHRY21Wvh4pjRxNRQcWVhcKw4DLVnqGqs/5.

### How can it be fixed?

Unfortunately, my brain is smol. So I don't know.

**Comment by fubuloubu** [comment]
It's really not that easy to do this, a general algorithm will be really expensive.

Here's a sketch though:
```vyper
# Or replace 78 with whatever the max should be, e.g. 10k = 5 digits
def _convertDigits(val: uint256) -> String[78]:
    str_val: String[78] = ""

    for i in range(78):
        # NOTE: ASCII digits '0' - '9' are 0x30 - 0x39 inclusive
        str_val[i] = convert((shift(val, -i) % 10 - 1) + 48, String[1])

    return str_val
```

Currently doesn't work because you can't insert chars into a string

**Comment by charles-cooper** [comment]
i believe there is an implementation here https://github.com/vyperlang/vyper/discussions/2363#discussioncomment-1791586

we should consider adding this as a builtin to the language though, because it is somewhat commonly used and having an efficient implementation would be useful

**Comment by fubuloubu** [comment]
> i believe there is an implementation here [#2363 (comment)](https://github.com/vyperlang/vyper/discussions/2363#discussioncomment-1791586)
> 
> we should consider adding this as a builtin to the language though, because it is somewhat commonly used and having an efficient implementation would be useful

I guess we can have the output try to render as `String[N]`, and if it takes more than `N` digits to render the integer argument in base 10, have it throw?

**Comment by charles-cooper** [comment]
we can render any uintN with `M = ceil(N / log2(10))` digits - e.g. 256 bits with 78 decimal places. so i think we can just have a compile-time requirement that the output string have at least M bytes of space.

**Comment by charles-cooper** [comment]
here's a production implementation: https://github.com/curvefi/curve-veBoost/blob/0e51be10638df2479d9e341c07fafa940ef58596/contracts/VotingEscrowDelegation.vy#L423 (h/t @skellet0r )

**Comment by charles-cooper** [comment]
note from https://github.com/vyperlang/vyper/pull/2879#issuecomment-1149406676

> switching back to uint2str, since we don't want to suggest that we have general str implementations for everything. if we start to add more builtins, we can try to settle on a more "generic" name like str or format.

**Comment by charles-cooper** [comment]
closed in https://github.com/vyperlang/vyper/pull/2879
