### ISSUE TITLE
implement vyper code formatter

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2723]
https://pypi.org/project/black/ doesn't work because, while vyper is close to python, it is not a strict subset of python. I looked briefly into doing this with the Lark AST but there is not an obvious/"free" way to pretty-print a Lark AST. So there might be some manual work involved.

**Comment by BoboTiG** [comment]
Actually I found https://github.com/benber86/mamushi quite pertinent. It seems exactly what you were looking for, right?

**Comment by fubuloubu** [comment]
mamushi is a great tool and definitely a solution for this issue, thank you @BoboTiG
