### ISSUE TITLE
Meeting Apr 18 2022

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2758]
Start time: 20:00 UTC (https://time.is/UTC)

Vidchat link: https://meet.jit.si/VyperPlanningMeeting

Agenda:

- [x] can we remove the `--memorymock` tests?
- [x] https://github.com/vyperlang/vyper/issues/2750
- [x] https://github.com/vyperlang/vyper/issues/2766
- [x] https://github.com/vyperlang/vyper/issues/2753#issuecomment-1092932248
- [x] https://github.com/vyperlang/vyper/pull/2768#issuecomment-1094354046

**Comment by charles-cooper** [comment]
leaving the memorymock tests for now

**Comment by fubuloubu** [comment]
Next: #2813
