### ISSUE TITLE
For giggles, can you try `METHOD_ID: constant(bytes4) = 0x12345678`?

### ISSUE THREAD

**Issue by Ash1818** [vyperlang/vyper#2770]
For giggles, can you try `METHOD_ID: constant(bytes4) = 0x12345678`?

_Originally posted by @fubuloubu in https://github.com/vyperlang/vyper/issues/2766#issuecomment-1092395441_

**Comment by charles-cooper** [comment]
reporting as spam

**Comment by fubuloubu** [comment]
Haha, what did you get when you tried it though?
