### ISSUE TITLE
Possibly incorrect calldata validation

### ISSUE THREAD

**Issue by hedgar2017** [vyperlang/vyper#2774]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.2
* OS: linux
* Python Version (output of `python --version`): 3.10.2

### What's your issue about?

The following code throws. We think it is one of validation checks, but you'll be able to tell for sure.

```
struct S:
    a: int16
    b: uint8
    c: bytes2
    
@external
@pure
def f(s: S) -> (uint256, uint256, uint256):
    return (convert(s.a, uint256), convert(s.b, uint256), convert(s.c, uint256))

# f((int16,uint8,bytes2)): 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff01, 0xff, "ab" -> 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff01, 0xff, "ab"
```

**Comment by charles-cooper** [comment]
Converting negative int16 to uint256 should revert. If you want to return the input bit-for-bit, you should convert to int256 to avoid the signedness change.
