### ISSUE TITLE
Bytes[N] and bytesN comparison (just to clarify)

### ISSUE THREAD

**Issue by hedgar2017** [vyperlang/vyper#2775]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.2
* OS: linux
* Python Version (output of `python --version`): 3.10.2

### What's your issue about?

```
@external
def f(a: bytes2, x: uint16) -> uint256:
    if a != b"ab":
        return 1
    return 0
```

This code produces the following error:
```
  contract "tests/vyper/external/cleanup/cleanup_bytes_types_v2.vy", function "f", line 4:7 
       3 def f(a: bytes2, x: uint16) -> uint256:
  ---> 4     if a != b"ab":
  --------------^
       5         return 1
```
It is only possible to use hex literals like `0xab`?

**Comment by charles-cooper** [comment]
That's right - b"ab" is inferred to have type `Bytes[2]`. You can `convert` Bytes[2] to bytes2, or use a hex literal.
