### ISSUE TITLE
Assignment bytestring to bytesN weird behavior

### ISSUE THREAD

**Issue by hedgar2017** [vyperlang/vyper#2778]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.2
* OS: linux
* Python Version (output of `python --version`): 3.10.2

### What's your issue about?

```
name: public(bytes6)

@external
def __init__():
    self.name = b"Celina"
```

After this, `self.name == 6`, the Celina's length!

**Comment by charles-cooper** [comment]
This should be blocked - it should not be possible to assign Bytes[6] directly to bytes6.
