### ISSUE TITLE
Initialization of DynArray blows up with literal.

### ISSUE THREAD

**Issue by scherrey** [vyperlang/vyper#2787]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.1+commit.0f9ff286
* OS: Linux squire 5.14.0-4mx-amd64 #1 SMP Debian 5.14.16-1~mx21+1 (2021-11-05) x86_64 GNU/Linux
* Python Version (output of `python --version`): Python 3.9.2

### What's your issue about?

Please include information like:

The following code blows up the vyper compiler with :
 ...
  File "vyper/codegen/stmt.py", line 153, in parse_Call
    assert arg.typ == darray.typ.subtype
AssertionError: 

```vyper
# @version 0.3.1

MAX_DEPTH: constant(uint8) = 6
struct Item:
    value: uint256
    holder: address


struct Node:
    key: Item
    prevNode: DynArray[int128, MAX_DEPTH]
    nextNode: DynArray[int128, MAX_DEPTH]

nodeLists: public(HashMap[uint256, Node])

@external
def __init__():
    #self.contractOperator = msg.sender
    #self.nextNodeId = 1

    # Initialize the zero terminus node.
    ZeroNode : Node = empty(Node) # self.nodeLists[0]
    ZeroValue : int128 = 0
    for i in range(MAX_DEPTH):
        ZeroNode.prevNode.append(ZeroValue)
        ZeroNode.nextNode.append(0)

    self.nodeLists[0] = ZeroNode

    assert convert(len(ZeroNode.prevNode), uint8) == MAX_DEPTH, "There is no ZeroNode.prevNode!"
```

### How can it be fixed?

If you replace the 'ZeroNode.nextNode.append(0)' with 'ZeroNode.prevNode.append(ZeroValue)' it works again.

**Comment by charles-cooper** [comment]
this was fixed in https://github.com/vyperlang/vyper/pull/2769

**Comment by scherrey** [comment]
Confirmed fixed in branch git+https://github.com/vyperlang/vyper@master-0.3.1
