### ISSUE TITLE
literal HashMap bytes4 key raises uncaught exception 

### ISSUE THREAD

**Issue by Doc-Pixel** [vyperlang/vyper#2809]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.2
* OS: LINUX
* Python Version (output of `python --version`): 3.8.10

### What's your issue about?
With the 0.3.2 version of vyper setting a value in a hashmap[bytes4,bool] no longer works.
This works in 0.3.1-master version.

What I tested:
- removing the constants and putting the actual values in the init function
- rolling back to 0.3.1-master lowering the version pragma in the contract back to 0.3.1 to double check and re-installing 0.3.2 / increasing the version pragma back to 0.3.2

Please include information like:

* full output of the error you received
`vyper.exceptions.TypeCheckFailure: Hex node did not produce IR. vyper.ast.nodes.Hex:
120 self.paused = False
---> 121 self.supportsInterfaces[ERC165_INTERFACE_ID] = True
-------------------------------------^
122 self.supportsInterfaces[ERC1155_INTERFACE_ID] = True
This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
https://github.com/vyperlang/vyper/issues/new?template=bug.md
`

* what command you ran
vyper compile

* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
```vyper
# @version >=0.3.2

# mappings
supportsInterfaces: HashMap[bytes4, bool] 

# Interface IDs
ERC165_INTERFACE_ID: constant(bytes4)  = 0x01ffc9a7
ERC1155_INTERFACE_ID: constant(bytes4) = 0xd9b67a26
ERC1155_INTERFACE_ID_METADATA: constant(bytes4) = 0x0e89341c

@external
def __init__():
   
    self.supportsInterfaces[ERC165_INTERFACE_ID] = True
    self.supportsInterfaces[ERC1155_INTERFACE_ID] = True
    self.supportsInterfaces[ERC1155_INTERFACE_ID_METADATA] = True
```
* please try running your example with the --debug flag turned on

**Comment by charles-cooper** [comment]
The root of this issue is a bug in type inference -- in `self.some_map[k]`, the inferred type of `k` is incorrect. This leads to an assertion failure during codegen.

In the meantime, a workaround for this particular use case (which has better performance characteristics anyway!) is to use `interface in SUPPORTED_INTERFACES`:
```vyper
SUPPORTED_INTERFACES: constant(bytes4[3]) = [0x01ffc9a7, 0xd9b67a26, 0x0e89341c]

...

def supportsInterface(interface_id: bytes4) -> bool:
    return interface_id in SUPPORTED_INTERFACES
```

**Comment by charles-cooper** [comment]
fixed in https://github.com/vyperlang/vyper/pull/2810
