### ISSUE TITLE
VIP: `default` kwarg for external contract calls

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2812]
## Simple Summary
add a "default" kwargs for dealing with external contracts which don't conform to their interface

## Motivation
We might want to add a "default" returnvalue to calls (specific name of keyword subject to bikeshedding). This is a more general mechanism for dealing with contracts which return less data than expected, so we do not have to add a builtin for every ERC20 (or, could be other standards) function implementation which is buggy. something like
```vyper
ExternalContract(msg.sender).some_function(<args>, default=False)
```

The compiler can issue code to fill the return buffer with the `default` value if `returndatasize` is empty.

_Originally posted by @charles-cooper in https://github.com/vyperlang/vyper/issues/2753#issuecomment-1092932248_

## Specification

TBD

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
rename `default=` to `default_empty_returndata=` or something?

**Comment by charles-cooper** [comment]
maybe `if_empty_returndata`? e.g.

```
some_contract.foo(1, if_empty_returndata=5)
```

**Comment by fubuloubu** [comment]
Implemented in #2839

**Comment by PatrickAlphaC** [comment]
Could we add this in the docs? I only learnt about it by coming to the VIP.

love this btw

**Comment by charles-cooper** [comment]
yes -- PRs welcome btw!
