### ISSUE TITLE
VIP: `.vyi` files

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2814]
should it look more like this?

```py
@external
def my_method(foo: DynArray[uint256, ...]):
    ...
```

where `...` is the actual Python elipsis AST node and represents letting the downstream use case decide what the value is that goes there

**Comment by charles-cooper** [comment]
dropping this here because it seems related https://github.com/vyperlang/vyper/issues/1944

**Comment by charles-cooper** [comment]
dropping this here because it seems related https://github.com/vyperlang/vyper/issues/1944

**Comment by charles-cooper** [comment]
i like the use of ellipses - also to mark the body of the function as unimplemented (which can be a syntactic difference between `.vyi` and `.vy` files)

**Comment by charles-cooper** [comment]
done in #3663
