### ISSUE TITLE
Missing error message for type mismatch inside a built-in type (min/max).

### ISSUE THREAD

**Issue by scherrey** [vyperlang/vyper#2827]
### Version Information

* `vyper Version (output of `vyper --version`): 0.3.1+commit.2bf43eee and later up to 0.3.3`
* `OS: Linux squire 5.14.0-4mx-amd64 #1 SMP Debian 5.14.16-1~mx21+1 (2021-11-05) x86_64 GNU/Linux`
* `Python 3.9.2`

### What's your issue about?
Compiler dies with weird/broken error message and no line number information to help identify where it broke.

```
$ brownie test tests/test_auction.py 
Brownie v1.18.1 - Python development framework for Ethereum

Compiling contracts...
  Vyper version: 0.3.1+commit.2bf43eee
Unhandled exception in 'contracts/auction.vy':
TypeMismatch: Error Message not found.


ERROR: Unable to load project
```

happens if you try to compile the following:
```
$ cat vyper-error.vy 
# @version 0.3.1

@external 
def broken():
    a : uint256 = 3
    b : int128 = 4

    # Error occurs because of b's type is inconsistent with a & c.
    # This code works :
    # c : uint256 = (min(a, convert(b, uint256))+1)/2
    c : uint256 = (min(a, b)+1)/2

```

Appears to be a problem figuring out the right error to report when in the context of the min or max functions. Possibly all built-in's but haven't tried the rest.

**Comment by fubuloubu** [comment]
related to this: #2788
