### ISSUE TITLE
Type of integer constant is ignored during folding of literal ops

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#2830]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.3
* OS: Linux
* Python Version (output of `python --version`): 3.8.5

### What's your issue about?

Please include information like:

This contract compiles when it should throw a typechecking error.
```
a: constant(uint16) = 200

@external
def foo() -> int16:
	return a - 201
```

### How can it be fixed?

Annotate the folded nodes with the original type information.

**Comment by tserg** [comment]
This also compiles, when it should not:
```
a: constant(uint16) = 200
b: constant(int248) = 100

@external
def foo() -> int16:
    return a - b
```

**Comment by tserg** [comment]
This also compiles, when it should not:
```
a: constant(uint8) = 255
b: constant(uint8) = 1

@external
def foo() -> uint8:
	return a + b
```

**Comment by tserg** [comment]
Another example:
```
a: constant(int8) = 25
b: constant(uint8) = 38

@external
def foo() -> bool:
	return a < b
```

**Comment by trocher** [comment]
Might be redundant with your example, but I got this one which is compiling:
```Vyper
a:constant(uint256)=1
b:constant(uint16)=a+1
```

**Comment by tserg** [comment]
> Might be redundant with your examples, but I got this one which is compiling:
> 
> ```vyper
> a:constant(uint256)=1
> b:constant(uint16)=a+0
> ```
> 
> Where this one does not:
> 
> ```vyper
> a:constant(uint256)=1
> b:constant(uint16)=a
> ```

Cool! I will add both examples as test cases to #3201.

**Comment by ToonVanHove** [comment]
As a side note, this also causes some funky stuff when used as array index:

```vyper
CONST: constant(int128) = 1

@external
def foo():
    array: uint256[10] = empty(uint256[10])
    a: int128 = 1

    array[a + CONST] = 20
```

When compiled this results in an AssertionError that is supposed to be unreachable.

**Comment by trocher** [comment]
> As a side note, this also causes some funky stuff when used as array index:
> 
> ```vyper
> CONST: constant(int128) = 1
> 
> @external
> def foo():
>     array: uint256[10] = empty(uint256[10])
>     a: int128 = 1
> 
>     array[a + CONST] = 20
> ```
> 
> When compiled this results in an AssertionError that is supposed to be unreachable.

Interesting, for this one it seems that the typechecker allows `a + CONST` to be any integer types but when annotating `a + CONST` is given type `uint256`, it annotate `a` with its `int128` type but `visit_Constant` annotates `CONST` with the `uint256` obtained from the `subscript`'s value type and does not care about its annotation obtained from folding..

**Comment by charles-cooper** [comment]
i think this was solved during recent refactoring of constant folding (see https://github.com/vyperlang/vyper/pull/3669 and https://github.com/vyperlang/vyper/pull/3719). @ToonVanHove @trocher please reopen if there are still any issues.
