### ISSUE TITLE
DynArray public getters require index as argument

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2836]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.3
* OS: linux
* Python Version (output of `python --version`): 3.9.9

### What's your issue about?

contract:
```vyper
my_list: public(DynArray[uint256, 10])
```

python script:
```py
assert contract.my_list() == []  # Raises ABI encoding error about requiring 1 arg to getter
```

**Comment by charles-cooper** [comment]
is this a bug? it is the same behavior as static arrays.

**Comment by fubuloubu** [comment]
> is this a bug? it is the same behavior as static arrays.

Maybe not a bug persay, but yeah it is strange behavior because I would expect a public getter to just return the full array

**Comment by charles-cooper** [comment]
meeting notes: stick with existing behavior
