### ISSUE TITLE
Obscure message for UnimplementedException

### ISSUE THREAD

**Issue by matiasbattocchia** [vyperlang/vyper#2840]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.3
* OS: linux
* Python Version (output of `python --version`): 3.9.12

### What's your issue about?

Arithmetic operator are only implemented for `uint8` and `uint256` but the compiler could not tell it when using the addition assignment (`+=`).

```vyper
sum: uint16 = 0
equities: uint16[3] = [1, 2, 3]

for equity in equities:
    sum += equity
```
```sh
$ brownie compile

vyper.exceptions.UnimplementedException: <exception str() failed>
```

Then changed code to

```vyper
sum: uint16 = 0
equities: uint16[3] = [1, 2, 3]

for equity in equities:
    sum = sum + equity
```

and finally could spot the problem.

```sh
$ brownie compile

vyper.exceptions.UnimplementedException: Not implemented: uint16 + uint16
  contract "contracts/DaiCell.vy", function "__init__", line 25:14 
       24     for equity in equities:
  ---> 25         sum = sum + equity
```

**Comment by charles-cooper** [comment]
well, the solution is to implement it :)

tracking in https://github.com/vyperlang/vyper/issues/2786
