### ISSUE TITLE
Meeting May 16 2022

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2846]
Start time: 20:00 UTC (https://time.is/UTC)

Vidchat link: https://meet.jit.si/VyperPlanningMeeting

Agenda:

- [x] bikeshed: https://github.com/vyperlang/vyper/issues/2836
- [x] bikeshed: https://github.com/vyperlang/vyper/issues/2803
- [x] VIP: https://github.com/vyperlang/vyper/issues/2847
- [x] discuss: https://github.com/vyperlang/vyper/pull/2852#issuecomment-1126124887
- [x] https://github.com/vyperlang/vyper/issues/2856

**Comment by fubuloubu** [comment]
Next: #2857
