### ISSUE TITLE
Meeting Jun 6 2022

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#2857]
Start time: 15:30 UTC (https://time.is/UTC)

Vidchat link: https://meet.jit.si/VyperPlanningMeeting

Agenda:

- [x] https://github.com/vyperlang/vyper/issues/2733
- [x] https://github.com/vyperlang/vyper/issues/2897
- [x] https://github.com/vyperlang/vyper/issues/2890
- [x] https://github.com/vyperlang/vyper/issues/2891
- [x] https://github.com/vyperlang/vyper/issues/2892
- [x] interpret code as initcode or runtime code https://github.com/vyperlang/vyper/pull/2889
- [x] https://github.com/vyperlang/vyper/issues/2893
- [x] change black line length setting to 80 chars
- [x] forward_all_calldata_to (delegatecall use case)
- [x] 0.3.4 release - what needs to be done
- [ ] (time permitting) https://github.com/vyperlang/vyper/issues/2316
- [ ] Add agenda item here

**Comment by charles-cooper** [comment]
meeting notes:
- convert test suite to ape
- we are ready for custom parser - to keep ourselves honest, continue to test that files are parseable with python parser (subject to single pass syntactic transform like we currently do in https://github.com/vyperlang/vyper/blob/90e3d20c9c9099101492514135b8677dcbf2be10/vyper/ast/pre_parser.py)

**Comment by charles-cooper** [comment]
next: https://github.com/vyperlang/vyper/issues/2898

**Comment by charles-cooper** [comment]
> Is this for the entire test suite? I recall it was discussed with reference to the `examples` directory during the meeting.

let's start with the `examples/` directory

**Comment by fubuloubu** [comment]
> > convert test suite to ape (can use jinja to parametrize contracts)
> 
> Is this for the entire test suite? I recall it was discussed with reference to the `examples` directory during the meeting.

Yes, start with `examples`, eventually port over dynamic test cases (static "compile only" and exception tests) don't require any of it.

The nice thing is to be able to configure the backend used for testing, so can start with eth-tester (which we use today) and switch over foundry (much faster) for that type of testing. It also let's you add other compilers, so can create compatibility tests with Solidity as well.

**Comment by tserg** [comment]
Got it. If I understood correctly, it can be broken down into the following steps/PRs (for future reference):
1. Convert `examples/` directory in test suite to use Ape with existing eth-tester backend.
2. Convert dynamic test cases in rest of the test suite to use Ape with existing eth-tester backend.
3. Switch backend from eth-tester to Foundry/Anvil.
4. Add compatibility tests.

**Comment by fubuloubu** [comment]
> Got it. If I understood correctly, it can be broken down into the following steps/PRs (for future reference):
> 
> 1. Convert `examples/` directory in test suite to use Ape with existing eth-tester backend.
> 2. Convert dynamic test cases in rest of the test suite to use Ape with existing eth-tester backend.
> 3. Switch backend from eth-tester to Foundry/Anvil.
> 4. Add compatibility tests.

Yep, that sounds about correct. Note that I'm not sure how well the xdist support will work, ape currently does not support xdist but it shouldn't affect non-ape tests. eth-tester might even work better w/ xdist because it's all an in-memory process. For CI though, it will definitely be faster to use Foundry, it's all single-threaded anyways.
