### ISSUE TITLE
VIP: Add type byte or another solution that allows the creation of a true dynamic size array of type byte(ABI bytes)

### ISSUE THREAD

**Issue by onlymaresia** [vyperlang/vyper#2869]
## Simple Summary
Add type ```byte``` or another solution that allows the creation of a true dynamic size array of type byte.

## Motivation
Currently, a fixed-length array is used to generate the ABI for type ```bytes```. In version 0.3.2 the dynamic array was introduced and this is a good opportunity to create a more natural way of creating a dynamic array of type ```byte```.

Current solution that compiles bytes using a fixed-length array:
```vyper
@external
def onERC721Received(_operator: address, _from: address, _tokenId: uint256, _data: Bytes[4096]) -> bytes4:
    return empty(bytes4)
```

Possible solution using type ```byte```:
```vyper
@external
def onERC721Received(_operator: address, _from: address, _tokenId: uint256, _data: DynArray[byte, 1]) -> bytes4:
    return empty(bytes4)
```

Possible solution using type ```bytes```:
```vyper
@external
def onERC721Received(_operator: address, _from: address, _tokenId: uint256, _data: bytes) -> bytes4:
    return empty(bytes4)
```

Reference: [byte arrays doc](https://vyper.readthedocs.io/en/stable/types.html#byte-arrays)

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by charles-cooper** [comment]
`Bytes[4096]` has ABI type `bytes`. The `4096` indicates an upper bound on the bytestring length, not the actual (runtime) length, which is dynamic.

**Comment by charles-cooper** [comment]
@onlymaresia wondering if this answers your question? or is there still some use case that's not addressed?
