### ISSUE TITLE
discussion: contract factories

### ISSUE THREAD

**Issue by nmushegian** [vyperlang/vyper#2883]
I must be missing something obvious, how do I do `new MyContract()` from inside a contract? I can't find any reference in the docs or in the issues... A language that can't make factories is a non-starter IMO and the forwarder pattern adds gas overhead to the deployed object

**Comment by nmushegian** [comment]
On second thought forcing everyone to use a generic multifactory where we log the constructor bytes might actually be a good idea!!

**Comment by michwill** [comment]
Maybe you are looking for `create_forwarder_to`. Which, though, is not create2

https://vyper.readthedocs.io/en/stable/built-in-functions.html#chain-interaction

**Comment by nmushegian** [comment]
I saw that, but that is not what I am looking for, I am looking for regular `CREATE` opcode

**Comment by nmushegian** [comment]
A multi factory is not the same as a proxy, I want to actually make objects without the overhead

A similar pattern to forwarder could be “copier” which deploys a copy of code using EXTCODECOPY (whatever it’s called) at given address provided

**Comment by nmushegian** [comment]
5 out of 5 people I have asked for a way to create contracts in vyper and not use a forwarded have shown me the forwarder, it is pretty remarkable how bad I am at communicating

**Comment by nmushegian** [comment]
https://github.com/ricobank/multifab

I will close this now and make a new issue when we could maybe add this similar to forwarding contract that is currently built in

**Comment by fubuloubu** [comment]
Typically I suggest just deploying separately, because it's just a huge waste of space to store one contract in another.

The link you shared is really interesting though, and might be a good idea for a built in function

**Comment by charles-cooper** [comment]
maybe worth a new builtin, either `create_copy_of(code_at: address)` or create(bytecode: Bytes)`. @nmushegian thoughts?

**Comment by nmushegian** [comment]
I think both would be good, maybe for these it makes sense just expose a typed version of select opcodes like `create`, `create2`, `codecopy`, I think all approaches have merits here I just *need* the ability to create new contracts from other contracts, defaulting to big multifactory right now

**Comment by nmushegian** [comment]
Maybe generating 1 factory alongside each contract is a good approach too, then that factory defines the type

**Comment by charles-cooper** [comment]
> Maybe generating 1 factory alongside each contract is a good approach too, then that factory defines the type

can you sketch this a bit more?

**Comment by charles-cooper** [comment]
also related: https://github.com/vyperlang/vyper/issues/2891

**Comment by nmushegian** [comment]
```
- maybe a comparison table of approaches would be useful
	- costs for build, call, and original setup if applicable
	- regular CREATE/CREATE2
		- setup: makes parent contract deploy more expensive
		- build: direct create with bytes
		- call: lowest overhead
	- deploy forwarder
		- setup: target needs to be deployed / exist
		- build: deploy tiny proxy
		- call: DELEGATECALL overhead
	- build from factory
		- setup: need to deploy object per-factory
		- build: call to factory overhead
		- call: lowest overhead
	- build from multifab
		- setup: need to deploy multifab, and add type
		- build: call to multifab overhead
		- call: lowest overhead
	- EXTCODECOPY
		- setup: target contract must exist
		- build: copy overhead
```

**Comment by charles-cooper** [comment]
@nmushegian nice table -- can you expand on what a multifab is in your terminology?
