### ISSUE TITLE
bug: jinja2 import error when running make docs

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#2885]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.4+
* OS: Linux
* Python Version (output of `python --version`): 3.8.13 and 3.9.12

### What's your issue about?

Running `make docs` gives an import error
```
ImportError: cannot import name 'contextfunction' from 'jinja2' (/home/user/miniconda3/envs/vyper/lib/python3.9/site-packages/jinja2/__init__.py)
```

See https://github.com/readthedocs/readthedocs.org/issues/9037

### How can it be fixed?

Pin `jinja2` version to `3.0.0`.

**Comment by charles-cooper** [comment]
weird - i have jinja 3.1.1 and docs work fine
```
$ pip freeze | grep -i jinja
Jinja2==3.1.1
```
maybe try upgrading your sphinx?

**Comment by charles-cooper** [comment]
@tserg is this still an issue?

**Comment by tserg** [comment]
No, not sure why this error arose in that specific instance but I have not encountered it since. Closing this issue.
