### ISSUE TITLE
VIP: rename `create_forwarder_to` to `create_minimal_proxy_to`

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#2893]
## Simple Summary
As title. Rename the builtin `create_forwarder_to` to `create_minimal_proxy_to`.

## Motivation
In the past, `create_forwarder_to` was chosen over `proxy` terminology (see https://github.com/vyperlang/vyper/issues/1177#issuecomment-465603700). However, I think these days, `proxy` is a more standard terminology when talking about smart contracts. Plus, the implementation of `create_forwarder_to()` was changed in #2281 to use EIP-1167 - the terminology in the EIP only mentions "proxies", not "forwarders", so we should be consistent with the EIP terminology.

## Specification
Rename `create_forwarder_to` to `create_minimal_proxy_to`

## Backwards Compatibility
Breaking change

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
There are many different types of proxies, forwarder style proxies are just one kind

**Comment by charles-cooper** [comment]
> There are many different types of proxies, forwarder style proxies are just one kind

the title of EIP 1167 is "Minimal Proxy Contract" - https://eips.ethereum.org/EIPS/eip-1167

**Comment by charles-cooper** [comment]
meeting notes: use `create_minimal_proxy_to` (mirrors EIP1167 terminology)
