### ISSUE TITLE
`vyper.exceptions.InvalidType` error for nested structs

### ISSUE THREAD

**Issue by Saw-mon-and-Natalie** [vyperlang/vyper#2912]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.4+commit.58a5ae5d
* OS: win
* Python Version (output of `python --version`): 3.10.0b3

### What's your issue about?

The Vyper compiler gives a `vyper.exceptions.InvalidType` when using a struct `B` in struct `A` in the following example:

```vyper
# @version 0.3.4

struct A:
    a: B

struct B:
    b: uint256
```

```bash
Error compiling: nested-structs.vy
vyper.exceptions.InvalidType: B
  contract "nested-structs.vy", line 4:7
       3 struct A:
  ---> 4     a: B
  --------------^
       5
```

Defining struct `B` before struct `A` fixes the error. So the error depends on the ordering of the definitions.

**Comment by charles-cooper** [comment]
this was fixed as of 3abe588e05be6f6cbfac283739d797ef6c485756
