### ISSUE TITLE
Add nightly build for Vyper

### ISSUE THREAD

**Issue by Saw-mon-and-Natalie** [vyperlang/vyper#2913]
Having nightly builds as part of GitHub workflows would allow integrating the new unreleased features with other tools. As an example, one can use the nightly builds with `@nomiclabs/hardhat-vyper` plugin.

**Comment by charles-cooper** [comment]
@Saw-mon-and-Natalie what is the best distribution channel for these? we already have continuous docker builds and wondering if that works for this use case - https://hub.docker.com/r/vyperlang/vyper. or do we need a continually updated, "nightly" github release?

**Comment by Saw-mon-and-Natalie** [comment]
I think an additional GitHub nightly release would be nice. That might make it really easy for example with `hardhat-vyper` plugin to pull the nightly without changing any of the plug-in implementation.

**Comment by charles-cooper** [comment]
we could have a special release tagged "pre-release" which we automatically update every commit to `master`.

**Comment by charles-cooper** [comment]
> we could have a special release tagged "pre-release" which we automatically update every commit to `master`.

i created https://github.com/vyperlang/vyper/releases/tag/pre-release, maybe we can auto-update it every commit to master

**Comment by Saw-mon-and-Natalie** [comment]
I've created a GitHub workflow for the pre-release. Probably will make a PR for it tonight.

**Comment by charles-cooper** [comment]
i deleted the release because, unfortunately, it breaks brownie:

![Screenshot from 2022-06-17 16-51-36](https://user-images.githubusercontent.com/3867501/174399552-81b249b8-0460-486d-94dc-a5aa3a9cbd9e.png)

i did not test hardhat or ape, i'm curious how we can publish this pre-release version without affecting dev frameworks.

**Comment by Saw-mon-and-Natalie** [comment]
We could also use a tag like `x.y.z-pre-release` where `x.y.z` is the next semver version (adding 1 to the patch version number).

**Comment by fubuloubu** [comment]
> i deleted the release because, unfortunately, it breaks brownie:
> 
> ![Screenshot from 2022-06-17 16-51-36](https://user-images.githubusercontent.com/3867501/174399552-81b249b8-0460-486d-94dc-a5aa3a9cbd9e.png)
> 
> i did not test hardhat or ape, i'm curious how we can publish this pre-release version without affecting dev frameworks.

tbh in `ape` it works perfectly fine installing from any git branch via pypi

**Comment by Saw-mon-and-Natalie** [comment]
The workflow in PR #2920 can aslo be customized futher to specifiy a custom `tag_name`. Based on my findings from the different version comparisons, we have:

- ✔ `hardhat-vyper` plugin uses [`semver`](https://www.npmjs.com/package/semver), so tags like `0.3.4-pre-release` would work.
- ✔ `Brownie` and `Ape` use [`semantic_version`](https://github.com/rbarrois/python-semanticversion/) which would also allow a tag like  `0.3.4-pre-release`
- ⛔ `Vyper`'s `setup` uses ` setuptools_scm` which tries to implement `PEP440` and does not allow for tags like `0.3.4-pre-release`, but accepts tags like `0.3pre4`. If we go by the `0.3.4-pre-release` pattern, we can probably strip the end `pre-release` in [`_global_version(version)`](https://github.com/vyperlang/vyper/blob/master/setup.py#L50-L56) before feeding it to `use_scm_version`

**Comment by Saw-mon-and-Natalie** [comment]
Added a new commit to #2920 to unify the `pre-release` tag format. Now the `x.y.z-pre-release` format should work across the board. Already tested the `Vyper` setup and `hardhat-vyper` plugin and they work.

We needed to modify the `setup.py` to make it work:

```py
setup(
   ...
   use_scm_version={
   ...
      "tag_regex": r"^(?:[\w-]+-)?(?P<version>[vV]?\d+(?:\.\d+){0,2}[^-\+]*)(?:[-\+].*)?$"

```

By modifiying the [`DEFAULT_TAG_REGEX`](https://github.com/pypa/setuptools_scm/blob/main/src/setuptools_scm/config.py#L13) in `setuptools_scm` we make sure the ther `version` part doesn't pick up `-` character and the suffix after the `version` portion can start with either `-` or `+`.

`Vyper` contracts can have a pragma version tag like:

```vyper
# @version 0.3.4-pre-release
a: uint256
```

and for `hardhat` projects, the `hardhat.config.js` file would look like this:

```js
require("@nomiclabs/hardhat-vyper");

module.exports = {
  vyper: {
    version: "0.3.4-pre-release",
  },
};
```

**Comment by charles-cooper** [comment]
very cool! my one concern with this is that, pragmas like `version >= 0.3.3` will get compiled with a pre-release version. does the `pre-release` suffix eliminate that possibility for all build tools?

**Comment by Saw-mon-and-Natalie** [comment]
@charles-cooper , great point. I'll have to check that.

**Comment by charles-cooper** [comment]
we are now publishing builds to https://github.com/vyperlang/vyper-builds/, also all docker builds are available [through GHCR](https://github.com/vyperlang/vyper/pkgs/container/vyper) as of https://github.com/vyperlang/vyper/pull/3435
