### ISSUE TITLE
VSCode gives a warning/problem icon in `conf.py`

### ISSUE THREAD

**Issue by krakxn** [vyperlang/vyper#2995]
## Description

When I cloned the repo, VSCode gives a warning/problem indicator as so:

*Context -- The snippet is taken from path: ./docs/conf.py*
*where `.` refers to the repo.*

![image](https://user-images.githubusercontent.com/108299225/181360675-2b76d1b8-a762-4439-a193-3e3f529ac805.png)

Certain it is not much, but worth looking at -- just in case it was a mistake.

**Comment by sorXCode** [comment]
The error is related to [missing dependency](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules:~:text=reportMissingImports) after cloning the repo. If you hover over the error's squiggly lines, you would likely see a message like this

> Import "recommonmark.parser" could not be resolved

To fix this you can install dependencies in the `requirements-docs.txt` file, which includes "recommonmark", using this command from the repo root.

`pip install -r requirements-docs.txt`

**Comment by krakxn** [comment]
Thank you!
