### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by merc1er** [vyperlang/vyper#2997]
### What's your issue about?

The link to NPM's semantic versioning docs is broken ([404](https://docs.npmjs.com/misc/semver)) in the ["Structure of Contract" page](https://vyper.readthedocs.io/en/stable/structure-of-a-contract.html#version-pragma). [Permalink on GitHub](https://github.com/vyperlang/vyper/blame/f31f0ec406bbbd2055f125abd17278e3ac2ed84f/docs/structure-of-a-contract.rst#L15).

<img width="883" alt="Screenshot 2022-07-28 at 10 23 27" src="https://user-images.githubusercontent.com/21960643/181394525-5900d586-c72c-419f-9dbc-1b16993fc978.png">

### How can it be fixed?

Was this page moved to https://docs.npmjs.com/about-semantic-versioning? If so, I can create a PR replacing the link.

**Comment by charles-cooper** [comment]
not exactly, see https://web.archive.org/web/20190303042351/https://docs.npmjs.com/misc/semver. but i think the about-semantic-versioning link you posted is an acceptable replacement - please open a PR!

**Comment by charles-cooper** [comment]
fixed in #3007
