### ISSUE TITLE
can't declare variable `public` but can define custom getter

### ISSUE THREAD

**Issue by nmushegian** [vyperlang/vyper#3016]
### Version Information

* vyper Version:  0.3.4+commit.f31f0ec
* OS: osx
* Python Version: 3.8.9

### What's your issue about?

This code fails to compile:

```
slates : public(HashMap[bytes32, DynArray[address, 15]])
```

but I can define my own getter for that type just fine:

```
slates : HashMap[bytes32, DynArray[address, 15]]

@external
def slate(sid :bytes32) -> DynArray[address, 15]:
   return self.slates[sid]
```

**Comment by nmushegian** [comment]
I realize now it is ambiguous whether the getter should take 1 or 2 args (return a dynarray or address). Maybe this is intended behavior?

**Comment by charles-cooper** [comment]
not intended behavior. there is an open issue about the ambiguity, but this is a typechecker bug

**Comment by charles-cooper** [comment]
for future reference -- this raises the following
```
vyper.exceptions.InvalidType: DynArray
  contract "repros/3016.vy", function "slates", line 1:33 
  ---> 1 slates : public(HashMap[bytes32, DynArray[address, 15]])
  ----------------------------------------^
       2
```

**Comment by charles-cooper** [comment]
`git bisect` indicates this was introduced in be2c59a604070c75212dca90beb4c33fed908c8b

**Comment by charles-cooper** [comment]
re. the ambiguity, linking here for reference https://github.com/vyperlang/vyper/issues/2897
