### ISSUE TITLE
Online compiler

### ISSUE THREAD

**Issue by yann300** [vyperlang/vyper#3025]
fetching the online compiler from the browser isn't working anymore. 
It seems CORS has been removed, is this possible to readd it?

```
Access to fetch at 'https://vyper.live/compile' from origin 'https://vyper.dyn.plugin.remixproject.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by yann300** [comment]
hello @charles-cooper could you help us in this?
https://vyper.live/compile is being used by remix.ethereum.org and it is at the moment broken (it was fine 3 days ago)
thanks very much

**Comment by m0ham3dx** [comment]
> hello @charles-cooper could you help us in this? https://vyper.live/compile is being used by remix.ethereum.org and it is at the moment broken (it was fine 3 days ago) thanks very much

You can compile `vyper` - `.vy` directly in [remix](https://remix.ethereum.org/) --> [ScreenShot](https://ibb.co/rv6P7ZL)

**Comment by yann300** [comment]
@m0ham3dx yes but the api endpoint ( https://vyper.live/compile ) is broken. so it isn't working anymore even in Remix.

**Comment by ngmisl** [comment]
Online compiler works again in remix, but local via vyper serve gives out errors (still?)

**Comment by yann300** [comment]
@ngmisl you mean compilation errors?

**Comment by yann300** [comment]
we have setup our own api endpoint.
