### ISSUE TITLE
send() function don't pass exception return data

### ISSUE THREAD

**Issue by AntonD3** [vyperlang/vyper#3056]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.3
* OS: macOS
* Python Version (output of `python --version`): 2.7.16

#### Source codes:

A.vy:
```
@external
@payable
def __default__():
    raise "no_receive"

```
C.vy:
```
import A as A

a: A

@external
def __init__(_a: address):
    self.a = A(create_forwarder_to(_a))

@external
@payable
def __default__():
    pass

@external
def f():
    send(self.a.address, as_wei_value(1, "wei"))

```

#### Problem

If set balance of contract C to 10 wei(for example) and call f(), it will return an exception with empty return data (But fallback in contract A reverts with string).

**Comment by charles-cooper** [comment]
this is expected behavior because the stipend for `send()` is 0 gas. leaving this issue open though since we may want to make the stipend configurable.

**Comment by charles-cooper** [comment]
superseded by https://github.com/vyperlang/vyper/issues/3060
