### ISSUE TITLE
cannot declare constant address

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3062]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.5+commit.c71b0238
* OS: Linux
* Python Version (output of `python --version`): 3.9.12

### What's your issue about?

Please include information like:

Declaring a constant address raises an InvalidType error - expected address but literal can only be cast as bytes20
```
FOO: constant(address) = 0x3cd751e6b0078be393132286c442345e5dc49699
```

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by tserg** [comment]
oops address needs to be checksummed.

**Comment by charles-cooper** [comment]
Error message could maybe be improved tho, ex "(did you mean {check summed address}?)"
