### ISSUE TITLE
In ERC721 token standard EIP, onERC721Received isn't annotated as view type

### ISSUE THREAD

**Issue by rmurray2** [vyperlang/vyper#3066]
* vyper Version (output of `vyper --version`): 0.3.4+commit.f31f0ec
* OS: linux
* Python Version (output of `python --version`): 3.8.3

The ERC721 example token standard in examples/tokens/ERC721.vy has an interface, `ERC721Receiver`, with a function, `onERC721Received`, that is annotated with `view`, but in the ERC721 token standard [EIP](https://eips.ethereum.org/EIPS/eip-721), `onERC721Received` is not annotated with `view`

**Comment by fubuloubu** [comment]
This is indeed a bug, this should be a state-modifying callback to the receiver. Would you mind creating a PR?

**Comment by rmurray2** [comment]
fixed [here](https://github.com/vyperlang/vyper/pull/3076)
