### ISSUE TITLE
company.vy

### ISSUE THREAD

**Issue by ngmisl** [vyperlang/vyper#3067]
Trying to compile the example: 
`Function not declared yet (reminder: functions cannot call functions later in code than themselves): _stockAvailable `

**Comment by charles-cooper** [comment]
what version of vyper are you using? generally you need to use the same version as you are pulling the examples folder from

**Comment by ngmisl** [comment]
Remxi and remote compiler

**Comment by charles-cooper** [comment]
what is the version of the remote compiler?

**Comment by ngmisl** [comment]
@charles-cooper good question... Whatever  remix feels is good enough? Or whoever runs the plugin
