### ISSUE TITLE
trying to compile conracts with built-in ERC20, but it's unrecognized

### ISSUE THREAD

**Issue by SureEdding** [vyperlang/vyper#3073]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.1
* OS: osx
* Python Version (output of `python --version`): python 3.9

### What's your issue about?
compiling issue. 
while i am tring to compile this contract: https://github.com/yearn/veYFI/tree/master/contracts 
it said the built-in ERC20 is Unrecognized

Please include information like:
```
➜  ve-contracts git:(main) ✗ vyper vyper_contracts/VotingYFI.vy          
Error compiling: vyper_contracts/VotingYFI.vy
vyper.exceptions.CompilerPanic: Unrecognized type ERC20

This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
https://github.com/vyperlang/vyper/issues/new?template=bug.md
```

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by cairoeth** [comment]
Compiled with Vyper v0.3.4 and Python 3.9.12 with no issues — try to use 0.3.4 instead of 0.3.1
