### ISSUE TITLE
Compiler panic when importing interfaces with `max_value()` as a default argument value

### ISSUE THREAD

**Issue by hadfieldn** [vyperlang/vyper#3077]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.6
* OS: osx
* Python Version (output of `python --version`): 3.9.8

### What's your issue about?

Please include information like:

* full output of the error you received
* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* please try running your example with the `--verbose` flag turned on

When a contract has a function that uses `max_value(uint256)` as a default argument value, it causes a compiler panic when it is imported as an interface:

```vyper
# ContractB.vy (compiles successfully)

@view
@external
def foo(_max: uint256 = max_value(uint256)) -> uint256:
    return _max

```

```vyper
# ContractA.vy (fails to compile)

import ContractB as ContractB
```

Compiling ContractA results in a compile error:
```console
$ vyper ContractA.vy
Error compiling: ContractA.vy
vyper.exceptions.CompilerPanic: max_value should always be folded

This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
```

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by hadfieldn** [comment]
The same failure occurs when the default value is `min_value(uint256)`, but it succeeds with `empty(uint256)`.

**Comment by hadfieldn** [comment]
As a workaround, if I declare a constant for the default value, it works, but I have to declare the same constant in the contract doing the import:

```vyper
# ContractB.vy (compiles successfully)

# `MAX_UINT256` is deprecated, so we use `_MAX_UINT256`
_MAX_UINT256: constant(uint256) = max_value(uint256)


@view
@external
def foo(_max: uint256 = _MAX_UINT256) -> uint256:
    return _max
```

Fails unless `_MAX_UINT256` is declared in ContractA:
```vyper
# ContractA.vy 

import ContractB as ContractB
```
```console
$ vyper ContractA.vy
Error compiling: ContractA.vy
vyper.exceptions.UndeclaredDefinition: '_MAX_UINT256' has not been declared.
  contract "ContractB", function "foo", line 9:24
       8 @external
  ---> 9 def foo(_max: uint256 = _MAX_UINT256) -> uint256:
  -------------------------------^
      10     return _max

```
Succeeds:
```vyper
# ContractA.vy 

import ContractB as ContractB

_MAX_UINT256: constant(uint256) = max_value(uint256)
```

```console
$ vyper ContractA.vy
0x61000d61000f60003961000d6000f3a165767970657283000306000b
```

**Comment by charles-cooper** [comment]
whoa, that also seems like a bug. you should not be able to override constants in the imported contract from the importing contract.

**Comment by hadfieldn** [comment]
Also works if I declare the interface inline:

```vyper
# ContractA.vy (compiles successfully)

interface ContractB:
    def foo(_max: uint256 = max_value(uint256)) -> uint256: view
```

**Comment by hadfieldn** [comment]
Related to the need to redeclare constants locally, but probably a separate issue -- if the imported contract references a struct in its function signatures, I also have to declare that Struct in the importing contract. 

(I know this was reported in https://github.com/vyperlang/vyper/issues/2670)
