### ISSUE TITLE
Loosen `semantic-version` lib version restriction

### ISSUE THREAD

**Issue by unparalleled-js** [vyperlang/vyper#3103]
### Version Information

* vyper Version (output of `vyper --version`): from main branch
* OS: macOS
* Python Version (output of `python --version`): 3.9
 
### What's your issue about?

Currently, `titanaboa` uses vyper as a dependency.
And vyper has a strict pin on `semantic-version` lib.
This causes conflicts with other packages in the ecosystem, such as `py-tokenlists`, which is used by the `ape-tokens` plugin which is one of the `recommended-plugins` from Ape.

Resolving this will improve compatibility between the Ape framework and Titanaboa.

### How can it be fixed?

* Upgrade semantic-version
* OR find a way to support broader range (copy in methods or components of the library?)

**Comment by charles-cooper** [comment]
We are probably not too sensitive to the version of semantic-version. Expanding the version range or upgrading the package should be fine. We believe we just use it in one place to validate version pragmas. Would you be able to submit a PR with the proposed change?
