### ISSUE TITLE
Compiler throws for `ERC20Detailed` interface implementation if `public` `constant`/`immutable` variables are used

### ISSUE THREAD

**Issue by pcaversaccio** [vyperlang/vyper#3130]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.7+commit.6020b8b
* OS: win
* Python Version (output of `python --version`): `3.9.2`

### What's your issue about?

Since Vyper version `0.3.7` I can declare `immutable` and `constant` variables as `public`. If I now try to implement the following, the Vyper compiler will throw:

```vy
from vyper.interfaces import ERC20Detailed
implements: ERC20Detailed


decimals: public(constant(uint8)) = 18
name: public(immutable(String[25]))
symbol: public(immutable(String[5]))
```

Error message: `vyper.exceptions.InterfaceViolation: Contract does not implement all interface functions or events: decimals, name, symbol`.

### How can it be fixed?

Allow the usage of `public` `constant` & `immutable` variables for interface `view` functions.

**Comment by pcaversaccio** [comment]
@charles-cooper do you think we can fix this for the Vyper `0.3.8` release?

**Comment by tserg** [comment]
This should have been fixed as of https://github.com/vyperlang/vyper/commit/026f85f36e609a81262b94a9a7f4b74d559d7c6c, so snekmate's ERC20 should compile now!

**Comment by pcaversaccio** [comment]
oh sweet @tserg - will fix the current workaround in snekmate (not using `implements`) using the `0.3.8` release. Closing the issue since the issue is fixed.
