### ISSUE TITLE
calldata variable can shadow a storage variable

### ISSUE THREAD

**Issue by trocher** [vyperlang/vyper#3139]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.7+commit.6020b8bb
* OS: OSX
* Python Version (output of `python --version`): 3.8.0

### What's your issue about?

According to the [documentation](https://vyper.readthedocs.io/en/stable/scoping-and-declarations.html?highlight=shadow#name-shadowing), it is not permitted for a calldata variable to shadow the name of a storage variable.
However this behavior is not enforced as the example provided in the documentation which is not supposed to compile actually compiles:

`vyper -f  abi,bytecode tests/customs/foo.vy` 
```Vyper
a: int128

@external
def foo(a: int128) -> int128:
    # input argument cannot have the same name as a storage variable
    return a
```
```
[{"stateMutability": "nonpayable", "type": "function", "name": "foo", "inputs": [{"name": "a", "type": "int128"}], "outputs": [{"name": "", "type": "int128"}]}]
0x61005a61000f60003961005a6000f36003361161000c57610042565b60003560e01c346100485763d98ffe11811861004057602436106100485760043580600f0b81186100485760405260206040f35b505b60006000fd5b600080fda165767970657283000307000b
```
This issue could maybe be merged with #3132, if it seems relevant I will merge them.

**Comment by charles-cooper** [comment]
i think the docs are wrong here

**Comment by trocher** [comment]
Small addition:  The documentation also seems to be wrong for memory variables as the corresponding example of the documentation supposed not to compile also compiles:
```Vyper
a: int128
@external
def foo() -> int128:
    # memory variable cannot have the same name as a storage variable
    a: int128 = self.a
    return a
```
`calldata` and `memory` variables shadowing a `immutable` or `constant` however seems to be prevented by the compiler.

**Comment by fubuloubu** [comment]
> Small addition: The documentation also seems to be wrong for memory variables as the corresponding example of the documentation supposed not to compile also compiles:
> 
> ```vyper
> a: int128
> @external
> def foo() -> int128:
>     # memory variable cannot have the same name as a storage variable
>     a: int128 = self.a
>     return a
> ```
> 
> `calldata` and `memory` variables shadowing a `immutable` or `constant` however seems to be prevented by the compiler.

Ah yes, we changed this much more recently (I think in 0.3.3)
