### ISSUE TITLE
`asttokens` dependency conflict with Ape framework (0.5.3+)

### ISSUE THREAD

**Issue by ozmium22** [vyperlang/vyper#3148]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.7
* OS: osx
* Python Version (output of `python --version`): 3.9.8

### What's your issue about?

I am getting dependency conflicts with the Ape framework because Vyper requires `asttokens==2.0.5`, but eth-ape 0.5.3+ requires `asttokens>=2.1.0` (via its requirement of `ipython==8.6.0`).

### How can it be fixed?

Loosen the dependency to `asttokens>=2.0.5,<3`

If this is acceptable I'd be happy to submit a PR.

**Comment by charles-cooper** [comment]
the dependency loosening seems fine
