### ISSUE TITLE
Questions about storage layout of old vyper contracts

### ISSUE THREAD

**Issue by jeffchen006** [vyperlang/vyper#3163]
Sorry if it's the wrong place to post this question.

I'm working on a research project which requires me to find storage layout of any contract, given the source code. 

I can handle Vyper contracts compiled with vyper-0.2.16 or after, because I can read outputs from "vyper -f layout". 

However, for contracts compiled with vyper-0.2.15 or before, there is no such an "-f layout" option so I really cannot find storage layout. 

I tried to compile contracts of version 0.2.4 with vyper-0.2.16, it successfully compiles but I realize the storage layout given vy the compiler is wrong. 

I wonder how can we figure out storage layout of these old vyper contracts? 

Also, I notice vyper allows users to provide a storage-layout file to override the compiler's default results, I wonder in this case,  is there still a way to extract the storage layout of a deployed contract?

**Comment by charles-cooper** [comment]
> I wonder how can we figure out storage layout of these old vyper contracts?

you would need to patch the old compiler to give you that information

> Also, I notice vyper allows users to provide a storage-layout file to override the compiler's default results, I wonder in this case, is there still a way to extract the storage layout of a deployed contract?

the layout file should be published as part of the source verification. if the layout does not match the layout file available to the verifier, the contract should not verify

**Comment by fubuloubu** [comment]
@banteg has a project that monkeypatches older versions of the compiler to print storage layouts

**Comment by jeffchen006** [comment]
> > I wonder how can we figure out storage layout of these old vyper contracts?
> 
> you would need to patch the old compiler to give you that information
> 
> > Also, I notice vyper allows users to provide a storage-layout file to override the compiler's default results, I wonder in this case, is there still a way to extract the storage layout of a deployed contract?
> 
> the layout file should be published as part of the source verification. if the layout does not match the layout file available to the verifier, the contract should not verify

Thanks very much for your answer! It all makes sense. I think I will find a workaround to handle it. Patching old compilers seems too much work :)

**Comment by jeffchen006** [comment]
> @banteg has a project that monkeypatches older versions of the compiler to print storage layouts


Thank you very much for your answer! Yes. I also found that repo. It provides a new idea about tracking SHA3 and tracing back. It could be an alternative way if we don't know the source code.
