### ISSUE TITLE
Assigning a value to the `implements` statement is not prevented

### ISSUE THREAD

**Issue by trocher** [vyperlang/vyper#3184]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.8+commit.e60b021b
* OS: OSX
* Python Version (output of `python --version`): 3.8.0

### What's your issue about?

The `implements` directive is currently translated to an `AnnAssign` AST node with the name `"implements"`. Since no check regarding the value of such AST node is done, it is possible to assign any value to it. Note that since the `implements`'s semantics are used, the value seems to be essentially ignored by the compiler.

As an example, the following contract compiles.

```Vyper
interface A:
    def test(): nonpayable

implements: A = 12

@external
def test():
    pass
```

### How can it be fixed?

Checking that the `value` field of the node is `None` should solve the issue.

**Comment by tserg** [comment]
I am keen to tackle this. Would it be a good idea to combine this issue with implementing the `ImplementsDecl` AST node? https://github.com/vyperlang/vyper/blob/df264826b25bf54595da5f5c6d81ca8116e946a9/vyper/semantics/analysis/module.py#L150-L157

**Comment by fubuloubu** [comment]
> I am keen to tackle this. Would it be a good idea to combine this issue with implementing the `ImplementsDecl` AST node? https://github.com/vyperlang/vyper/blob/df264826b25bf54595da5f5c6d81ca8116e946a9/vyper/semantics/analysis/module.py#L150-L157

Yes

**Comment by charles-cooper** [comment]
i actually think it will be more straightforward to add this check separately
