### ISSUE TITLE
docs: add note on return value sizes in interfaces

### ISSUE THREAD

**Issue by pcaversaccio** [vyperlang/vyper#3204]
Add a note in the interface documentation regarding the following fact: 
> If we use interfaces via Vyper syntax, the following holds: For any input parameters, where you have to put a max threshold (eg. dynamic arrays, strings, bytes etc). the values defined in the interface reflect also the _max_ threshold in the implementation. However, for any return values, if you need to define a max threshold in the interface, it reflects the _lower_ bound in the implementation.

**Comment by pcaversaccio** [comment]
I will take care of this issue and will submit a PR.

**Comment by charles-cooper** [comment]
note that we are planning to remove explicit bounds in interfaces in favor of ellipses - see https://github.com/vyperlang/vyper/issues/2814#issue-1207449618

**Comment by pcaversaccio** [comment]
> note that we are planning to remove explicit bounds in interfaces in favor of ellipses quite soon - see https://github.com/vyperlang/vyper/issues/2814#issue-1207449618

That's why I write in the PR 'This behaviour might change in the future.' You want me to add something else?

**Comment by charles-cooper** [comment]
> That's why I write in the PR 'This behaviour might change in the future.' You want me to add something else?

no! just wanted to give a heads up to anybody following this issue.
