### ISSUE TITLE
Vague exception message when accessing a storage variable before declaration in a subscript

### ISSUE THREAD

**Issue by benber86** [vyperlang/vyper#3214]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.7
* OS: linux
* Python Version (output of `python --version`): 3.10

### What's your issue about?

Referencing a constant variable in a subscript in a type annotation before it is declared when declaring another state variable gives the following unclear error message:
`vyper.exceptions.UndeclaredDefinition: 'self' has not been declared. `

Can be reproduced with the following example:

```
PRECISIONS: constant(uint256[N_COINS]) = [
    1000000000000,
    10000000000,
    1,
]

N_COINS: constant(int128) = 3
```

**Comment by charles-cooper** [comment]
fixed in #3215
