### ISSUE TITLE
DynArray setter in constructor causes unhandled error on 0.3.4

### ISSUE THREAD

**Issue by antazoey** [vyperlang/vyper#3260]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.4
* OS: macOS
* Python Version (output of `python --version`): 3.9

### What's your issue about?

Whe attempting to compile this contract (extremely simplified version):

```vyper
# @version 0.3.4

dynArray: public(DynArray[uint256, 1024][3])

@external
def __init__():
    self.dynArray[0] = [0]
```

, it fails with:

```
INFO: Compiling 'TestContractVy.vy'.
ERROR: Unable to load project. Reason: vyper.exceptions.CompilerPanic: Mismatch between node and input type while building getter

This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
https://github.com/vyperlang/vyper/issues/new?template=bug.md
[74488] Failed to execute script 'vyper_compile' due to unhandled exception!
```

I am pretty sure this worked before!

### How can it be fixed?

Upgrading to 0.3.6 does fix it, but I am opening the issue because the output told me to do so.

**Comment by charles-cooper** [comment]
closing because this is fixed as of v0.3.6
