### ISSUE TITLE
`if else` with exit statements in both branch with succeeding code not prevented

### ISSUE THREAD

**Issue by trocher** [vyperlang/vyper#3265]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.8+commit.f3c8cb99
* OS: OSX
* Python Version (output of `python --version`): 3.8.0

### What's your issue about?

The compiler checks that there is no exit statements (`Return`, `Selfdestruct`, `Raise`) with succeeding code (that would not execute) including other exit statements.
It is however not checked that there is no statements after an `if else` where both branches contains an exit statement. This would probably be a good check to have.

For example, the following code compiles although the last statement is not reachable.

```Vyper
@external
def foo(a:bool) -> uint256:
    if a:
        return 1
    else:
        return 2
    b:uint256 = 1
```

Note that is issue is quite similar to #3223

**Comment by fubuloubu** [comment]
Definitely low severity, basically just produces dead code and should probably raise
