### ISSUE TITLE
__init__ re-initializes DynArray after being populated by subroutine call.

### ISSUE THREAD

**Issue by scherrey** [vyperlang/vyper#3270]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.7
* OS: `linux (5.14.0-4mx-amd64 #1 SMP Debian 5.14.16-1~mx21+1 (2021-11-05) x86_64 GNU/Linux)`
* Python Version (output of `python --version`): 3.9.2

Not sure if this is intentional or a bug but it sure seems counter intuitive and problematic to debug. My contract has a DynArray member which will get populated by iterating over an array passed into `__init__` by calling an internal method. However, if I don't explicitly initialize the DynArray *before* calling this internal method, the` __init__` seems to perform its own initialization of the DynArray after the internal method is called and empty the DynArray that was previously populated.

See the VYPER NOTE in the `__init__` function below. Comment out the initialization line under that note and the efforts performed by the add_pool() calls get erased and  self.dlending_pools is empty even though the add_pool() calls succeeded.

Here's my ctor:

```
@external
def __init__(_name: String[64], _symbol: String[32], _decimals: uint8, _erc20asset : address, _pools: DynArray[address, MAX_POOLS]):

    assert MAX_BALTX_DEPOSIT <= MAX_POOLS, "Invalid contract pre-conditions."

    dname = _name
    dsymbol = _symbol
    ddecimals = _decimals
    derc20asset = _erc20asset

    # VYPER NOTE - if we don't explicitly initialize dlending_pools here
    #              the ctor will initialize it to empty AFTER the
    #              _add_pool() loop completes and erase the passed in pools!
    self.dlending_pools = empty(DynArray[address, MAX_POOLS])

    self.owner = msg.sender
    self.totalSupply = 0

    for pool in _pools:
        self._add_pool(pool)


# Can't simply have a public lending_pools variable due to this Vyper issue:
# https://github.com/vyperlang/vyper/issues/2897
@view
@external
def lending_pools() -> DynArray[address, MAX_POOLS]: return self.dlending_pools


@internal 
def _add_pool(_pool: address) -> bool:    
    # Do we already support this pool?
    assert (_pool in self.dlending_pools) == False, "pool already supported."

    # Is this likely to be an actual LPAdapter contract?
    response: Bytes[32] = empty(Bytes[32])
    result_ok: bool = empty(bool)

    result_ok, response = raw_call(_pool, method_id("maxDepositable()"), max_outsize=32, is_static_call=True, revert_on_failure=False)
    assert (response != empty(Bytes[32])), "Doesn't appear to be an LPAdapter."

    self.dlending_pools.append(_pool)

    log PoolAdded(msg.sender, _pool)

    return True
```

### How can it be fixed?

WORKAROUND: Explicit initialization of the DynArray before the subroutine call prevents this problem from manifesting itself.

**Comment by fubuloubu** [comment]
Hmm, yeah why is it initializing the array at all in the constructor?

**Comment by tserg** [comment]
Hi @scherrey, can you share the full code (if possible) as well as the framework that you are using?

**Comment by scherrey** [comment]
> 

I sent you an invite to our repo. You can repro the defect at commit 87111fae2b077cd1005bdf1ff47a5828f5b234d0 .

**Comment by scherrey** [comment]
Hrm... now I can't recreate the defect with a fresh checkout. What's crazy is I repo'd it on two different computers before I reported it as a defect. :-( I think this one is not legit. Apologies for the wild good chase.
