### ISSUE TITLE
`convert` from `String` to `bool` convert the `String`'s address instead of the `String` itself

### ISSUE THREAD

**Issue by trocher** [vyperlang/vyper#3299]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.8+commit.7ff8f307
* OS: OSX
* Python Version (output of `python --version`): 3.8.0

### What's your issue about?

Converting a `String` `a`  into a `bool` is allowed but it performs the following `slot_number(a) != 0`
 
For example, a call to `foo` will return `True` here, but if we were to comment the first line, it would return `False` as `a` is now at slot 0 of the storage:

```Vyper
b:uint256
a: String[1]
@external
@payable
def foo() -> bool:
    g:bool = convert(self.a, bool)
    return g
```
### How can it be fixed?

Conversion from `String` to `bool` should maybe be blocked as it doesn't really make sense anyway.

**Comment by charles-cooper** [comment]
Conversion from string to bool should indeed be blocked.

**Comment by charles-cooper** [comment]
this was fixed in https://github.com/vyperlang/vyper/pull/3391
