### ISSUE TITLE
shift argument type inconsistencies

### ISSUE THREAD

**Issue by xrchz** [vyperlang/vyper#3309]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.8+commit.8ebabc5c
* OS: GNU
* Python Version (output of `python --version`): Python 3.10.9

### What's your issue about?

This file compiles fine with `vyper`, but fails if you try to load it with `boa`.
```
@external
def bug() -> uint256:
  x: uint256 = 392
  y: uint256 = 19
  return shift(x, y)
```

The [docs](https://docs.vyperlang.org/en/stable/built-in-functions.html#shift) for `shift` list the following type:
`shift(x: uint256, _shift: int128) → uint256`

The [implementation](https://github.com/vyperlang/vyper/blob/8ebabc5ce277942ee470845e2d04df5f8a2e6ad6/vyper/builtins/functions.py#L1459) is different again, allowing any integer type (whereas boa complains for non-int128).

### How can it be fixed?

Decide on the semantics and make vyper, boa, and the docs consistent.

**Comment by charles-cooper** [comment]
closing as this was an issue with boa's vyper pin being out of date. also, `shift()` is deprecated as of https://github.com/vyperlang/vyper/pull/3019
