### ISSUE TITLE
Bug: compiler dislikes `x not in [a, b]` in 0.3.8, whereas it was fine in 0.3.7

### ISSUE THREAD

**Issue by bout3fiddy** [vyperlang/vyper#3339]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.8
* OS: osx
* Python Version (output of `python --version`): 3.10.4

### What's your issue about?

<img width="705" alt="image" src="https://user-images.githubusercontent.com/11488427/230437774-c3b68030-9319-4169-b344-dbb470002102.png">

**Comment by charles-cooper** [comment]
got it. in the future, it will be very helpful to please include a repro (text, that can be copy-pasted)
