### ISSUE TITLE
`PUSH0` Support

### ISSUE THREAD

**Issue by pcaversaccio** [vyperlang/vyper#3360]
The original motivation behind this issue is a quick convo with @bout3fiddy about the latest added opcode [`PUSH0`](https://eips.ethereum.org/EIPS/eip-3855). Since we can't use inline assembly (yet 😉), the only way I currently see how Vyper can benefit is by improving the optimiser to make use of `PUSH0`. My questions are:
- Has there already been a discussion about how to support it best?
- Does anyone see further dimensions where Vyper could support from `PUSH0` beside the optimiser?

**Comment by charles-cooper** [comment]
i think we could just replace `push1 0` with `push0`

**Comment by pcaversaccio** [comment]
Completed via https://github.com/vyperlang/vyper/pull/3361.
