### ISSUE TITLE
VIP: `CODECOPY` support (`self.code`)

### ISSUE THREAD

**Issue by JorgeAtPaladin** [vyperlang/vyper#3362]
## Simple Summary
Support the low level `CODECOPY` opcode to copy contract code into a memory array.

## Motivation
`CODECOPY` is a low level opcode which allows for copying a contracts own bytecode into a slice. This can be very powerful for more unique contracts. Eg. a famous practical example is a minimal proxy contract which encodes immutable variables at the end of the proxy code. Our own use case is to use HyVM to encode calldata (parameters) at the end of the contract code.

Regardless of use case, we strongly believe it makes sense to support simple features like this, which don't have any downside to support, as it makes the language more mature and complete.

## Specification
We recommend a feature similar to `msg.data` which returns the Bytes type. The most obvious syntax for this feature would be `self.code`, returning sliceable bytes as well. Of course, the Bytes should only lazy load the data which is actually used, as is how the Bytes is designed to be used.

## Backwards Compatibility
No incompatibilities.

## Dependencies
No dependencies

## References
[Solidity docs](https://docs.soliditylang.org/en/v0.8.19/cheatsheet.html): `<address>.code` (bytes memory): code at the [Address](https://docs.soliditylang.org/en/v0.8.19/types.html#address) (can be empty). Also present within solidity (though solidity also supports EXTCODECOPY).

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by JorgeAtPaladin** [comment]
It may make sense to immediately also support EXTCODECOPY, similar to solidity. This is outside of our own use-case hence it wasn't raised in the VIP, but arguably the implementation can support both opcodes using `<address>.code`, just like solidity does.

**Comment by JorgeAtPaladin** [comment]
Looks like we are noobs that only look at the docs and didn't realize this was already done in #2583.

If confirmed that this already works, we'll be doing our OS duty and providing a PR to document this behavior 👍 

Very nice if this is already implemented!

**Comment by charles-cooper** [comment]
@JorgeAtPaladin yep, done in #2583, apparently just undocumented that it dispatches into CODECOPY. Here's an example you can use to verify the behavior:
```vyper
@external
def foo() -> Bytes[32]:
    return slice(self.code, 0, 32)
```
and the resultant assembly:
```
(vyper) ~/vyper $ vyc -f opcodes_runtime tmp/codecopy.vy  | grep CODECOPY
PUSH1 0x0 CALLDATALOAD PUSH1 0xE0 SHR CALLVALUE PUSH2 0x084 JUMPI PUSH4 0xC2985578 DUP2 XOR PUSH2 0x07D JUMPI PUSH1 0x4 CALLDATASIZE LT PUSH2 0x084 JUMPI PUSH1 0x20 DUP1 PUSH1 0x80 MSTORE CODESIZE PUSH1 0x20 GT PUSH2 0x084 JUMPI PUSH1 0x20 PUSH1 0x40 MSTORE PUSH1 0x20 PUSH1 0x0 PUSH1 0x60 CODECOPY PUSH1 0x40 DUP2 PUSH1 0x80 ADD DUP2 MLOAD DUP1 DUP3 MSTORE PUSH1 0x20 DUP4 ADD PUSH1 0x20 DUP4 ADD DUP2 MLOAD DUP2 MSTORE POP POP POP DUP1 MLOAD DUP1 PUSH1 0x20 DUP4 ADD ADD PUSH1 0x1F DUP3 PUSH1 0x0 SUB AND CALLDATASIZE DUP3 CALLDATACOPY POP POP PUSH1 0x1F NOT PUSH1 0x1F DUP3 MLOAD PUSH1 0x20 ADD ADD AND SWAP1 POP SWAP1 POP DUP2 ADD SWAP1 POP PUSH1 0x80 RETURN JUMPDEST POP PUSH1 0x0 PUSH1 0x0 REVERT JUMPDEST PUSH1 0x0 DUP1 REVERT LOG1 PUSH6 0x767970657283 STOP SUB ADDMOD STOP SIGNEXTEND
```

**Comment by JorgeAtPaladin** [comment]
@charles-cooper thanks, closing this and adding a todo for me to PR some doc updates for your team.

cheers, Marco from Paladin.
