### ISSUE TITLE
constant folding of some builtins results in compiler panic

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3363]
### Version Information

* vyper Version (output of `vyper --version`): c93bc06354d620608f4da823d5bd7444d293270f

### What's your issue about?
repro:
```vyper
BIT_MASK: constant(uint256) = shift(2**32 - 1, 224)

@external
def foo() -> uint256:
  return BIT_MASK
```
results in
```
vyper.exceptions.CompilerPanic: Node to be replaced does not exist within parent children

This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
```

**Comment by charles-cooper** [comment]
closing since `shift()` is deprecated as of #3019

**Comment by charles-cooper** [comment]
note: this regression seems to have been introduced in be2c59a604070c75212dca90beb4c33fed908c8b

**Comment by charles-cooper** [comment]
convert is also having issues:
```vyper
_BATCH_SIZE: constant(uint16) = convert(max_value(uint8), uint16))
```

**Comment by pcaversaccio** [comment]
> convert is also having issues:
> 
> ```vyper
> _BATCH_SIZE: constant(uint16) = convert(max_value(uint8), uint16))
> ```

the source code if needed: https://github.com/pcaversaccio/snekmate/blob/main/src/tokens/ERC1155.vy#L70

**Comment by tserg** [comment]
I think `convert` is a separate issue because it does not have an `evaluate()` function for folding.
