### ISSUE TITLE
Document/define storage slots for reentrancy locks

### ISSUE THREAD

**Issue by pcaversaccio** [vyperlang/vyper#3382]
We should define somewhere properly how the storage slots for reentrancy locks are chosen. In the compiler code, we can see this [here](https://github.com/vyperlang/vyper/blob/master/vyper/semantics/analysis/data_positions.py#L98). Also, I feel we should disallow empty reentrancy locks like `@nonreentrant("")` or `@nonreentrant(" ")` for safety reasons.

**Comment by fubuloubu** [comment]
It would be amazing to create an output storage slot table for viewing purposes, like in https://github.com/vyperlang/vyper/issues/1950

**Comment by charles-cooper** [comment]
nonreentrant keys are in `-f layout` output format.
```
$ vyper -f layout /dev/stdin <<EOF
@external
@nonreentrant("x")
def foo():
  pass
EOF
{"storage_layout": {"nonreentrant.x": {"type": "nonreentrant lock", "slot": 0}}, "code_layout": {}}
```

**Comment by charles-cooper** [comment]
invalid identifiers are prevented from being non-reentrancy keys in https://github.com/vyperlang/vyper/pull/3605
