### ISSUE TITLE
SyntaxException about Event datafield name

### ISSUE THREAD

**Issue by andriytyurnikov** [vyperlang/vyper#3426]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.7+commit.6020b8b
* OS: osx
* Python Version (output of `Python 3.9.6`):

### What's your issue about?
Word `from` can not be used as a name of event data field, as I suspect other keywords
```
event Transfer:
    from: indexed(address)
    to: indexed(address)
    value: uint256
```

```
SyntaxException: invalid syntax (<unknown>, line 18)
  line 18:9 
       17 event Transfer:
  ---> 18     from: indexed(address)
```

**Comment by charles-cooper** [comment]
this is a dup of https://github.com/vyperlang/vyper/issues/2339
