### ISSUE TITLE
bug: view and pure functions can be called without assignment

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3434]
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/ed0a654aa2f1069874c2c6d21b8932737aee3f6f
* OS: linux
* Python Version (output of `python --version`): 3.10.8

### What's your issue about?

View and pure functions can be called without assignment of their result. This serves no purpose since they cannot have side effects. This could be disallowed like builtin functions that are not assigned.

```
@internal
@pure
def foo(x: uint256) -> uint256:
    return x

@external
def bar(x: uint256):
    self.foo(x)
```

h/t @trocher @ptrcarta

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by trocher** [comment]
After reviewing this, I don't think such a restriction should be implemented as someone might consider reverting as some side effect:

```Vyper
ADMIN: constant(address) = empty(address)

@internal
@view
def check_msg_sender():
    assert(msg.sender) == ADMIN

@external
def foo():
    self.check_msg_sender()
```
