### ISSUE TITLE
bug: fallback function without `@payable` decorator can be payable

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3440]
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/95bf73f493dc8458a1d6981493275379197a4bdf
* OS: linux
* Python Version (output of `python --version`): 3.10.8

### What's your issue about?

A fallback function without the `@payable` decorator can be payable since there is no check on call value.

See the IR generated by this contract:
```
@external
def foo() -> uint256:
    send(self,12)
    return 1

@external
def __default__():
    pass
```

h/t @trocher @ptrcarta

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by charles-cooper** [comment]
this was fixed as of https://github.com/vyperlang/vyper/commit/02339dfda0f3caabad142060d511d10bfe93c520, please see https://github.com/vyperlang/vyper/security/advisories/GHSA-vxmm-cwh2-q762
