### ISSUE TITLE
bug: array of different types can be folded

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3442]
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/95bf73f493dc8458a1d6981493275379197a4bdf
* OS: linux
* Python Version (output of `python --version`): 3.10.8

### What's your issue about?

The first statement compiles even though there is a type mismatch in the literal array. It should fail compilation like the second statement.

```
@external
def foo():
    a: uint256 = [max_value(decimal), max_value(uint256)][1] # compiles  
    b: uint256 = [1.0, max_value(uint256)][1]
```

h/t @trocher @ptrcarta

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by trocher** [comment]
The issue is no longer there in 4b4e188ba83d28b5dd6ff66479e7448e5b925030, was removed by the refactoring of folding
