### ISSUE TITLE
[chore] improve typechecking of literal arrays as iterator in a `for` loop

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3443]
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/95bf73f493dc8458a1d6981493275379197a4bdf
* OS: linux
* Python Version (output of `python --version`): 3.10.8

### What's your issue about?

In `vyper/semantics/analysis/local.py`, the `visit_For` function can be improved by converting to a `set()` for literal arrays to prevent duplicates due to both `SArrayT` and `DArrayT` being present for the same base types.

h/t @trocher @ptrcarta

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by charles-cooper** [comment]
@trocher is this still an issue? as of https://github.com/vyperlang/vyper/commit/c6b29c7f06a493bbeb62e85baa2592a994b15a5d

**Comment by trocher** [comment]
No, this is fixed as of #3596
