### ISSUE TITLE
contract with only internal functions is executable

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3446]
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/95bf73f493dc8458a1d6981493275379197a4bdf
* OS: linux
* Python Version (output of `python --version`): 3.10.8

### What's your issue about?

A contract that only has internal functions besides the constructor may still compile to executable code. Internals are not pruned, and execution of the internal functions section is not guarded. Upon calling the contract, execution will start at the first internal function. However, execution will generally fail when `POP`ping the `RETURN_PC` from the stack, which should be empty upon function exit.

h/t @trocher @ptrcarta

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by charles-cooper** [comment]
this was resolved in #3496
