### ISSUE TITLE
location of an internal function's argument should be memory

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3449]
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/95bf73f493dc8458a1d6981493275379197a4bdf
* OS: linux
* Python Version (output of `python --version`): 3.10.8

### What's your issue about?

The data location of a function's arguments is set to `CALLDATA` for external and internal functions, when it should be `MEMORY` for internal functions. This causes the error message to be misleading.

```
@internal
def foo(a: uint256):
    a = 1
```
```
vyper.exceptions.ImmutableViolation: Cannot write to calldata
  contract "tmp/internal_arg.vy:3", function "foo", line 3:4 
       2 def foo(a: uint256):
  ---> 3     a = 1
  -----------^
       4
```

h/t @trocher @ptrcarta

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by charles-cooper** [comment]
this is a UX issue, as calldata protects against writing to function arguments (which is currently expected behavior, although there are other proposals to change that).

**Comment by charles-cooper** [comment]
We should allow writing to internal function arguments.
