### ISSUE TITLE
VIP: require loop variable annotation

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3475]
## Simple Summary
as title. require for statements like `for i: uint256 in [1, 2, 3]:` instead of `for i in [1, 2, 3]`

(h/t to @trocher for suggesting this change to the language!)

## Motivation
loop variable type inference is one of the most complicated areas of the vyper type checker, taking up 150 loc (that is, 30%) of vyper/semantics/analysis/local.py: https://github.com/vyperlang/vyper/blob/7f18aeee59abbf3f4657edc94a8b354731cce19b/vyper/semantics/analysis/local.py#L336-L493

because the compiler currently has to loop over all possible types for the loop variable, it

- creates a performance issue for nested loops since we get a nested loop in the typechecker
- many fixed and outstanding bugs in the typechecker have to do with loops, for instance just cherry-picking some recent issues, cf. #2772, #3212, #3443, #3441, #3429, #3374
- a state journal had to be implemented in the typechecker because the loop variable inference routine depends on raising exceptions, which can result in invalid state inside the typechecker(!) (see #3318, #3375)
- iterator type inference is still not intuitive, for instance both of the following functions actually revert at runtime due to the loop variable being inferred as `uint256` (thanks to @trocher for these examples):
```vyper
@external
def loo():
    for x in [1, 2, 3]:
        v: bool = x - 10 == 1  # x is uint256, safesub reverts

@external
def foo():
    for x in [1, 2, 3]:
        a: int256 = convert(x - 100,int256)  # x is uint256, checked conversion reverts
```
these above two examples could be fixed by attempting to (at compile-time) unroll the loop and fold in the loop variable, and reject types which result in folding failures. this would "correctly" (i.e., match the user's intuition) infer the type of `x` as `int256` in both of the above two cases. however, this would result in more complexity in the loop variable type inference routine, and would result in more runtime complexity as well.

lastly, the fact that loop variables are currently not annotated is actually a peculiar outcome of [PEP526 - "In addition, one cannot annotate variables used in a for or with statement"](https://peps.python.org/pep-0526/#where-annotations-aren-t-allowed). i consider this to be a flaw in PEP484+PEP526 itself, as loop variables cannot be annotated in python without commented type hints.

also, while it might seem unfamiliar to users at first, from the point of view of vyper, the fact that loop variables are not annotated is inconsistent with all other vyper variables, which do not run into the same type inference issues (because they are all required to be annotated in the first place).

## Specification
require loop variables to be annotated.

an implementation note: the fact that type annotations are not allowed for loop variables causes some issues for us at the syntactic level, but they can be worked around (e.g. by adding a preprocessing rule which converts `for i: uint256 in ..:` to some currently unused syntactic expression, ex. `for *(i, uint256) in ..:`, which can then be converted into a type annotation during conversion from python to vyper ast.

## Backwards Compatibility
this is a breaking change.

## Dependencies
If this VIP depends on any other VIPs being implemented, please mention them.

## References
Add any references that this VIP might reference (other VIPs/issues, links to blog posts, etc.)

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by tserg** [comment]
Do we want to consider disallowing literal lists if they can be of more than one possible types? This seems like a reasonable restriction given that one of vyper's goals is strong typing.

Instead of the first snippet, we require users to do the latter:
```
for i in [1, 2, 3]:
    ...
```
```
x: uint256[3] = [1, 2, 3]
for i in x:
    ...
```

**Comment by fubuloubu** [comment]
> Do we want to consider disallowing literal lists if there is more than one possible type? This seems like a reasonable restriction given that one of vyper's goals is strong typing.
> 
> Instead of the first snippet, we require users to do the latter:
> 
> ```
> for i in [1, 2, 3]:
>     ...
> ```
> 
> ```
> x: uint256[3] = [1, 2, 3]
> for i in x:
>     ...
> ```

I think with the iterator variable finally having typing, we can forward propagate the type to the list literal

**Comment by tserg** [comment]
> > Do we want to consider disallowing literal lists if there is more than one possible type? This seems like a reasonable restriction given that one of vyper's goals is strong typing.
> > Instead of the first snippet, we require users to do the latter:
> > ```
> > for i in [1, 2, 3]:
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > x: uint256[3] = [1, 2, 3]
> > for i in x:
> >     ...
> > ```
> 
> I think with the iterator variable finally having typing, we can forward propagate the type to the list literal

I was thinking that between the two un-pythonic choices of (1) type annotation for the iterator variable in `for` statements; or (2) disallowing literal lists with more than one possible type in `for` statements, option (2) would be the lesser of the two evils.

**Comment by tserg** [comment]
I have a sketch at this [PR](https://github.com/vyperlang/vyper/pull/3544) - during pre-parsing, we transform `for i: uint256 in ...` to a tuple in `for i, uint256 in ...`.
