### ISSUE TITLE
`tests` module is importable outside of Vyper package

### ISSUE THREAD

**Issue by antazoey** [vyperlang/vyper#3509]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.9
* OS: macos
* Python Version (output of `python --version`): 3.10.11

### What's your issue about?

Please include information like:

* Install Vyper
* Go outside of vyper folder (make sure can't do any local importing)
* Run `python -c "import tests; print(tests.__path__)"`
* Notice it prints the path to Vyper's tests for some reason

I actually had this issue with some of our repos, but once I fixed those I noticed it was still happening with Vyper.

### How can it be fixed?

I tried so many things; the only way I have gotten it to work is by putting the source files in `src` first so like `src/vyper` and then changing the packages key in pyproject.toml to:

```toml
packages = [
    { include = "vyper", from = "src" }
]

```

**Comment by antazoey** [comment]
realizing this only happened when having vyper installed in editable mode.

**Comment by charles-cooper** [comment]
yea i was going to say that's kind of odd, this line in setup.py should prevent `tests` from being exported: https://github.com/vyperlang/vyper/blob/9e3b9a2b8ae55aa83b5450080f750be15f819de7/setup.py#L91

**Comment by antazoey** [comment]
> yea i was going to say that's kind of odd, this line in setup.py should prevent `tests` from being exported:
> 
> https://github.com/vyperlang/vyper/blob/9e3b9a2b8ae55aa83b5450080f750be15f819de7/setup.py#L91

Yes I saw that but have had issues with setting.
It's doc is a little confusing too:

```
    'exclude' is a sequence of names to exclude; '*' can be used
        as a wildcard in the names.
        When finding packages, 'foo.*' will exclude all subpackages of 'foo'
        (but not 'foo' itself).
```

it sounds like you can use to exclude file patterns that within your package folder, like if you were putting tests in there or something. However, it is not clear to me that you can exclude whole directories this way, from reading the doc, maybe I am just being dumb tho.
