### ISSUE TITLE
bug: imported contracts are not fully semantically validated

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3512]
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/9e3b9a2b8ae55aa83b5450080f750be15f819de7
* OS: linux
* Python Version (output of `python --version`): 3.10.4

### What's your issue about?

When a contract is imported, only the function signatures are semantically checked to produce the `InterfaceT`. Contract A can therefore import another contract B that does not compile, but Contract A would compile as long as the signatures of the imported functions of Contract B are semantically correct.

```
# Contract A
# a.vy
import b as B

@external
def foo(addr: address):
    x: B = B(addr)
    x.foo() 
```
```
# Contract B
# b.vy
@external
def foo():
    x: uint256 = "foo"
```

h/t @trocher 

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by charles-cooper** [comment]
this was fixed in #3663
