### ISSUE TITLE
bug: overriding storage layout fails with immutables

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3517]
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/9e3b9a2b8ae55aa83b5450080f750be15f819de7
* OS: linux
* Python Version (output of `python --version`): 3.10.4

### What's your issue about?

Please include information like:

The check used for ignoring immutable in `set_storage_slots_with_overrides` is ill-defined. When compiling a contract with a custom storage layout file, if an immutable is defined in the contract (and is not present in the json), the compilation will fail with a `StorageLayoutException`.

This contract fails to compile if given an empty storage layout:
```
a: immutable(uint256)

@external
def __init__():
    a = 1
```

h/t @trocher 

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by charles-cooper** [comment]
should be fixed in #3789
