### ISSUE TITLE
bug: `TypeCheckFailure` when using address and `self` members as struct field name

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3521]
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/9e3b9a2b8ae55aa83b5450080f750be15f819de7
* OS: linux
* Python Version (output of `python --version`): 3.10.4

### What's your issue about?

Accessing the field of an enum named after an address or `self` member (`balance`, `codesize`, `is_contract`, `codehash` or `code`) results in a `TypeCheckFailure`.

This contract fails to compile: `TypeCheckFailure: Attribute node did not produce IR`
```
struct User:
    balance: uint256

@external
def foo():
    a: User = User({balance: 12})
    b: uint256 = a.balance
```

h/t @trocher 

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by trocher** [comment]
might be fixed in `0.4.0` given that #3939 is @charles-cooper

**Comment by charles-cooper** [comment]
todo: bisect to find the fixing commit

**Comment by charles-cooper** [comment]
bisect showed 7bdebbf12798ccda4285653f630c1a6b1d4af5b8 as the fixing commit
