### ISSUE TITLE
VIP: rename `enum` to `flags`

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3642]
## Simple Summary
per title

## Motivation
`enum` has been a bit confusing, since vyper's `enum` really follows https://docs.python.org/3/library/enum.html#enum.IntFlag semantics. rename to `flags`.

## Specification
deprecate the `enum` keyword in 0.4.0, and support it as `flags`

optionally, introduce a non-flags `enum` type in 0.5.x series

## Backwards Compatibility
All VIPs that introduce backwards incompatibilities must include a section describing these incompatibilities and their severity. The VIP must explain how the author proposes to deal with these incompatibilities.

## Dependencies
If this VIP depends on any other VIPs being implemented, please mention them.

## References
Add any references that this VIP might reference (other VIPs/issues, links to blog posts, etc.)

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by ControlCplusControlV** [comment]
Will attempt to impl this and make a draft PR

**Comment by AlbertoCentonze** [comment]
Hey @ControlCplusControlV do you mind if I take over this?

**Comment by ControlCplusControlV** [comment]
Sure, go ahead!

**Comment by charles-cooper** [comment]
implemented in #3697
