### ISSUE TITLE
Two keccak256 implementations

### ISSUE THREAD

**Issue by exp7l** [vyperlang/vyper#3649]
* Is it actually safe and/or necessary to choose from 2 hash implementations, given they return different outputs for the same input?  [ref](https://github.com/vyperlang/vyper/blob/68da04b2e9e010c2e4da288a80eeeb9c8e076025/vyper/utils.py#L49)

**Comment by charles-cooper** [comment]
nice find.

that `ImportError` branch looks like dead code -- it should not be reachable since pycryptodome should always be installed. https://github.com/vyperlang/vyper/blob/68da04b2e9e010c2e4da288a80eeeb9c8e076025/setup.py#L97

we should remove it for hygiene.
