### ISSUE TITLE
Integer Range Compiler Check

### ISSUE THREAD

**Issue by chen-robert** [vyperlang/vyper#3652]
**Description**
For the maximum bound in a range, in situations where both the range and the bound are numerical integers, and the range surpasses the bound, it would be advisable to incorporate a compiler check. When both values are numerical integers, and the range exceeds the bound, this check will trigger an exception in the compiler. This exception serves to indicate that the range exceeds the specified bound.

```python
 def visit_For(self, node):
        if isinstance(node.iter, vy_ast.Subscript):
            raise StructureException("Cannot iterate over a nested list", node.iter)

        if isinstance(node.iter, vy_ast.Call):
            [...]
            if len(args) == 1:
                # range(CONSTANT)
                n = args[0]
                bound = kwargs.pop("bound", None)
                validate_expected_type(n, IntegerT.any())
        [...]
```

**Solution**
Add a compiler check to handle the above scenario.

**Comment by charles-cooper** [comment]
#3679 bans the behavior (numerical range constants + constant bound) entirely, ex. `range(1, bound=2)` or `range(1,2, bound=3)` are not longer allowed.
