### ISSUE TITLE
Label Name Collision

### ISSUE THREAD

**Issue by chen-robert** [vyperlang/vyper#3653]
**Description**

In `common`, `ir_identifier` generates a unique and human-readable identifier for a contract function based on its visibility, name, and argument types. However, there is a possibility of a label collision in the logic for generating the label name in the current code. An example of such a collision would be as follows: `def zzz(x: uint8[3], y: uint8)`  and `def zzz__uint8_3(y:uin8)`.

```python
@cached_property
   def ir_identifier(self) -> str:
       argz = ",".join([str(argtyp) for argtyp in self.func_t.argument_types])
       return mkalphanum(f"{self.visibility} {self.func_t.name} ({argz})")
```

**Solution**
Ensure unique label names are given for each function.

**Comment by trocher** [comment]
Might be dup of #3226
