### ISSUE TITLE
Kessak algorithm implementation may be vulnerable

### ISSUE THREAD

**Issue by Kirikus** [vyperlang/vyper#3668]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.10
* OS: osx/linux/win
* Python Version (output of `python --version`): 3.9.16

### What's your issue about?

This error, produced by code analysis tools:

> Issue: [B413:blacklist] The pyCrypto library and its module keccak are no longer actively maintained and have been deprecated. Consider using pyca/cryptography library.
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.7.5/blacklists/blacklist_imports.html#b413-import-pycrypto
   Location: [vyper\vyper\utils.py:45](https://github.com/vyperlang/vyper/blame/master/vyper/utils.py#L45):4
44      try:
45          from Crypto.Hash import keccak  # type: ignore
46

### How can it be fixed?

There is an [eth-hash](https://pypi.org/project/eth-hash/), but that seems like sweeping problem under the rug, since that library does similar includes. This may also be a non-existing issue if vulnerability can not be triggered.
Maybe it is possible to switch algorithm to a random sha3, not just that particular kessak version?
Anyway, someone understanding more about the reason to include that particular algorithm should glance at this.

**Comment by charles-cooper** [comment]
we use pycryptodome though. https://github.com/vyperlang/vyper/blob/4dd47e302fc538ca4fc6fe29d992f0b59456f8e2/setup.py#L97

**Comment by fubuloubu** [comment]
Arguably, the vulnerability is not a risk to this project since it is only used to produce accurate keccak hash literals. Timing analysis bugs are not an issue for this project
