### ISSUE TITLE
VIP: move builtin interfaces to `ethereum.ercs`

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3675]
## Simple Summary
move builtin interfaces like ERC20 to `ethereum.ercs` instead of `vyper.interfaces`

## Motivation
ERC20 et al are clearly ethereum-specific (ERC in fact standing for "Ethereum Request for Comment"), not something related to vyper- the language.

## Specification
per title

## Backwards Compatibility
breaks backwards compatibility. we could have a deprecation period for the 0.4.x series where `import ERC20 from vyper.interfaces` is deprecated but still works; meanwhile the new and recommended way is `import ERC20 from ethereum.ercs`.

## References
loosely related to #2431 and #2814 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by anewt95** [comment]
> ## Simple Summary
> move builtin interfaces like ERC20 to `ethereum.ercs` instead of `vyper.interfaces`
> 
> ## Motivation
> ERC20 et al are clearly ethereum-specific (ERC in fact standing for "Ethereum Request for Comment"), not something related to vyper- the language.
> 
> ## Specification
> per title
> 
> ## Backwards Compatibility
> breaks backwards compatibility. we could have a deprecation period for the 0.4.x series where `import ERC20 from vyper.interfaces` is deprecated but still works; meanwhile the new and recommended way is `import ERC20 from ethereum.ercs`.
> 
> ## References
> loosely related to #2431 and #2814
> 
> ## Copyright
> Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by ControlCplusControlV** [comment]
Wait, should `builtins/interfaces/` be made to `/builtins/ercs/` or `/builtins/ethereum/ercs/`?

**Comment by charles-cooper** [comment]
done in #3741
