### ISSUE TITLE
Is the `unsafe_div` divide by zero result correct?

### ISSUE THREAD

**Issue by engn33r** [vyperlang/vyper#3690]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.10
* OS: linux
* Python Version (output of `python --version`): 3.11.6

### What's your issue about?

The docs for `unsafe_div` indicate it [returns zero](https://docs.vyperlang.org/en/stable/built-in-functions.html?highlight=unsafe_div#unsafe_div) on division by zero. My testing shows this documentation is matches the current implementation, but is the decision to return zero on division by zero correct? I ask only after noticing that the solidity equivalent of unchecked math division by zero has a note in the [solidity 0.8.0 change log](https://docs.soliditylang.org/en/v0.8.20/080-breaking-changes.html#silent-changes-of-the-semantics) that it causes a [panic error](https://docs.soliditylang.org/en/v0.8.23/types.html#division) and reverts. I saw some old blog post suggesting division by zero used to return zero in solidity but no longer does. Which source is used as a reference to indicate what proper EVM semantics are for this case?

### How can it be fixed?

Link to the EVM semantics source in the docs to give more context on what the proper behavior should be.

**Comment by charles-cooper** [comment]
it's `unsafe_div`, which means that it tries to compile to as close to EVM as possible (without any checks).

the docs are also quite clear on this. https://docs.vyperlang.org/en/latest/built-in-functions.html#unsafe_div

**Comment by engn33r** [comment]
Is this something that may change if/when there is a vyper Yul-equivalent? There are currently two division approaches in vyper (safe and unsafe) while solidity has three: 1. checked math 2. unchecked math 3. Yul (div or sdiv)
