### ISSUE TITLE
docs: Adopt a new theme?

### ISSUE THREAD

**Issue by BoboTiG** [vyperlang/vyper#3746]
I would like to propose the usage of another theme for the documentation: [shibuya](https://github.com/lepture/shibuya). A preview is visible here: https://shibuya.lepture.com/

Would you be open to such a change?

Previews of the "Built-in Functions" page:
![Screenshot 2024-01-24 at 22-51-05 Built-in Functions](https://github.com/vyperlang/vyper/assets/2033598/33c2a89e-7f16-4c09-9d2d-bc80d0392e8b)
![Screenshot 2024-01-24 at 22-51-15 Built-in Functions](https://github.com/vyperlang/vyper/assets/2033598/c9eb9211-c0af-46bc-b130-f4c7f349b5b4)

Personally, I only see pros, but that's will depend on each individual:
- no more custom CSS (light/dark themes are already provided, same for the toggle)
- modern design
- responsive

**Comment by BoboTiG** [comment]
I just saw the logo on dark them is invisible. Apart from that, it seems good.

**Comment by charles-cooper** [comment]
i'm interested! is there any way to preview what this would look like?

by the way, we are migrating to new logo -- you can see here https://github.com/vyperlang/vyper-brand/tree/main

**Comment by BoboTiG** [comment]
> i'm interested! is there any way to preview what this would look like?

Awesome, I will put something for a preview.

> by the way, we are migrating to new logo -- you can see here https://github.com/vyperlang/vyper-brand/tree/main

Awesome too! I'll use it for the preview.

**Comment by BoboTiG** [comment]
@charles-cooper I shared the preview link directly in the PR (#3754) ;)
