### ISSUE TITLE
incorrect transient storage codegen for `extract32()` and `slice()`

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3801]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.10

### What's your issue about?

`extract32()` and `slice()` builtins hardcode checks for `STORAGE`, they should use the `location.word_addressable` check instead.

thanks to @trocher for reporting

**Comment by charles-cooper** [comment]
fixed in #3874

**Comment by mozz30-tech** [comment]
> ### Version Information
> 
> * vyper Version (output of `vyper --version`): 0.3.10
> 
> ### What's your issue about?
> 
> `extract32()` and `slice()` builtins hardcode checks for `STORAGE`, they should use the `location.word_addressable` check instead.
> 
> thanks to @trocher for reporting
