### ISSUE TITLE
immutables accessible in `pure` context

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3894]
### Version Information

* vyper Version (output of `vyper --version`): ea7f0818f909a76df099aaf5c0668e90b91a2f26

### What's your issue about?

probably `pure` functions should not be able to access code.

```vyper
IMM: immutable(uint256)

@deploy
def __init__():
    IMM = 1

@pure
@internal
def foo() -> uint256:
    return IMM
```

**Comment by charles-cooper** [comment]
related (but not the same issue): https://github.com/vyperlang/vyper/issues/3830

**Comment by cyberthirst** [comment]
agreed, it breaks referential transparency which i think `pure` funs should satisfy:
```vyper
c: immutable(uint256)

first: public(uint256)
second: public(uint256)

@pure
@internal
def bar() -> uint256:
    return c


@deploy
def __init__():
    self.first = self.bar()
    c = 1
    self.second = self.bar()
```
`self.first()=0` and `self.first()=1`
