### ISSUE TITLE
bug in `pure` access analysis

### ISSUE THREAD

**Issue by pcaversaccio** [vyperlang/vyper#3902]
### Version Information

* vyper Version (output of `vyper --version`): `0.4.0b6+commit.20432c50`
* OS: `linux`
* Python Version (output of `python --version`): `3.11.3`

### What's your issue about?

The commit https://github.com/vyperlang/vyper/commit/20432c505c706ed28d0fa5f743e33a9cfa2dd8c3 introduced a regression. Repro example: Compile [this](https://github.com/pcaversaccio/snekmate/blob/modules/src/snekmate/tokens/ERC721.vy) contract and the [line]( https://github.com/pcaversaccio/snekmate/blob/67534580da3105e408ad5c6de8abca130a637fcd/src/snekmate/tokens/ERC721.vy#L1306) raises with:

```console
Error compiling: src\snekmate\tokens\ERC721.vy
vyper.exceptions.InvalidReference: not a variable or literal: 'uint256'

  contract "src\snekmate\tokens\ERC721.vy:1306", function "_try_recover_vrs", line 1306:49
       1305     """
  ---> 1306     assert s <= convert(_MALLEABILITY_THRESHOLD, uint256), "ECDSA: invalid signature `s` value"
  -----------------------------------------------------------^
       1307
```

**Comment by charles-cooper** [comment]
fixed in https://github.com/vyperlang/vyper/commit/45a225c438918f21611d4c91de887052f020b002
