### ISSUE TITLE
bad user-facing error msg when reporting namespace collision

### ISSUE THREAD

**Issue by cyberthirst** [vyperlang/vyper#3913]
### Version Information

* vyper Version (output of `vyper --version`): `0.4.0b6+commit.e29a584c`

### What's your issue about?
```vyper
import lib1
import lib2 as lib1

initializes: lib1
initializes: lib1
```
yields:
```
vyper.exceptions.NamespaceCollision: 'lib1' has already been declared as a {prev}
```
- notice {prev}

### How can it be fixed?

should be the missing f-string here: https://github.com/vyperlang/vyper/blob/a91af13db9d6d89e6c2139c1b28c490845f06e13/vyper/semantics/namespace.py#L96

**Comment by cyberthirst** [comment]
couldn't we have some lint rule for using '{}' in non-fstring? seen this bug multiple times already

**Comment by trocher** [comment]
https://github.com/vyperlang/vyper/blob/074073f4a42b72d0e7777d6aeba6dfb27a798025/vyper/semantics/types/utils.py#L174
