### ISSUE TITLE
`vyper-serve` is still lingering in `setup.py`

### ISSUE THREAD

**Issue by arjunaskykok** [vyperlang/vyper#3935]
### Version Information

* vyper Version (output of `vyper --version`): doesn't matter
* OS: doesn't matter
* Python Version (output of `python --version`): doesn't matter

### What's your issue about?

You removed `vyper-serve` with this commit: https://github.com/vyperlang/vyper/commit/98f502baea6385fe25dbf94a70fb4eddc9f02f56, but you forgot to remove `vyper-serve` from `setup.py`:

```python
entry_points={
        "console_scripts": [
            "vyper=vyper.cli.vyper_compile:_parse_cli_args",
            "vyper-serve=vyper.cli.vyper_serve:_parse_cli_args",
            "fang=vyper.cli.vyper_ir:_parse_cli_args",
            "vyper-json=vyper.cli.vyper_json:_parse_cli_args",
        ]
    },
```

### How can it be fixed?

Remove `vyper-serve` line.

**Comment by MoigeMatino** [comment]
Taking this on.
