### ISSUE TITLE
multiple eval of `sqrt()` argument

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3972]
### Version Information

* vyper Version (output of `vyper --version`): x.x.x
* OS: osx/linux/win
* Python Version (output of `python --version`):

### What's your issue about?

tracking issue for https://github.com/vyperlang/vyper/security/advisories/GHSA-5jrj-52x8-m64h

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by cyberthirst** [comment]
fixed in: https://github.com/vyperlang/vyper/pull/3976
