### ISSUE TITLE
double eval of the slice start/length args

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3973]
### Version Information

* vyper Version (output of `vyper --version`): x.x.x
* OS: osx/linux/win
* Python Version (output of `python --version`):

### What's your issue about?

tracking issue for https://github.com/vyperlang/vyper/security/advisories/GHSA-r56x-j438-vw5m

**Comment by cyberthirst** [comment]
fixed in: https://github.com/vyperlang/vyper/pull/3976
