### ISSUE TITLE
incorrect topic logging in raw_log for non-literal expressions

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3974]
### Version Information

* vyper Version (output of `vyper --version`): x.x.x
* OS: osx/linux/win
* Python Version (output of `python --version`):

### What's your issue about?

tracking issue for https://github.com/vyperlang/vyper/security/advisories/GHSA-xchq-w5r3-4wg3

**Comment by cyberthirst** [comment]
fixed in: https://github.com/vyperlang/vyper/pull/3977
