### ISSUE TITLE
double eval of raw_args in create_from_blueprint

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#3975]
### Version Information

* vyper Version (output of `vyper --version`): x.x.x
* OS: osx/linux/win
* Python Version (output of `python --version`):

### What's your issue about?

tracking issue for https://github.com/vyperlang/vyper/security/advisories/GHSA-3whq-64q2-qfj6

**Comment by charles-cooper** [comment]
honestly, we should consider just getting rid of the `raw_args=` variant, since it is unused

**Comment by cyberthirst** [comment]
fixed in: https://github.com/vyperlang/vyper/pull/3976
