### ISSUE TITLE
Overriding Storage Allocator Does Not Handle Stateful Modules

### ISSUE THREAD

**Issue by cyberthirst** [vyperlang/vyper#3989]
### Version Information

* vyper Version (output of `vyper --version`): commit vyperlang/vyper@4b4e188ba83d28b5dd6ff66479e7448e5b925030
### Issue description

`OverridingStorageAllocator.set_storage_slots_with_overrides()` does not
handle stateful module imports and initialization properly and will not
allocate storage and transient storage slots for variables or reentrant
functions defined in a sub-module. The issue is only caught at the code
generation stage and would most likely result in the compiler panicking.

credits: @trocher

**Comment by charles-cooper** [comment]
should be fixed in #3789
