### ISSUE TITLE
Constants Cannot Be Imported From .vyi Files

### ISSUE THREAD

**Issue by cyberthirst** [vyperlang/vyper#3991]
### Version Information

* vyper Version (output of `vyper --version`): commit 4b4e188ba83d28b5dd6ff66479e7448e5b925030
### Issue description

Constants cannot be imported from `.vyi` interface files. This behavior
would be useful as one would usually want this for types dependent on
some value (for example a static array with some length).

credits: @trocher

**Comment by charles-cooper** [comment]
closing in favor of #4176
