### ISSUE TITLE
Incorrect error messages during compilation

### ISSUE THREAD

**Issue by cyberthirst** [vyperlang/vyper#3994]
### Version Information

* vyper Version (output of `vyper --version`): commit 4b4e188ba83d28b5dd6ff66479e7448e5b925030
### Issue description

  - In `VariableDecl.validate()`, instead of calling the method
    `self._pretty_location()` to pretty-print the location of the given
    variable, `self._pretty_location` is used.
  - In `_CreateBase.build_IR`, `context.check_is_not_constant` should be
    called with an f-string and not a regular string to have `self._id`
    as the id of the built-in in the error message.

credits: @trocher

**Comment by big1oot** [comment]
Great review. Working on a fix already!

**Comment by charles-cooper** [comment]
these were fixed as of 215de1da6c53fcc97d00f38621d13b622d4a224f (not sure exact commits which fixed them)
