### ISSUE TITLE
Optimizations Missing for Transient Storage

### ISSUE THREAD

**Issue by ritzdorf** [vyperlang/vyper#4017]
### Version Information

* vyper Version (output of `vyper --version` OR linkable commit hash vyperlang/vyper@<commithash>): vyperlang/vyper@b43fface148b45cbd2c90b5d24f77398a63745b5
### Issue Description

Several optimizations performed when copying data from one location to
another have a special path when the source or destination's location is
the storage. No equivalent optimization is done for transient storage:

  - `make_byte_array_copier()`: `has_storage = STORAGE in (src.location,
    dst.location)`
  - `_complex_make_setter()`: `has_storage = STORAGE in (left.location,
    right.location)`

**Comment by charles-cooper** [comment]
resolved in #4015
