### ISSUE TITLE
Missing Constancy Check for Transient Storage

### ISSUE THREAD

**Issue by ritzdorf** [vyperlang/vyper#4018]
### Version Information

* vyper Version (output of `vyper --version` OR linkable commit hash vyperlang/vyper@<commithash>): vyperlang/vyper@b43fface148b45cbd2c90b5d24f77398a63745b5
### Issue Description

In `Stmt._get_target()`, the target is checked not to have a storage
location in the case the context is constant. However, the check is
missing for the case where the target is in transient storage. Given
that the semantic analysis phase should make the compiler fail earlier
if transient storage is accessed in a constant context, no impact of the
missing check could be found.

**Comment by charles-cooper** [comment]
should be fixed in #4015
