### ISSUE TITLE
F-Strings Missing Prefix

### ISSUE THREAD

**Issue by ritzdorf** [vyperlang/vyper#4109]
### Version Information

* vyper Version (output of `vyper --version` OR linkable commit hash vyperlang/vyper@<commithash>): vyperlang/vyper@b43fface148b45cbd2c90b5d24f77398a63745b5
### Issue Description

The following f-strings are missing the `f` prefix:

  - `vyper/ast/nodes.py:1394:41`
  - `vyper/ast/pre_parser.py:207:54`
  - `vyper/builtins/functions.py:1662:39`
  - `vyper/builtins/functions.py:2280:37`
  - `vyper/cli/vyper_compile.py:286:17`
  - `vyper/cli/vyper_compile.py:287:17`
  - `vyper/cli/vyper_json.py:193:29`
  - `vyper/cli/vyper_json.py:202:17`
  - `vyper/cli/vyper_json.py:206:17`
  - `vyper/codegen/arithmetic.py:292:42`
  - `vyper/codegen/core.py:602:32`
  - `vyper/semantics/analysis/base.py:283:41`
  - `vyper/semantics/analysis/utils.py:358:41`
  - `vyper/semantics/namespace.py:96:24`
  - `vyper/semantics/types/base.py:172:29`
  - `vyper/semantics/types/primitives.py:97:34`
  - `vyper/semantics/types/utils.py:163:29`

**Comment by trocher** [comment]
fixed as of https://github.com/vyperlang/vyper/pull/3953
