### ISSUE TITLE
`flag` Can't Be Imported

### ISSUE THREAD

**Issue by ritzdorf** [vyperlang/vyper#4121]
### Version Information

* vyper Version (output of `vyper --version`): commit `4b4e188ba83d28b5dd6ff66479e7448e5b925030`
### Issue description

While it is possible to import events and struct types both from `.vy`
and `.vyi` files, it is not possible to import flags.

For interfaces, this is because `InterfaceT` does not hold the flags
defined in the interface and hence `InterfaceT.get_type_member()` only
returns the set of events and struct types defined.

For modules, similarly, flag types are not added to the set of members
of the `ModuleT` at construction time.

**Comment by trocher** [comment]
> is this fixed as of #3871?

Fixed when importing a module but not for interfaces
