### ISSUE TITLE
Panic on expected interface method implemented as internal.

### ISSUE THREAD

**Issue by AlbertoCentonze** [vyperlang/vyper#4169]
### Version Information

* vyper Version: 0.4.1+commit.f92ef414a

### What's your issue about?

Given an interface file `foo.vyi`
```vyper
@external
def bar():
    ...
```

if the interface is imported and implemented in a module:
```vyper
import foo

implements: foo


# !!!! here we don't add the external modifier
def bar():
    pass
``` 

Not using the external modifier makes the compiler panic.

**Comment by charles-cooper** [comment]
we should really not require any visibility modifier in `.vyi` files (everything is external)
