### ISSUE TITLE
venom bug: `AssertionError: Cannot dup non-existent operand`

### ISSUE THREAD

**Issue by pcaversaccio** [vyperlang/vyper#4215]
Compile [`timelock_controller_mock.vy`](https://github.com/pcaversaccio/snekmate/blob/main/src/snekmate/governance/mocks/timelock_controller_mock.vy) with commit https://github.com/vyperlang/vyper/commit/f2975d76648db3f9cf806a093da17d4b613a8578:

```console
~$ vyper timelock_controller_mock.vy --experimental-codegen --optimize "none" --evm-version "shanghai"
Error compiling: timelock_controller_mock.vy
AssertionError: Cannot dup non-existent operand
```

It doesn't happen if you use `cancun` as EVM version.

**Comment by charles-cooper** [comment]
this is a blocker for 0.4.1

**Comment by pcaversaccio** [comment]
Fixed via https://github.com/vyperlang/vyper/commit/5d8280feec16f86ae1a888e770f20a96113fdabd.
