### ISSUE TITLE
Vyper interface compilation

### ISSUE THREAD

**Issue by romanagureev** [vyperlang/vyper#4232]
## Simple Summary
Check correctness of `.vyi` file.

## Motivation
There is no way to check if `.vyi` file alone was written correctly.

## Specification
Something like:
```
 vyper Interface.vyi
```

**Comment by PatrickAlphaC** [comment]
Would also be helpful to be able to get the abi from an interface

**Comment by charles-cooper** [comment]
tentatively tagging for inclusion in 0.4.1

**Comment by romanagureev** [comment]
Note: discussed with Charles that should compile only with flags `-f ast,annotated_ast,interface,external_interface`

**Comment by charles-cooper** [comment]
And abi!
