### ISSUE TITLE
`vyper -f interface` doesn't include structs in the generated code

### ISSUE THREAD

**Issue by AlbertoCentonze** [vyperlang/vyper#4282]
### What's your issue about?
As per title

### How can it be fixed?

Generated .vyi files should include structs to work correctly

**Comment by heswithme** [comment]
will add here, because related:

when `vyper contract.vy -f interface -o interface.vyi` it adds `pass` after function definitions, however when `boa.load_vyi("interface.vyi")`, it expects `...`. Not sure if boa or vyper shall be fixed here.

**Comment by charles-cooper** [comment]
> will add here, because related:
> 
> when `vyper contract.vy -f interface -o interface.vyi` it adds `pass` after function definitions, however when `boa.load_vyi("interface.vyi")`, it expects `...`. Not sure if boa or vyper shall be fixed here.

that's a vyper issue - it should have been updated for 0.4.0
