### ISSUE TITLE
bug: Example blind_auction.vy does not compile on 0.3.10

### ISSUE THREAD

**Issue by Ninjagod1251** [vyperlang/vyper#4283]
### Version Information
`#pragma version 0.3.10`

* vyper Version (output of `vyper --version`): `3.10.0`
* OS: linux
* Python Version (output of `python --version`): `3.11.4`

### What's your issue about?

The current version of blind_auction.vy does not compile properly due to the updated changes of 0.4.0

I just want to have a working copy of blind_auction.vy at `3.10.0` if you going to keep `^0.3.10` in the pragma

Please include information like:

* full output of the error you received
* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* please try running your example with the `--verbose` flag turned on

### How can it be fixed?
Here is the section of code that needs to be fixed

```
#pragma version 0.3.10
...

@external
def __init__(_beneficiary: address, _biddingTime: uint256, _revealTime: uint256):
...

@external
@payable
def bid(_blindedBid: bytes32):
    # Check if bidding period is still open
    assert block.timestamp < self.biddingEnd

    # Check that payer hasn't already placed maximum number of bids
    numBids: int128 = self.bidCounts[msg.sender]
    assert numBids < MAX_BIDS

    # Add bid to mapping of all bids
    self.bids[msg.sender][numBids].blindedBid = _blindedBid
    self.bids[msg.sender][numBids].deposit = msg.value

    # Increment the number of bids placed by this user
    self.bidCounts[msg.sender] += 1

```

**Comment by charles-cooper** [comment]
check historical versions of the file - i think this should work, reopen if you are still having any issues

https://github.com/vyperlang/vyper/blob/v0.3.10/examples/auctions/blind_auction.vy
