### ISSUE TITLE
Version string inconsistent depending on installation method

### ISSUE THREAD

**Issue by DanielSchiavini** [vyperlang/vyper#4308]
### Version Information
```
~ $ .vvm/vyper-0.4.0 --version
0.4.0+commit.e9db8d9f
~ $ workon boa
(boa) ~/titanoboa $ vyper --version
0.4.0+commit.e9db8d9
```

* OS: linux
* Python Version: 3.12

### What's your issue about?
there is a mismatch between pip-installed vyper and binary-installed vyper (e.g. via vvm).

**Comment by charles-cooper** [comment]
this is the case for pipx vs github release-installed 0.3.10 as well:
```
~ $ vyper --version  # pipx install vyper==0.3.10
0.3.10+commit.9136169
```
```
~ $ .vvm/vyper-0.3.10  --version
0.3.10+commit.91361694
```

**Comment by charles-cooper** [comment]
the number of nibbles in the commit hash depends on the number of commits in the repository -- apparently this is different for the github release and pypi release workflows

https://github.com/vyperlang/vyper/blob/8f9a8cac49aafb3fbc9dde78f0f6125c390c32f0/.github/workflows/build.yml#L59

https://github.com/vyperlang/vyper/blob/8f9a8cac49aafb3fbc9dde78f0f6125c390c32f0/.github/workflows/release-pypi.yml#L22
