### ISSUE TITLE
metadata doesn't report internal functions from modules

### ISSUE THREAD

**Issue by AlbertoCentonze** [vyperlang/vyper#4312]
### Version Information

* vyper Version (output of `vyper --version`): 0.4.0

### What's your issue about?

If contract `A.vy` contains an internal function `foo` and contract `B.vy` contains an external function `bar` that is imported in `A.vy` and called internally:

`vyper -f metadata B.vy` 

will not report the function `foo` from `A.vy`

**Comment by charles-cooper** [comment]
this should be fixed in https://github.com/vyperlang/vyper/pull/4328
