### ISSUE TITLE
Setup.py error

### ISSUE THREAD

**Issue by felixpapaaa** [vyperlang/vyper#4319]
Thanks in advance
solved
Thanks to everyone

**Comment by charles-cooper** [comment]
what steps did you take which led to the issue?

**Comment by felixpapaaa** [comment]
I don’t know exactly. What should I do - could you gimme step by step guidance ? I’m newbie in vyper

**Comment by felixpapaaa** [comment]
![IMG_9184](https://github.com/user-attachments/assets/cfe6137a-0776-4977-a4b2-584775fcfc3b)
What can I do to solve metadata error ?

**Comment by charles-cooper** [comment]
what are you trying to do? typically you would run the test suite if you are working on vyper, but i am guessing you are actually just trying to use vyper?
