### ISSUE TITLE
Implementation of non-lowering for `dstore` and `dstorebytes` instructions in Venom compiler for zkSync support

### ISSUE THREAD

**Issue by harkal** [vyperlang/vyper#4326]
## Summary
The current implementation of the Venom compiler needs an update to handle specific instructions used by zkSync for immutables without lowering them to standard EVM instructions. While zkSync is used as an example here, the principle applies to other architectures also.

## Specification
The current implementation of the Venom compiler needs an update to handle specific instructions used by zkSync for immutables without lowering them to standard EVM instructions. Here are the details:

- **Instructions:** `dstore` and `dstorebytes`

- **Issue:** These instructions are currently being lowered to simpler instructions that fit within the EVM framework. However, for zkSync, these instructions should remain intact as they are directly interpreted by zkSync[*](https://docs.zksync.io/zk-stack/components/compiler/toolchain), not by the standard EVM.

- **Requirement:** 
  - Implement a feature in the Venom compiler that allows `dstore` and `dstorebytes` to pass through compilation without being converted into EVM-compatible bytecode. 
  - This approach will ensure that zkSync can directly read and utilize these instructions from the Venom output.

- **Objective:**
  - To ensure that zkSync can efficiently implement immutables by preserving the `dstore` and `dstorebytes` instructions during compilation.
  - Introduce an architecture selection parameter or treat zkSync as a special EVM version to handle these instructions appropriately.
  - Future enhancements could include a more dynamic opcode management system based on the target architecture's capabilities.

- **Acceptance Criteria:**
  - The compiler should accept parameters that dictate when to compile for zkSync vs. standard EVM.
  - `dstore` and `dstorebytes` should remain in the bytecode output when compiling for zkSync.
  - No functionality break when merging these changes with existing systems where Venom support is not yet implemented.

## Backwards Compatibility

This ticket assumes Venom does not yet support zkSync, ensuring that this implementation will not break current functionality.

## References

PR: feat[venom]: remove dloadbytes and sha3_64 venom instructions #4325 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by charles-cooper** [comment]
resolved in https://github.com/vyperlang/vyper/pull/4410
