### ISSUE TITLE
API - expose `--experimental-codegen` as `--venom`

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyper#4334]
expose `--experimental-codegen` as `--venom` in all compiler i/o (CLI, json input, output_bundle, source code pragma). it will be an alias for `--experimental-codegen`, but eventually we can promote it to be the preferred way.

**Comment by Philogy** [comment]
Wouldn't this imply to some degree that Venom is no longer experimental?

**Comment by charles-cooper** [comment]
> Wouldn't this imply to some degree that Venom is no longer experimental?

kind of :)

it's going to be opt-in, but as of 0.4.1 it's looking like we've ironed out all the major bugs, and https://github.com/vyperlang/vyper/pull/4339 will help with assurances that it produces semantically equivalent code to the legacy pipeline.

it's still going to be "experimental" for some time, but as we get more assurance from fuzz testing, symbolic testing and (tbd) audits, i think we can feel better and better about starting to take the training wheels off.
