### ISSUE TITLE
Support `linkReferences` and `immutableReferences` JSON bytecode output selection

### ISSUE THREAD

**Issue by DaniPopes** [vyperlang/vyper#4389]
`linkReferences` and `immutableReferences` are not supported and providing it reports "Invalid outputSelection - 'evm.bytecode.linkReferences'".

In Foundry we must skip passing this to Vyper when using the same standard JSON as for Solidity.

I don't know if this is feasible to implement for Vyper, but I didn't see any issues regarding this so I'm raising the question here.

**Comment by charles-cooper** [comment]
what do `linkReferences` and `immutableReferences` do? vyper does not have those in its output.

**Comment by DaniPopes** [comment]
https://docs.soliditylang.org/en/latest/using-the-compiler.html

> evm.bytecode.linkReferences - Link references (if unlinked object)
> evm.deployedBytecode.immutableReferences - Map from AST ids to bytecode ranges that reference immutables

They're byte ranges into the bytecode, `linkReferences` is for "unlinked" library addresses, `immutableReferences` is for immutables.

We use `linkReferences` to link external libraries.

It would be useful if the compiler would at least accept these options and provide an empty output, but feel free to close if you don't believe so.

**Comment by charles-cooper** [comment]
hmm. since these aren't used by the vyper compiler and they don't have any meaning, it makes sense to reject them during validation. going to close as wontfix, but we can revisit in the future if this changes.
