### ISSUE TITLE
VIP: ABI Method in contracts

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#485]
This is the suggested template for new VIPs.

## Preamble

VIP: 485
Title: ABI Method in contracts
Author: @fubuloubu
Type: Standard Track
Status: Draft
Created: 2017-11-19

## Simple Summary
Have Viper create an additional ABI method that returns the ABI on-demand and is deployed with the contract.

## Abstract
You create a smart contract, deploy it to the Ethereum blockchain and want to share it with the world! Now all you have to do is share your ABI (or get users to generate it themselves) so that web3 can interact with it. Wouldn't it be awesome if there were a standard method (proposal `get_abi() -> bytesN:`) that was auto-magically generated by the compiler and added to your contract, so that other tools could directly query this to get the interface? I think so

## Motivation
This would make it simpler for for development integration, and for third-party/dynamic applications to interact with contracts on the Ethereum blockchain by being able to query the ABI.

## Specification
Pretty simple, just create a method called `get_abi()` in every contract that returns the result of the abi processor in whatever format makes the most sense (JSON, Native, etc.). Have it be configurable in the compiler so if someone doesn't want it, they can opt-out. It might need an additional `get_abi_gas_cost() -> num:` method in order to get the gas estimation for the `get_abi()` method itself (as it will be different between contracts and we need it to run the method).

Here's something really cool this could enable (if we decide this sticks with Viper's principles): Stateful gas calculation. We could compute gas costs for methods with non-constant variables (strings, var_lists, etc.) by simply figuring out the correct linear sequence (`methodGasCost = G1*global1.length + G2*global2.length + ... + G3*globalN.length + G_constant`) and putting it in this method before returning the ABI with the gas estimates based on current state. This might be a much further off kind of idea, but I think it would be really cool.

## Backwards Compatibility
Backwards compatible as long as no one used the `get_abi()`/`get_abi_gas_cost()` method, which is probably okay.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Also, if this were enacted `contract` types could have their ABI checked during init/runtime setting by first querying the ABI from the contract being retreived (if that contract contains that `get_abi()` method) and then testing against the expected method signature provided e.g.:

```python
class Foo():
    def set_lucky(_lucky: num): pass

def set_lucky(arg1: address, arg2: num):
    Foo(arg1).set_lucky(arg2)
```
which would perform something like this behind the scenes (or after processor):
```python
class Foo():
    def set_lucky(_lucky: num): pass

def set_lucky(arg1: address, arg2: num):
    if address.get_abi exists:
        assert address.get_abi()['set_lucky'] is not None
        assert address.get_abi()['set_lucky']['inputs'] is { 'name' : '_lucky', '_type' : 'num' }
        assert address.get_abi()['set_lucky']['outputs'] is None
    # NOTE: above is not valid Viper syntax, but I hope you get the idea
    Foo(arg1).set_lucky(arg2)
```

**Comment by fubuloubu** [comment]
TODO:
Benchmark the increased cost for this

**Comment by ericssonaxel** [comment]
The standard interface for in-contract abi strings should probably be proposed through the EIP track, and then implemented by both Solidity and Vyper.

**Comment by fubuloubu** [comment]
Withdrawn. Relevant resources:
- https://eips.ethereum.org/EIPS/eip-205
- https://www.ethpm.com/
