### ISSUE TITLE
VIP: Restrict functions that return to be `@constant`

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#641]
## Preamble

VIP: #641
Title: Restrict functions that return to be `@constant`
Author: @fubuloubu
Type: Standard
Status: Draft
Created: 2018-01-22

## Simple Summary
Enforce only `@constant` methods can return. Non-`@constant` methods should use Logs instead.

## Abstract
In web3, if you make a state-changing transaction, the API will return the transaction hash for that transaction instead of any return values. After the transaction is accepted, the logs may be used for state feedback and/or further processing (via promises/callbacks). It typically isn't helpful for a computed variable to be returned in a state-changing function because of this, instead preferable to use Logs to maintain computed variables (so as to leverage the promise/callback techniques that Web3 provides for Logs). Let's make this the explicit way Vyper handles things.

## Motivation
This will simplify how to write different kinds of methods so it is more obvious how the method should be used. From a usage perspective, this will eliminate any issues with trying to use the return values from a transacted method, enforcing the use of Logs for that purpose.

## Specification
Pretty straightforward, if it has a return type and is not marked `@constant` throw a compiler error.

## Backwards Compatibility
This is not backwards compatible if anyone was using non-`@constant` methods to return before.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
Hmm I think this will conflict with quite a number of existing contracts, ERC20 for instance.
```
function transfer(address to, uint tokens) public returns (bool success);
function approve(address spender, uint tokens) public returns (bool success);```

**Comment by fubuloubu** [comment]
Good point. Although, if I recall correctly, our version of ERC20 enforces this as a rule. I think it's a bad practice that should be discouraged, but you're right about several important existing use-cases.

**Comment by DavidKnott** [comment]
Discouraging what's currently considered a bast practice seems like it might confuse developers.

**Comment by fubuloubu** [comment]
Why is it a best practice? `send` is discouraged vs `transfer` for ether. Is there a reason why `returns success` for ERC20 is preferable to throwing? It seems contentious to me.

Vyper being designed to be safe and easy to the reader, I would think the need codify or at least encourage a standard design pattern would be important. `input validation -> logic -> logic validation -> log` I think is becoming that preferred design standard.

**Comment by DavidKnott** [comment]
It is the preferred way for writing Solidity now, but goes against the ERC20 standard which isn't going anywhere.  What if we don't allow it, but create a flag so that people can comply with ERC20 if they want?

**Comment by fubuloubu** [comment]
Oh, I was leaning more towards warning then error based on @jacqueswww's comment, but the ERC20 precompile and interactions with existing ERC20 contracts wouldn't be affected, and the warning would only be there for that specific standard, which hopefully gets updated to a better standard over time.

**Comment by jacqueswww** [comment]
Note: This would be an excellent warning message ;) Allowing old contract styles to compile.

**Comment by fubuloubu** [comment]
Closing as this is considered a best practice, and not really an actionable issue
