### ISSUE TITLE
Solidity to Vyper translator

### ISSUE THREAD

**Issue by Johan-Pretorius** [vyperlang/vyper#648]
## Preamble
VIP: [#648](https://github.com/ethereum/vyper/issues/648)
Title: Solidity to Vyper translator
Author: @Johan-Pretorius
Type: Standard Track
Status: Draft
Created: 2018-01-26

## Simple Summary
If one can convert Solidity contracts to Vyper code, one can leverage a huge amount of previous work and build on to it.

## Abstract
One of the most powerful aspects of open-development communities is the ability to leverage work that was done by others (etc openZeppelin, ERC-20, MiniMe all get used and extended to build new tools). It would be extremely useful if there was a converter from Solidity to Vyper, so that work done in Solidity can be ported to, and extended in, Vyper.

## Motivation
The motivation is to enable developers to jump-start being productive by leveraging the mass of work that has already been done in Solidity.

## Specification
1. Download source Solidity contract (and all contracts in the hierarchy tree).
2. Run a tool to translate source Solidity contracts into Vyper code.
3. Output new Vyper source code file.

## Backwards Compatibility
A new tool, hence no backward compatibility issues.

## Copyright
Copyright and related rights waived via CC0

**Comment by fubuloubu** [comment]
Neither language is that complicated, but both make very different tradeoffs that would make creating a tool like this very difficult. Namely, solidity leverages inheritance to a large extent, whereas Vyper disallows it and currently doesn't have a method for program extension (although we're looking into composition as a model). Each language has to deal with many different small security tradeoffs, so this is not something that can be trivially rewritten by a translator.

Once Vyper gets more traction, people will create libraries of model code like OpenZeppelin has done with solidity. Smart contracts are not hugely complicated codebases, and can be translated manually in a few days to a few weeks without an automated tool. Wouldn't you much rather have a security expert well versed in this nuance accomplish this task, over some tool that could never understand that nuance when you have thousands to millions of dollars on the line?

That being said, having a section in the docs about translated as thing Solidity to Vyper would be handy.

**Comment by fubuloubu** [comment]
There are several examples in [our docs](https://vyper.readthedocs.io/en/latest/vyper-by-example.html) that are derived from Solidity contracts of the same name. I don't see the original suggestion in this Issue ever being made, so I am closing this for now
