### ISSUE TITLE
VIP:  Support CREATE2 opcode

### ISSUE THREAD

**Issue by DavidKnott** [vyperlang/vyper#649]
## Preamble
    VIP: <to be assigned>
    Title: Create contract built in function
    Author: David knott
    Type: Sharding Track
    Status: Draft
    Created: 2018-01-27
    Requires: Sharding opcodes #632

## Simple Summary
Add a built in contract creating function that utilizes `CREATE2` sharding opcode.

## Motivation
Vyper users need a way to utilize `CREATE2`.

## Specification
The built in will be called `create_contract` and will be used like:
```
def foo():
    create_contract(value, salt, contract_to_be_deployed_bytes)
```
`contract_to_be_deployed_bytes` will become `mem_start` and `mem_size` for `CREATE2`

## Backwards Compatibility
Practically speaking this is backwards compatible, but it's not completely because it will make `create_contract` reserved so an contract using `create_contract` as a variable/function name will become invalid.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
So, this is like a contract factory kind of thing?

**Comment by DavidKnott** [comment]
It could be used that way, or it could just deploy a contract once.

**Comment by fubuloubu** [comment]
I mean, this is on-chain deployment through an opcode?

**Comment by fubuloubu** [comment]
Also, can you fix the title to "Sharding" lol

**Comment by fubuloubu** [comment]
@hwwhww @jacqueswww Deprecate due to changing plans for sharding?

**Comment by jacqueswww** [comment]
I think create2 is still going live in Constantinople 2.0 ?

**Comment by haydenadams** [comment]
create2 should def get some priority once Constantinople hits. Lots of interesting stuff it enables.

**Comment by cartercarlson** [comment]
@haydenadams I was thinking about that too...  Would it be possible to add create2 to a mapping?

**Comment by charles-cooper** [comment]
https://medium.com/coinmonks/on-efficient-ethereum-storage-c76869591add has some techniques for cheaper store/load.

**Comment by haydenadams** [comment]
Any updated thoughts on this? Would love this to be implemented in the next 1-2 months. 

Maybe add it to the next meeting?
https://github.com/ethereum/vyper/issues/1518

**Comment by cryptoman04** [comment]
curious if this is still in progress?

**Comment by fubuloubu** [comment]
@cryptoman04 it is on the roadmap but currently not one of our main focuses, sorry

**Comment by charles-cooper** [comment]
I think this is done in https://github.com/vyperlang/vyper/pull/2460, @fubuloubu can you confirm?

**Comment by fubuloubu** [comment]
lgtm :+1:
