### ISSUE TITLE
create_with_code_of() does not execute __init__

### ISSUE THREAD

**Issue by haydenadams** [vyperlang/vyper#773]
* vyper Version: 0.0.4
* pyethereum Version: 2.3.1
* OS: macOS
* Python Version: 3.6.4

### What's your issue about?
My post might be unnecessary if https://github.com/ethereum/vyper/issues/649 is going to be the standard factory pattern. 

I'm working on a factory contract that uses `create_with_code_of()` to launch exchange contracts. 

<img width="575" alt="screen shot 2018-04-10 at 4 17 01 pm" src="https://user-images.githubusercontent.com/9343483/38581361-a6637a84-3cda-11e8-9c05-870bdf25ed1f.png">

Ideally I want the contract that is launched to know the address of the factory. Since `create_with_code_of()` does not support passing arguments, I tried setting it in the constructor of the exchange:

<img width="324" alt="screen shot 2018-04-10 at 3 19 21 pm" src="https://user-images.githubusercontent.com/9343483/38580892-2a42abd8-3cd9-11e8-9cf5-f0f5f382897c.png">

unfortunately, this does not work:

<img width="861" alt="screen shot 2018-04-10 at 4 19 59 pm" src="https://user-images.githubusercontent.com/9343483/38581504-1b7fdb6e-3cdb-11e8-9671-bcb38d189c08.png">

### How can it be fixed?

Allow contracts created using `create_with_code_of()` to recognize msg.sender in the constructor. 

Or not if https://github.com/ethereum/vyper/issues/649 is implemented

Or I'm missing something/there is a better factory pattern I should be using that allows passing parameters?

#### Cute Animal Picture

![cute-kittens-67-57b32a998544a__6051](https://user-images.githubusercontent.com/9343483/38581697-98c0923a-3cdb-11e8-8238-d14faaf9afdd.jpg)

**Comment by jacqueswww** [comment]
@haydenadams I will have to dig deeper exactly what's wrong. Could it be that the __init__ code isn't ever executed?

**Comment by haydenadams** [comment]
@jacqueswww Tried setting something else in **init** and it returned 0. As far as I can tell, **init** is never executed in `create_with_code_of()`

**Comment by jacqueswww** [comment]
That's what I suspected, basically the init code isn't part of the runtime code on chain. We'll have to figure out a new function or extension of the existing function that allows you to scrape the init code.

**Comment by jacqueswww** [comment]
In the meantime you can build a fake init function with a boolean that can only be called once :-P

**Comment by haydenadams** [comment]
Makes sense, thanks! Already implemented that as a temporary solution.

**Comment by haydenadams** [comment]
In my current solution, the factory does a `raw_call()` on the new contract immediately after calling `create_with_code_of()`. 

Factory
<img width="905" alt="screen shot 2018-04-23 at 4 30 55 pm" src="https://user-images.githubusercontent.com/9343483/39151649-db809128-4713-11e8-82e5-c73a803e0b66.png">

Exchange
<img width="725" alt="screen shot 2018-04-23 at 4 31 25 pm" src="https://user-images.githubusercontent.com/9343483/39151664-e6d92a6c-4713-11e8-8739-0176bda60510.png">

Since the contract creation and raw_call are done in the same function, and `setup()` can only be called once, it essentially functions as a constructor.

**Comment by haydenadams** [comment]
@jacqueswww 

>  That's what I suspected, basically the init code isn't part of the runtime code on chain. We'll have to figure out a new function or extension of the existing function that allows you to scrape the init code.

btw b/c of this, Unisocks classic was able to verify on etherscan with this code:
https://etherscan.io/address/0xf7a5a8a95491ec170738434963b649671b563b88#code

despite their init function being different. This is actually kind of a dangerous bug I think?

**Comment by fubuloubu** [comment]
> Unisocks classic

🤣🤣🤣

**Comment by haydenadams** [comment]
Nice!
