### ISSUE TITLE
VIP: Add support for specifying byte array lengths when decoding RLPLists

### ISSUE THREAD

**Issue by mkeen** [vyperlang/vyper#818]
* VIP: 818
* Title: Add support for specifying byte array lengths when decoding RLPLists
* Author: Mike Keen
* Type: Standard Track
* Status: Draft
* Created: 2018-05-11

### Simple Summary
Vyper's RLP implementation does not currently support specifying a length for byte arrays while decoding, resulting in too many bytes being allocated for byte arrays when decoding them from RLP. I suggest an enhancement which would allow an implementer to specify a fixed size for byte arrays while decoding RLP data. I am willing to explore implementing this. But would like some feedback on this first.

### Abstract
`_RLPList` currently does not allow for RLP `bytes` members' lengths to be specified when decoding. This works:

    encoded_message: bytes <= 1024 = ...
    values = RLPList(encoded_message, [int128, bytes32, int128, int128, bytes])
    sig: bytes <= 1024 = values[4]

This does not work:

    encoded_message: bytes <= 1024 = ...
    values = RLPList(encoded_message, [int128, bytes32, int128, int128, bytes])
    sig: bytes <= 934 = values[4]

This also does not work:

    encoded_message: bytes <= 1024 = ...
    values = RLPList(encoded_message, [int128, bytes32, int128, int128, bytes <= 934])
    sig: bytes <= 934 = values[4]

As a consequence of this line...

https://github.com/ethereum/vyper/blob/0d92d86752bcfca875e042cec6048488db3d479c/vyper/functions/functions.py#L431

...Vyper simply allocates the same number of bytes for `bytes` members as was allocated for the `ByteArrayType` that represents the entire encoded message. This means if the whole encoded message's `ByteArrayType` has a `maxlen` of 1024 bytes, then every `bytes` member will get 1024 bytes when they are decoded.

### Motivation

In researching [another issue](https://github.com/ethereum/casper/issues/110), I found the behavior described above.

I think the ability to enforce a size for byte arrays in this context is syntactically desirable and I also think that allocating definitively too much memory for anything is undesirable long term behavior.

### Specification

I propose supporting the following syntax:

    encoded_message: bytes <= 1024 = ...
    values = RLPList(encoded_message, [int128, bytes32, int128, int128, bytes <= 934])
    sig: bytes <= 934 = values[4]

This will require modifying the following logic:

https://github.com/ethereum/vyper/blob/0d92d86752bcfca875e042cec6048488db3d479c/vyper/functions/functions.py#L430-L438

Currently, passing in a spec for a fixed size such as `[int128, bytes32, int128, int128, bytes <= 934]` results in the following being executed:

https://github.com/ethereum/vyper/blob/0d92d86752bcfca875e042cec6048488db3d479c/vyper/functions/functions.py#L435

So, this logic...

https://github.com/ethereum/vyper/blob/0d92d86752bcfca875e042cec6048488db3d479c/vyper/functions/functions.py#L434

...would need to be made more robust, to support the proposed byte size annotation

I'm certain that in the course of implementing this, other structural items in `_RLPList` will need to be touched.

Will need to add at least one new test.

### Backwards Compatibility

I propose still supporting the following (works today) syntax...

    encoded_message: bytes <= 1024 = ...
    values = RLPList(encoded_message, [int128, bytes32, int128, int128, bytes])
    sig: bytes <= 1024 = values[4]

...in addition to what I propose adding. This would keep existing behavior in-tact while exposing the enhanced behavior I am proposing.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Moved to deffered because we are removing RLP

**Comment by iamdefinitelyahuman** [comment]
#1936 makes this irrelevant.
