### ISSUE TITLE
VIP: Custom units in convert

### ISSUE THREAD

**Issue by ben-kaufman** [vyperlang/vyper#837]
## Preamble

    VIP: 837
    Title: Custom units in convert
    Author: Ben Kaufman
    Type: Standard Track
    Status: Draft
    Created: 2018-05-24

## Simple Summary
Allow specifying custom units when using convert.

## Abstract
Allow specifying custom units when using convert.

## Motivation
Currently, we can only use ``convert`` for a base value, I think we should also be able to use it in order to set a unit.

## Specification
I think it should look like this:
``convert(value, 'uint256(some_unit)')``

## Backwards Compatibility
This should be backwards compatible

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/10667901/40490438-2e63bf32-5f74-11e8-81e6-9aaa02ed576d.png)

**Comment by djrtwo** [comment]
I think that `convert` should not let you drop units. You should have to use the explicit `as_unitless_number` call for that.

I would expect the following the throw because it is implicitly dropping the unit. 
```python
value: int128(unit) = 50.0
new_value: uint256 = convert(value, 'uint256')
```

and I would expect the following to succeed
```python
value: int128(unit) = 50.0
new_value: uint256(unit) = convert(value, 'uint256(unit)')
```

I also don't think you should be able to add units via convert.

**Comment by ben-kaufman** [comment]
I'm not sure about dropping units because most time I would expect units to have a certain type so if I convert a variable with unit it should drop the unit, but maybe we do need to change it for the sake of explicitly.

Why don't you think we should add custom units in convert? There are certain cases where adding a unit in other way would be very difficult and inefficient. For example:
```
units: {
    cm: "centimeter"
}

@public
def foo():
    num1: uint256(cm) = convert(10, 'uint256')
```
This won't compile...

**Comment by djrtwo** [comment]
Sorry, I misread the original issue 😬 

I think custom units shouldn't be dropped when using `convert`. I don't think `convert` should add units.

**Comment by ben-kaufman** [comment]
Another usage for convert with adding a unit
```
units: {
    cm: "centimeter",
    m: "meters"
}

@public
def foo(num1: uint256(cm)):
    num2: uint256(m) = num1/ 100
```

**Comment by fubuloubu** [comment]
That last suggestion is interesting (for example, with `ether` to `wei` unit conversions), but it requires associations to built into the units to work correctly.

Something like:
```python
units: {
    cm: "centimeter",
    m: "meter"
}
conversions: {
    m: 100*cm
}

@public
def foo(num1: uint256(cm)):
    num2: uint256(m) = num1/ 100
```

This may lead into an entire sub-language of units.

**Comment by fubuloubu** [comment]
@jacqueswww this seems very related to our discussion on Monday

**Comment by iamdefinitelyahuman** [comment]
Closing this - #1896 makes it irrelevant.
