### ISSUE TITLE
Vyper release management CI

### ISSUE THREAD

**Issue by fubuloubu** [vyperlang/vyper#929]
We should have CI for release management if possible.

Snapcraft:
Can the current beta tag be the `--beta` option for snap? Can we link this to a tag?
Can we also have `--edge` be a nightly based off the master branch? Can we remove the `--devmode`/`--jailmode` qualifiers?

What other things can we automate releases based off master commits/PRs/merges? PyPI? Docker? Brew?

**Comment by jacqueswww** [comment]
We can remove the devmode now I believe. 
`--edge` gets built automatically on each push to master so that is sorted.
`--beta` will probably have to be done by hand.

**Comment by iamdefinitelyahuman** [comment]
I think this can be closed now?
