### ISSUE TITLE
VIP: add conversion from bytes32 to fixed size byte arrays

### ISSUE THREAD

**Issue by connordwoods** [vyperlang/vyper#967]
## Simple Summary
converting bytes should be given more convertible types, such as bytes32 to bytes[1] (fixed type)

## Abstract
you can only convert bytes32 to int128 and bytes256, making it hard to trim bytes32 (such as sha3 digest) into bytes[x]

## Motivation
this would be in line with the goal to increase code legibility without using slicing

## Specification

this implementation is compilable in Solidity through casting

```
// hash
                bytes32 hashOfSerialNumber = keccak256(serialNumber);

// get first 8 bits as as 1 byte, uint8 used in Sol but uint256 viable when smaller uint not available
                bytes1 truncatedHash = bytes1(hashOfSerialNumber);
                uint8 unsignedTruncatedHash = uint8(truncatedHash);
```

suggested syntax

`convert(bytes32, bytes[1]) -> covertedVar`

## Backwards Compatibility
no expected compatibility errors

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by nrryuya** [comment]
@jacqueswww 

`slice()` doesn't receive `bytes32` so there is no easy way to convert `bytes32` to fixed sized byte arrays?
https://github.com/ethereum/vyper/blob/e3238561d0555a2a9dc555819ee14526af2d8fcf/vyper/functions/functions.py#L104

**Comment by charles-cooper** [comment]
closing as dup, tracking in https://github.com/vyperlang/vyper/issues/3349
